'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {DatabaseSync}=require('node:sqlite');
const {AuthorityStore}=require('../src/authority-store');
const {AuthorityMemory}=require('../src/authority-memory');
const {canonicalHash,canonicalSerialize,verifyLedgerChain}=require('../src/authority-hash');
const {migrateAuthority}=require('../src/authority-schema');
const {migrateLegacy,inventory}=require('../src/authority-migration');
const {evaluateRouting}=require('../src/authority-router');
function fixture(t){let now=1000;const db=new DatabaseSync(':memory:'),s=new AuthorityStore(db,{now:()=>now}),m=new AuthorityMemory(s);t.after(()=>db.close());return {db,s,m,advance:ms=>{now+=ms;}};}
const observation=(extra={})=>({session_id:'session-one',chunk_id:'chunk-one',timestamp:1,speaker:'operator',claim:'No micro-prompts.',kind:'personal_preference',subject_key:'workflow.micro_prompts',value:'forbidden',...extra});
const input=s=>({operator_id:s.operatorId,include_personal:true,required_keys:['workflow.micro_prompts']});
function accepted(t){const f=fixture(t),p=f.s.createProject({name:'Proof'}),m=f.s.createMission({project_id:p.id,envelope:{objective:'Read-only fixture',criteria:[]}}),r=f.s.startRun({mission_id:m.id,mission_revision:1,agent_id:'host'}),result=f.s.recordResult({mission_id:m.id,mission_revision:1,run_id:r.id,status:'completed',summary:'Observed fixture'}),v=f.s.verifyResult({mission_id:m.id,mission_revision:1,result_id:result.id,status:'passed',verifier_id:'independent-checker',evidence:[{observed:'fixture'}]});f.s.setState(m.id,'awaiting_acceptance');return {...f,mission:m,run:r,result,verification:v};}
test('JCS canonical ordering, RFC number example, Unicode and malformed inputs',()=>{
 assert.equal(Buffer.from(canonicalSerialize({numbers:[333333333.33333329,1E30,4.50,2e-3,1e-27]})).toString(),'{"numbers":[333333333.3333333,1e+30,4.5,0.002,1e-27]}');
 assert.equal(canonicalHash({b:2,a:1}),canonicalHash({a:1,b:2}));assert.notEqual(canonicalHash({a:1}),canonicalHash({a:2}));
 for(const value of [NaN,Infinity,undefined,1n,'\ud800',{a:undefined},new Date(),[,1]])assert.throws(()=>canonicalSerialize(value));
 const cycle={};cycle.x=cycle;assert.throws(()=>canonicalSerialize(cycle));
 assert.notEqual(canonicalHash('é'),canonicalHash('e\u0301'));
});
test('schema is replayable, foreign keys enabled, revisions immutable',t=>{const {s,db}=fixture(t);assert.equal(migrateAuthority(db),false);assert.equal(db.prepare('PRAGMA foreign_keys').get().foreign_keys,1);const m=s.createMission({envelope:{objective:'one'}});assert.throws(()=>db.prepare('UPDATE authority_mission_revisions SET objective=?').run('changed'));assert.throws(()=>s.startRun({mission_id:m.id,mission_revision:2,agent_id:'host'}));s.reviseMission(m.id,{objective:'two'},1);assert.equal(s.getMission(m.id).current_revision,2);assert.equal(s.getMissionRevision(m.id,1).objective,'one');assert.throws(()=>s.reviseMission(m.id,{objective:'stale'},1));assert.equal(s.integrity().ok,true);});
test('result, verification, acceptance and stale evidence remain separate',t=>{const f=accepted(t);assert.equal(f.s.listAcceptancesForMission(f.mission.id).length,0);assert.equal(f.s.getMission(f.mission.id).current_state,'awaiting_acceptance');assert.throws(()=>f.s.accept({mission_id:f.mission.id,mission_revision:1,verification_id:f.verification.id,reason:'self'}, {type:'agent',id:'host'}));f.s.reviseMission(f.mission.id,{objective:'New objective'},1);assert.throws(()=>f.s.accept({mission_id:f.mission.id,mission_revision:1,verification_id:f.verification.id,reason:'stale'}));});
test('cross-mission results fail and audit rows cannot cascade away',t=>{const f=accepted(t),m=f.s.createMission({envelope:{objective:'other'}});assert.throws(()=>f.s.recordResult({mission_id:m.id,mission_revision:1,run_id:f.run.id,status:'completed'}));assert.throws(()=>f.db.prepare('DELETE FROM authority_missions WHERE id=?').run(f.mission.id));});
test('per-project chain detects tampered payload, deletion, and wrong genesis',t=>{const {s,db}=fixture(t);s.createProject({name:'A'});s.createProject({name:'B'});const rows=db.prepare('SELECT * FROM authority_ledger_entries ORDER BY project_id,sequence').all();assert.equal(verifyLedgerChain(rows).valid,true);assert.throws(()=>db.prepare("UPDATE authority_ledger_entries SET payload_json='{}'").run());for(const modified of [[{...rows[0],previous_hash:'0'.repeat(64)},...rows.slice(1)],[{...rows[0],payload_json:'{}'},...rows.slice(1)],[{...rows[0],sequence:2},...rows.slice(1)]])assert.equal(verifyLedgerChain(modified).valid,false);});
test('durable grant/run binding and nonce replay fail closed',t=>{const f=accepted(t);const g=f.s.issueGrant({mission_id:f.mission.id,mission_revision:1,run_id:f.run.id,policy_version:'test',expires_at:2000,signature_reference:'broker:fixture',capabilities:[{capability:'fs:read',scope:{path:'fixture'}}]});const n={grant_id:g.id,run_id:f.run.id,nonce:'one',request_hash:canonicalHash({read:'fixture'})};assert.equal(f.s.consumeNonce(n).consumed,true);assert.throws(()=>f.s.consumeNonce(n));f.advance(1001);assert.throws(()=>f.s.consumeNonce({...n,nonce:'two'}));});
test('real-shaped observation promotion provenance and later retrieval are idempotent',t=>{const {s,m}=fixture(t),c=m.ingest(observation(),s.operator);assert.equal(c.status,'candidate');assert.equal(m.ingest(observation(),s.operator).id,c.id);assert.throws(()=>m.ingest(observation({claim:'changed'}),s.operator));assert.throws(()=>m.promote(c.id,{}, {type:'agent',id:'host'}));const memory=m.promote(c.id,{},s.host);assert.equal(m.promote(c.id,{},s.host).id,memory.id);const a=m.build(input(s)),b=m.build(input(s));assert.equal(a.context_hash,b.context_hash);assert.equal(a.items[0].value,'forbidden');assert.equal(m.provenance(memory.id,s.operator).observation.chunk_id,'chunk-one');assert.equal(s.integrity().ok,true);});
test('malformed, spoofed, secret-bearing and wrong-owner observations rejected',t=>{const {s,m}=fixture(t);for(const packet of [observation({speaker:'agent'}),observation({claim:'Authorization: Bearer abcdefghijklmnop'}),observation({timestamp:'today'}),observation({claim:'Remember something unrelated'}),observation({arbitrary:true})])assert.throws(()=>m.ingest(packet,s.operator));assert.throws(()=>m.ingest(observation(),{type:'agent',id:s.operatorId}));const c=m.ingest(observation(),s.operator);assert.throws(()=>m.promote(c.id,{}, {type:'operator',id:'other'}));});
test('scoped conflict waits for affected domain but not unrelated diagnostics',t=>{const {s,m}=fixture(t);const base={kind:'project_operational',operator_id:s.operatorId,scope:'global',subject_key:'forecast.live_status',source_hash:canonicalHash('source'),source_refs:[]};const a=m.propose({...base,value:'OFF'},s.operator);m.promote(a.id,{source_type:'operator_decision',domains:['forecast']},s.operator);const b=m.propose({...base,value:'LIVE'},s.operator);const conflict=m.promote(b.id,{source_type:'operator_decision',domains:['forecast']},s.operator);assert.equal(conflict.status,'conflict');assert.equal(m.build({operator_id:s.operatorId,domains:['forecast']}).state,'WAIT');assert.equal(m.build({operator_id:s.operatorId,domains:['git']}).state,'ready');});
test('TTL, forgetting, supersession, privacy and cross-project filters precede relevance',t=>{const {s,m,advance}=fixture(t),c=m.ingest(observation(),s.operator),a=m.promote(c.id,{ttl_ms:10},s.operator);advance(11);assert.equal(m.build(input(s)).state,'WAIT');assert.throws(()=>m.forget(a.id,{type:'agent',id:'host'}));m.forget(a.id,s.operator);assert.equal(m.build(input(s)).state,'WAIT');assert.throws(()=>m.build({...input(s),operator_id:'wrong'}));const p=s.createProject({name:'Scoped'}),q=s.createProject({name:'Other'});const c2=m.ingest(observation({chunk_id:'two',scope:'project_specific',project_id:p.id}),s.operator);m.promote(c2.id,{privacy:'restricted_security'},s.operator);assert.equal(m.build({...input(s),project_id:p.id,privacy:'internal'}).state,'WAIT');assert.equal(m.build({...input(s),project_id:q.id,privacy:'restricted_security'}).state,'WAIT');assert.equal(m.build({...input(s),project_id:p.id,privacy:'restricted_security'}).state,'ready');});
test('deep ContextPack diff preserves removal reason and change significance',t=>{const {s,m}=fixture(t);const c=m.ingest(observation(),s.operator),a=m.promote(c.id,{},s.operator),before=m.build({...input(s),required_keys:[]});m.forget(a.id,s.operator);const after=m.build({...input(s),required_keys:[]}),diff=m.diff(before.id,after.id,s.operator);assert.equal(diff.diff[0].kind,'removed');assert.equal(diff.diff[0].exclusion.reason,'forgotten');assert.equal(m.diff(before.id,after.id,s.operator).id,diff.id);});
test('episodic memory requires acceptance and replay produces one memory',t=>{const f=accepted(t);assert.throws(()=>f.m.distill('unaccepted'));const a=f.s.accept({mission_id:f.mission.id,mission_revision:1,verification_id:f.verification.id,reason:'Explicit fixture acceptance'});const x=f.m.distill(a.id),y=f.m.distill(a.id);assert.equal(x.id,y.id);assert.equal(f.db.prepare("SELECT count(*) n FROM authority_memories WHERE kind='mission_episodic'").get().n,1);assert.equal(x.value.provider,null);});
const routeInput={task_class:'focused_refactor',required_capabilities:['coding'],memory_state:'ready',context_current:true,privacy:'internal',external_allowed:true};
const candidate=(extra={})=>({agent_id:'claude',runtime_id:'claude-cli',enabled:true,capabilities:['coding'],assurance:2,locality:'external',availability:'available',observed_at:1000,auth_state:'observed',quota_state:'unknown',circuit_state:'closed',cost_class:'subscription',...extra});
test('router hard gates, provider-free Pi, truthful fallback, and unknown cost',()=>{const a=candidate(),pi=candidate({agent_id:'host',runtime_id:'native',locality:'local',cost_class:'local',capabilities:['local_tools'],isolation_verified:true});const r=evaluateRouting({...routeInput,task_class:'local_diagnostics',required_capabilities:['local_tools']},[a,pi],1000);assert.equal(r.selectedAgent,'host');assert.equal(r.selectedProvider,null);for(const changed of [{writer_conflict:true},{privacy:'restricted_security'},{context_current:false},{maxCostUsdBoundary:1},{required_capabilities:['unsupported']}])assert.equal(evaluateRouting({...routeInput,...changed},[a],1000).state,'WAIT');assert.equal(evaluateRouting(routeInput,[candidate({provider_id:'deepseek'})],1000).state,'WAIT');assert.equal(evaluateRouting(routeInput,[candidate({agent_id:'cursor',availability:'quota_limited'}),a],1000).selectedAgent,'claude');});
test('cost preference changes only an eligible tie; privacy still wins',()=>{const a=candidate({agent_id:'claude',observed_latency_ms:10,observed_failure_rate:0}),b=candidate({agent_id:'host',runtime_id:'native',locality:'local',isolation_verified:true,cost_class:'local',observed_latency_ms:10,observed_failure_rate:0});assert.equal(evaluateRouting(routeInput,[a,b],1000).selectedAgent,'claude');assert.equal(evaluateRouting({...routeInput,preferences:{'infrastructure.cost_preference':'early_stage_cost_efficient'}},[a,b],1000).selectedAgent,'host');assert.equal(evaluateRouting({...routeInput,privacy:'restricted_security'},[a,b],1000).selectedAgent,'host');});
test('migration inventory is unchanged and repeat migration is inert',t=>{const {s,db}=fixture(t);const before=inventory(db);assert.equal(migrateLegacy(s).migrated,true);assert.deepEqual(inventory(db),before);assert.equal(migrateLegacy(s).migrated,false);assert.equal(s.integrity().ok,true);});
test('raw JSON boundary rejects duplicate escaped keys before canonicalization',()=>{const {parseAuthorityJSON:p}=require('../src/authority-json');for(const s of ['{"a":1,"a":2}','{"a":1,"\\u0061":2}','{"x":[{"a":1,"a":2}]}','{"n":1e400}'])assert.throws(()=>p(s));assert.deepEqual(p('{"a":[{"a":1},true,null,"a: b"]}'),{a:[{a:1},true,null,'a: b']});});
test('evidence is durable and acceptance/state cannot be forged',t=>{const f=accepted(t);assert(f.db.prepare('SELECT count(*) n FROM authority_evidence_records').get().n>0);assert.throws(()=>f.db.prepare("UPDATE authority_verification_records SET status='passed'").run());assert.throws(()=>f.s.setState(f.mission.id,'completed'));assert.throws(()=>f.s.verifyResult({mission_id:f.mission.id,mission_revision:1,result_id:f.result.id,status:'passed',verifier_id:'x',criteria:[{criterion_id:'forged',evidence_refs:['not-observed']}],evidence:[{observed:true}]}));f.db.prepare("UPDATE authority_missions SET current_state='completed'").run();assert.throws(()=>f.s.getCurrentMissionProjection(f.mission.id),/PROJECTION/);});
test('rejecting a conflict unlocks only its domain; scoped preference overrides global',t=>{const {s,m}=fixture(t),p=s.createProject({name:'Scoped'});const source={kind:'project_operational',operator_id:s.operatorId,project_id:p.id,scope:'project_specific',subject_key:'forecast.mode',source_hash:canonicalHash('x'),source_refs:[]};const a=m.propose({...source,value:'off'},s.operator);m.promote(a.id,{source_type:'operator_decision',domains:['forecast']},s.operator);const b=m.propose({...source,value:'on'},s.operator);m.promote(b.id,{source_type:'operator_decision',domains:['forecast']},s.operator);assert.equal(m.build({operator_id:s.operatorId,project_id:p.id,domains:['forecast']}).state,'WAIT');m.reject(b.id,s.operator);assert.equal(m.build({operator_id:s.operatorId,project_id:p.id,domains:['forecast']}).state,'ready');const global=m.ingest(observation(),s.operator),local=m.ingest(observation({chunk_id:'scoped',project_id:p.id,scope:'project_specific'}),s.operator);m.promote(global.id,{},s.operator);const scoped=m.promote(local.id,{},s.operator);assert.deepEqual(m.build({...input(s),project_id:p.id}).items.filter(x=>x.subject_key==='workflow.micro_prompts').map(x=>x.memory_id),[scoped.id]);});
test('runtime health, capability and privacy cannot be asserted through memory',t=>{const {s,m}=fixture(t);for(const field of ['allowed_agents','allowed_providers','execution_grant','approval','acceptance','health','sandbox','scope'])assert.throws(()=>m.ingest(observation({[field]:'allow'}),s.operator));for(const type of ['agent','provider']){const c=m.propose({kind:'personal_preference',operator_id:s.operatorId,scope:'global',subject_key:'workflow.micro_prompts',value:'forbidden',source_hash:canonicalHash('spoof'),source_refs:[]},{type,id:'untrusted'});assert.throws(()=>m.promote(c.id,{}, {type,id:'untrusted'}));}assert.equal(m.build(input(s)).state,'WAIT');const c=candidate();for(const change of [{availability:'unavailable'},{availability:'busy'},{observed_at:-100000},{circuit_state:'open'},{auth_state:'auth_required'},{quota_state:'quota_limited'}])assert.equal(evaluateRouting(routeInput,[{...c,...change}],1000).state,'WAIT');assert.equal(evaluateRouting({...routeInput,allow_handoff:true},[candidate({agent_id:'codex',availability:'handoff_only'}),candidate({availability:'unavailable'})],1000).selectedAgent,'codex');assert.equal(evaluateRouting(routeInput,[candidate({agent_id:'codex',availability:'handoff_only'}),c],1000).selectedAgent,'claude');});
test('nonce consumption survives process/database reopen and a second connection cannot replay',t=>{const fs=require('node:fs'),path=require('node:path'),dir=fs.mkdtempSync('/private/tmp/authority-nonce-'),file=path.join(dir,'memory.sqlite');t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));let db=new DatabaseSync(file),s=new AuthorityStore(db,{now:()=>1000});const m=s.createMission({envelope:{objective:'nonce fixture'}}),r=s.startRun({mission_id:m.id,mission_revision:1,agent_id:'host'}),g=s.issueGrant({mission_id:m.id,mission_revision:1,run_id:r.id,policy_version:'fixture',expires_at:2000,signature_reference:'broker:fixture',capabilities:[{capability:'read',scope:{path:'fixture.txt'}}]}),n={grant_id:g.id,run_id:r.id,nonce:'once',request_hash:canonicalHash('read')};s.consumeNonce(n);db.close();db=new DatabaseSync(file);s=new AuthorityStore(db,{now:()=>1000});const other=new DatabaseSync(file),s2=new AuthorityStore(other,{now:()=>1000});assert.throws(()=>s2.consumeNonce(n));assert.equal(s.integrity().ok,true);other.close();db.close();});
test('failed legacy import rolls back records and succeeds on a clean replay',t=>{const {s,db}=fixture(t);db.exec('CREATE TABLE projects(project_id TEXT PRIMARY KEY,name TEXT,status TEXT,created_at INTEGER,updated_at INTEGER); CREATE TABLE cp_missions(id TEXT,project_id TEXT,goal_id TEXT,task_id TEXT,owner TEXT,revision INTEGER,state TEXT,acceptance_strength TEXT,created_at INTEGER,updated_at INTEGER,envelope TEXT);');db.prepare('INSERT INTO projects VALUES(?,?,?,?,?)').run('p','legacy','active',1,1);db.prepare('INSERT INTO cp_missions VALUES(?,?,?,?,?,?,?,?,?,?,?)').run('m','missing',null,null,'operator',9,'awaiting_acceptance','criteria',1,1,JSON.stringify({objective:'historical',criteria:[]}));const before=inventory(db);assert.throws(()=>migrateLegacy(s));assert.deepEqual(inventory(db),before);assert.equal(db.prepare('SELECT count(*) n FROM authority_legacy_records').get().n,0);db.prepare("UPDATE cp_missions SET project_id='p'").run();assert.equal(migrateLegacy(s).migrated,true);assert.equal(s.getCurrentMissionProjection('m').current_revision,9);assert.equal(migrateLegacy(s).migrated,false);assert.equal(s.integrity().ok,true);});
test('grant revocation and ledger tail removal fail closed',t=>{const f=accepted(t),g=f.s.issueGrant({mission_id:f.mission.id,mission_revision:1,run_id:f.run.id,policy_version:'fixture',expires_at:2000,signature_reference:'broker:fixture',capabilities:[{capability:'read',scope:{path:'fixture'}}]});f.s.revokeGrant(g.id,'operator stop');assert.throws(()=>f.s.consumeNonce({grant_id:g.id,run_id:f.run.id,nonce:'new',request_hash:canonicalHash('request')}));assert.equal(f.s.integrity().ok,true);f.db.exec('DROP TRIGGER authority_ledger_entries_delete');f.db.prepare('DELETE FROM authority_ledger_entries WHERE entry_id=(SELECT entry_id FROM authority_ledger_entries ORDER BY rowid DESC LIMIT 1)').run();assert.equal(f.s.integrity().ok,false);});

test('typed Git revision digits never masquerade as card text; secret content stays denied', t => {
 const { s } = fixture(t), { safe } = require('../src/authority-store');
 const head = 'a4111111111111111' + 'b'.repeat(23);
 assert.equal(require('../src/personal-memory').containsSecret(head), true);
 for (const revision of [head, head + 'c'.repeat(24)]) {
  const envelope = { objective: 'Typed repository coordinate', verification_manifest: { version: 2, repository: { head: revision } } };
  const mission = s.createMission({ envelope });
  assert.equal(s.getMissionRevision(mission.id, 1).envelope.verification_manifest.repository.head, revision);
 }
 for (const value of [
  { envelope: { objective: head } },
  { envelope: { repository: { head } } },
  { envelope: { verification_manifest: { repository: { description: head } } } },
  { envelope: { verification_manifest: { repository: { head: '4111111111111111' } } } },
  { envelope: { verification_manifest: { repository: [{ head }] } } },
  { envelope: { verification_manifest: { repository: { head } }, objective: 'sk-fixtureprivatecredential' } }
 ]) assert.throws(() => safe(value), /Sensitive authority data rejected/);
 assert.equal(s.integrity().ok, true);
});
