'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const {fixture}=require('./fixtures/mission-fixture.cjs'),ControlServer=require('../src/control-server');
const ORIGIN='https://research.example';
test('browser Control Center shows current consent, real progress and immediate revoke; APIs require operator auth',async t=>{
 const f=await fixture(t),b=f.bridge;let closed=false;
 b.options.researchMission={workspace:f.repo,synthetic:true,maxPages:1,maxActions:20,timeoutMs:30000,browserFactory:o=>({qualify:async()=>({available:true}),execute:async()=>({state:'navigated',authority:false}),permissions:()=>({mode:'authentication',origin:ORIGIN,methods:['GET','HEAD','POST'],expires_at:o.sessionAuthorization.permission_expires_at}),revokePermission:()=>{},close:async()=>{closed=true;return {closed:true,termination_verified:true,owned_process_termination:'verified'};}})};
 f.host.researchAssess=(task,input)=>b.missions.research.assess(task,input);f.host.researchExecute=(task,input,signal)=>b.missions.research.perform(task,input,signal);
 const r=b.missions.research.create({request_id:randomUUID(),objective:'Inspect explicitly authorized synthetic feature navigation.',entry_url:ORIGIN+'/',session_authorization:{mode:'dedicated_cdp',permission_mode:'authentication',confirmed:true}});b.missions.dispatch(r.mission_id,{request_id:randomUUID()});for(let n=0;n<150&&!b.missions.research.active.get(r.mission_id)?.waitingHandoff;n++)await new Promise(r=>setTimeout(r,10));
 const server=new ControlServer(b,{port:0});await server.start();t.after(()=>server.close());
 for(const route of ['/api/assistant/browser/options','/api/assistant/browser/sessions','/api/assistant/browser/diagnostics?mission_id='+r.mission_id,'/api/assistant/browser/status?mission_id='+r.mission_id,'/api/assistant/mission/web/status?mission_id='+r.mission_id])assert.equal((await fetch(server.origin+route)).status,401);
 const browser=await require('playwright-core').chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.name));await page.addInitScript(token=>sessionStorage.setItem('airodromToken',token),server.token);await page.goto(server.origin+'/');await page.getByText('Live · local',{exact:true}).waitFor();await page.getByRole('button',{name:'Missions',exact:true}).click();
 await page.getByText('Browser connection & consent',{exact:true}).first().waitFor();assert.match(await page.locator('body').innerText(),/authentication|POST/);assert.equal(await page.getByRole('button',{name:'Hand back for strict read-only inspection'}).count(),1);assert.doesNotMatch(await page.locator('body').innerText(),/\d+%|Bearer|token=|synthetic-private/);
 assert.equal(await page.getByRole('button',{name:'View sanitized browser diagnostics'}).count(),1);await page.getByRole('button',{name:'View sanitized browser diagnostics'}).click();await page.getByText('No retained browser denials.',{exact:true}).waitFor();
 await page.setViewportSize({width:320,height:780});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.getByRole('button',{name:'Revoke browser access and close'}).click();for(let n=0;n<150&&!closed;n++)await new Promise(r=>setTimeout(r,10));assert.equal(closed,true);assert.equal(b.missions.require(r.mission_id).state,'cancelled');assert.equal(errors.length,0);
 const response=await fetch(server.origin+'/api/assistant/browser/status?mission_id='+r.mission_id,{headers:{Authorization:'Bearer '+server.token}}),status=await response.json();assert.equal(status.state,'closed');assert.equal(status.termination_verified,true);
});
