'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {DatabaseSync}=require('node:sqlite');
const {PersonalMemory}=require('../src/personal-memory');
const {EventLedger}=require('../src/event-ledger');
const {ControlPlaneStore,transaction}=require('../src/control-plane-store');
const {ControlContext}=require('../src/control-context');
const {afterCommit}=require('../src/control-transaction');
function fixture(t){const db=new DatabaseSync(':memory:');t.after(()=>db.close());db.exec('CREATE TABLE project_missions(mission_id TEXT,status TEXT,updated_at INTEGER)');const ledger=new EventLedger(db),store=new ControlPlaneStore({db,ledger}),memory=new PersonalMemory({db,record:e=>ledger.record(e)}),task={id:'t1',sessionId:'s1',includeSharedMemory:false};store.registerMission({id:'m1',taskId:'t1',owner:'operator',envelope:{objective:'fixture'},ceiling:{}});const context=new ControlContext({personalMemory:memory,tasks:{get:()=>task}},store);return{db,store,memory,context,task,ledger};}
test('worker candidates cannot promote; operator promotion preserves provenance and forget removes content',t=>{const f=fixture(t);const c=f.context.propose('m1',null,{subject:'fixture fact',content:'fixture observation'});assert.equal(f.memory.recent({}).items.length,0);assert.throws(()=>f.context.review(c.id,{decision:'promote',reviewer:'worker'}),/Operator/);const result=f.context.review(c.id,{decision:'promote'});assert.equal(f.memory.get(result.memory_id).source,'user_explicit');f.memory.forget(result.memory_id);assert.equal(f.memory.get(result.memory_id),null);assert.equal(JSON.parse(f.db.prepare('SELECT record FROM cp_candidates WHERE id=?').get(c.id).record).content,undefined);});
test('context selection honors opt-in, sensitivity, supersession, forget, and reference-only storage',t=>{const f=fixture(t);const input={domain:'session',taskId:'t1',type:'fact',subject:'fixture',content:'fixture preferred result',source:'user_explicit'};const old=f.memory.remember(input);const current=f.memory.update(old.memoryId,{content:'fixture current result'});f.memory.remember({...input,taskId:'other'});f.memory.remember({...input,subject:'fixture sensitive',sensitivity:'sensitive'});f.memory.remember({domain:'personal',type:'fact',subject:'fixture',content:'fixture personal data',source:'user_explicit'});const pack=f.context.build(f.store.getMission('m1'));assert.deepEqual(pack.refs.map(x=>x.memory_id),[current.memoryId]);assert.equal(pack.selection.authority,false);assert.ok(pack.selection.bytes<=8000);const persisted=f.db.prepare('SELECT * FROM cp_context_packs WHERE id=?').get(pack.id);assert.ok(!JSON.stringify(persisted).includes('current result'));f.memory.forget(current.memoryId);assert.equal(f.context.build(f.store.getMission('m1')).refs.length,0);});
test('nested transactions defer observers until commit and discard on rollback',t=>{const f=fixture(t);let observed=0;assert.throws(()=>transaction(f.db,()=>{transaction(f.db,()=>afterCommit(f.db,()=>observed++));throw Error('rollback');}),/rollback/);assert.equal(observed,0);transaction(f.db,()=>{transaction(f.db,()=>afterCommit(f.db,()=>observed++));assert.equal(observed,0);});assert.equal(observed,1);});
test('settlement is durable during ledger outage and its audit is delivered after recovery',t=>{const f=fixture(t);f.store.startRun({id:'r1',taskId:'t1'});f.ledger.markDegraded(new Error('fixture outage'));f.store.updateRun('r1',{state:'completed',processState:'exited',verified:true,deferAudit:true});assert.equal(f.store.run('r1').state,'completed');assert.equal(f.db.prepare('SELECT count(*) n FROM cp_pending_events').get().n,1);f.ledger.degraded=null;f.store.flushPendingEvents();assert.equal(f.db.prepare('SELECT count(*) n FROM cp_pending_events').get().n,0);assert.equal(f.ledger.list({runId:'r1'}).events.at(-1).event_type,'run.completed');});
