'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {DatabaseSync}=require('node:sqlite');
const {EventLedger}=require('../src/event-ledger');
const {ControlPlaneStore,transaction}=require('../src/control-plane-store');
function fixture(t){const root=fs.mkdtempSync('/private/tmp/cpv2-'),db=new DatabaseSync(path.join(root,'state.sqlite'));db.exec('CREATE TABLE project_missions(mission_id TEXT PRIMARY KEY,status TEXT,updated_at INTEGER)');const ledger=new EventLedger(db),store=new ControlPlaneStore({db,ledger});t.after(()=>{db.close();fs.rmSync(root,{recursive:true,force:true});});store.registerMission({id:'mission1',taskId:'task1',owner:'mcp',envelope:{objective:'fixture'},ceiling:{scopes:['repo']}});return{root,db,ledger,store};}
test('control migration preserves ledger identity and reopens idempotently',t=>{const{db,ledger,store}=fixture(t);const e=ledger.record({eventType:'fixture.event',agent:'bridge',direction:'internal'});new ControlPlaneStore({db,ledger});assert.equal(ledger.get(e.event_id).sequence,e.sequence);assert.throws(()=>db.prepare('DELETE FROM event_ledger_events').run(),/Append-only/);assert.throws(()=>db.prepare('UPDATE cp_grants SET ceiling=?').run('{}'),/Immutable/);assert.equal(store.listMissions().length,1);});
test('state, ledger and follow-up intent roll back together',t=>{const{db,ledger,store}=fixture(t);const before=ledger.list().events.length;assert.throws(()=>transaction(db,()=>{store.state('mission1','running');throw Error('rollback');}),/rollback/);assert.equal(store.getMission('mission1').state,'ready');assert.equal(ledger.list().events.length,before);});
test('decision first answer wins and survives restart with one continuation',t=>{const{db,store}=fixture(t);const d=store.createDecision('mission1',{question:'Choose',options:[{id:'A',label:'A'},{id:'B',label:'B'}]});assert.equal(store.answerDecision(d.id,{option_id:'B',actor:'user',surface:'operator'}).answer.option_id,'B');assert.equal(store.answerDecision(d.id,{option_id:'A',actor:'mcp',surface:'mcp'}).answer.option_id,'B');store.recover();assert.equal(db.prepare('SELECT count(*) n FROM cp_continuations').get().n,1);assert.equal(store.decision(d.id).state,'answered');});
test('writer lifetime and terminal process invariants fail closed',t=>{const{root,store}=fixture(t);store.startRun({id:'run1',taskId:'task1',missionId:'mission1'});store.acquireLease({resource:root,runId:'run1',missionId:'mission1'});assert.throws(()=>store.acquireLease({resource:root,runId:'run2'}),/writer lease/);assert.throws(()=>store.updateRun('run1',{state:'completed',processState:'alive'}),/alive/);store.recover();assert.equal(store.run('run1').process_state,'unknown');assert.throws(()=>store.acquireLease({resource:root,runId:'run2'}),/writer lease/);});
test('durable direct result replay never dispatches uncertain work',t=>{const{store}=fixture(t);store.beginInvocation('task1','request1','hash1');store.finishInvocation('request1',{status:'completed',result:{value:42}});store.beginInvocation('task1','request2','hash2');store.recover();assert.equal(store.invocation('request1').result.result.value,42);assert.equal(store.invocation('request2').state,'unknown');assert.throws(()=>store.beginInvocation('task2','request1','hash1'),/conflict/);});
test('unsupported future schema is rejected without mutation',t=>{const{db,ledger}=fixture(t);db.prepare('UPDATE control_plane_meta SET version=999').run();assert.throws(()=>new ControlPlaneStore({db,ledger}),/Unsupported/);assert.equal(db.prepare('SELECT version FROM control_plane_meta').get().version,999);});
test('migration failure rolls back all new schema objects and preserves historical ledger',t=>{const db=new DatabaseSync(':memory:');t.after(()=>db.close());const ledger=new EventLedger(db);const event=ledger.record({eventType:'fixture.old',agent:'bridge',direction:'internal'});const original=db.exec.bind(db);db.exec=sql=>original(sql.includes('CREATE TABLE cp_runs')?sql.replace('CREATE TABLE cp_runs','INVALID SQL cp_runs'):sql);assert.throws(()=>new ControlPlaneStore({db,ledger}));db.exec=original;assert.equal(db.prepare("SELECT count(*) n FROM sqlite_master WHERE name LIKE 'cp_%' OR name='control_plane_meta'").get().n,0);assert.equal(ledger.get(event.event_id).sequence,event.sequence);new ControlPlaneStore({db,ledger});});
