'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events'),{PassThrough}=require('node:stream'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {acpProbe,environment,errorClass,qualificationObservation,cursorRuntimeStatus}=require('../src/cursor-runtime');
function fake(reply,{silent=false}={}){let args,opts,request;const child=new EventEmitter();child.stdout=new PassThrough();child.stderr=new PassThrough();child.stdin=new PassThrough();child.kill=()=>{child.emit('close',0);return true;};child.stdin.on('data',b=>{request=JSON.parse(b.toString());if(!silent)queueMicrotask(()=>child.stdout.write(JSON.stringify(reply)+'\n'));});return{spawn:(p,a,o)=>{args=a;opts=o;return child;},get args(){return args},get opts(){return opts},get request(){return request}};}
test('ACP probe only initializes, never authenticates, prompts, starts MCP or grants tools',async()=>{const f=fake({id:1,result:{protocolVersion:1,agentCapabilities:{loadSession:true},authMethods:[{id:'cursor_login'}]}});const r=await acpProbe('/fixture/agent',{spawnImpl:f.spawn,timeout:100});assert.equal(r.reachable,true);assert.equal(r.load_session,true);assert.deepEqual(f.args,['acp']);assert.equal(f.request.method,'initialize');assert.deepEqual(f.request.params.clientCapabilities,{fs:{readTextFile:false,writeTextFile:false},terminal:false});assert.equal(f.opts.env.CURSOR_API_KEY,undefined);assert.equal(f.opts.env.ANTHROPIC_API_KEY,undefined);});
test('malformed or wrong ACP version cannot claim reachability',async()=>{for(const reply of [{id:1,error:{message:'CURSOR_AUTH_TOKEN=seededSecret'}},{id:1,result:{protocolVersion:999}}]){const f=fake(reply);const r=await acpProbe('/fixture/agent',{spawnImpl:f.spawn,timeout:100});assert.equal(r.reachable,false);assert.ok(!JSON.stringify(r).includes('seededSecret'));}});
test('silent ACP times out and closes without inferring vendor availability',async()=>{const f=fake(null,{silent:true});assert.deepEqual(await acpProbe('/fixture/agent',{spawnImpl:f.spawn,timeout:20}),{reachable:false});});
test('minimal environment drops credential keys and malformed values',()=>{const e=environment({HOME:'/fixture',PATH:'/usr/bin',CURSOR_API_KEY:'seed',CURSOR_AUTH_TOKEN:'seed',ANTHROPIC_API_KEY:'seed',SECRET:'seed',LANG:'bad\0value'});assert.deepEqual(e,{HOME:'/fixture',PATH:'/usr/bin'});});
test('auth/quota failure classifier never exports raw diagnostics',()=>{assert.equal(errorClass('Credit usage limit reached for account private@example.invalid'),'quota_limited');assert.equal(errorClass('Not authenticated token secret'),'auth_required');assert.equal(errorClass('unexpected output private@example.invalid'),'runtime_unavailable');});
test('qualification snapshots can only deny; stale, different version or spoofed available is ignored',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cursor-profile-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const file=path.join(dir,'qualification.json'),now=100000000;const write=(extra={})=>fs.writeFileSync(file,JSON.stringify({cursor:{runtime_version:'1.0',observed_at:now,availability:'quota_limited',...extra}}));write();assert.equal(qualificationObservation('1.0',{file,now}).availability,'quota_limited');for(const extra of [{availability:'available'},{runtime_version:'spoofed'},{observed_at:now-86400001},{observed_at:now+1}]){write(extra);assert.equal(qualificationObservation('1.0',{file,now}),null);}});
test('test fixtures never spawn installed real Cursor',async()=>{const r=await cursorRuntimeStatus({fixture:true});assert.equal(r.installed,false);assert.equal(r.availability,'unavailable');assert.equal(r.acp_reachable,false);});
