'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {fixture}=require('./fixtures/mission-fixture.cjs');
const {publish}=require('../scripts/publish-agent-result.cjs');
test('Codex handoff is durable before execution, truthfully unavailable, leased, zero inference; local publication dedups and independent verification does not accept',async t=>{
 const f=await fixture(t),m=f.create({preferred_agent:'codex'}),a=f.bridge.codexAdapter;
 assert.equal(a.health().available,false);assert.equal(a.health().hard_cancel,false);
 const h=a.startTask(m.id,'codex-fixture');assert.equal(a.startTask(m.id,'codex-fixture').duplicate,true);assert.equal(f.bridge.controlStore.run(h.run_id).agent_id,'codex');assert.equal(f.inference(),0);
 assert.throws(()=>a.startTask(m.id,'second'),/Unreconciled/);assert.throws(()=>f.bridge.controlStore.acquireLease({resource:f.repo,runId:'other'}),/writer lease/);
 fs.writeFileSync(path.join(f.repo,'fixture.txt'),'beta\n');const input={schema_version:'codex-result-v1',transport:'handoff',relay_nonce:h.contract.relay_nonce,timestamps:{started_at:1,finished_at:2},publisher:{identity:'codex-work',mode:'artifact'},mission_id:m.id,task_id:m.task_id,run_id:h.run_id,request_id:'codex-fixture',agent_id:'codex',result:{status:'completed',summary:'Fixture updated',changed_files:['fixture.txt'],tests:[],artifacts:[],limitations:[]}};input.content_hash=require('../src/control-plane-store').fingerprint(input);const file=path.join(f.root,'result.json');fs.writeFileSync(file,JSON.stringify(input));const runtime=path.join(f.root,'data');assert.equal(publish(file,{runtime}).published,true);assert.equal(publish(file,{runtime}).duplicate,true);assert.equal(f.bridge.controlStore.run(h.run_id).termination_verified,0);
 const conflict={...input,result:{...input.result,summary:'Conflict'}};delete conflict.content_hash;conflict.content_hash=require('../src/control-plane-store').fingerprint(conflict);fs.writeFileSync(file,JSON.stringify(conflict));assert.throws(()=>publish(file,{runtime}),/conflict/);
 a.reconcile({run_id:h.run_id,termination_verified:true});f.bridge.missions.schedule();const done=await f.settle(m.id);assert.equal(done.state,'awaiting_acceptance');assert.equal(done.acceptance.length,0);const inbox=f.bridge.resultInbox.list({agent:'codex'});assert.equal(inbox.length,1);assert.equal(inbox[0].state,'unread');assert.equal(inbox[0].result.accepted,false);f.bridge.resultInbox.review(h.run_id,'read');f.bridge.resultInbox.review(h.run_id,'reviewed');assert.equal(f.bridge.resultInbox.list()[0].state,'reviewed');assert.equal(f.inference(),0);await f.bridge.controlStore.outbox.dispatch();assert.equal(f.bridge.memory.db.prepare('SELECT count(*) n FROM cp_result_receipts').get().n,1);
});
test('cancellation never claims hard termination or releases writer lease; restart never dispatches Codex again',async t=>{const f=await fixture(t),m=f.create(),h=f.bridge.codexAdapter.startTask(m.id,'cancel-handoff');const c=f.bridge.codexAdapter.cancelTask(h.run_id);assert.equal(c.termination_verified,false);assert.equal(f.bridge.controlStore.run(h.run_id).state,'termination_unverified');assert.throws(()=>f.bridge.controlStore.acquireLease({resource:f.repo,runId:'other'}),/writer/);await f.reopen();assert.equal(f.bridge.codexAdapter.getTask(h.run_id).state,'cancellation_requested');assert.equal(f.bridge.controlStore.run(h.run_id).state,'interrupted');assert.throws(()=>f.bridge.codexAdapter.startTask(m.id,'again'),/Unreconciled|cannot hand off/);assert.equal(f.calls(),0);assert.equal(f.inference(),0);});
test('Claude results relay into the same durable inbox with completion distinct from acceptance',async t=>{const f=await fixture(t),m=f.create();f.bridge.missions.dispatch(m.id,{request_id:'claude-relay'});await f.settle(m.id);const r=f.bridge.resultInbox.list({agent:'claude_code'})[0];assert.equal(r.state,'unread');assert.equal(r.result.accepted,false);assert.equal(f.bridge.resultInbox.publish({run_id:r.run_id,mission_id:r.mission_id,task_id:r.task_id,agent_id:r.agent_id,request_id:r.request_id,result:{...JSON.parse(f.bridge.memory.db.prepare('SELECT normalized FROM cp_run_results WHERE run_id=?').get(r.run_id).normalized)}}).duplicate,true);});
test('unavailable Codex uses only declared compatible fallback; no scope broadening or result correlation mismatch',async t=>{const f=await fixture(t),m=f.create({preferred_agent:'codex',fallback_agents:['claude_code']});const observations=await f.bridge.missions.agents.refresh();assert.equal(observations.codex.reason,'native_dispatch_unavailable');const route=await f.bridge.missions.agents.select(m.envelope);assert.equal(route.selected,'claude_code');assert.equal(route.skipped[0].agent,'codex');const h=f.bridge.codexAdapter.startTask(m.id,'correlation-test');assert.throws(()=>f.bridge.resultInbox.publish({run_id:h.run_id,mission_id:m.id,task_id:'wrong',agent_id:'codex',request_id:'wrong',result:{status:'completed',summary:'Claim'}}),/correlation/);assert.throws(()=>f.bridge.codexAdapter.reconcile({run_id:h.run_id,termination_verified:false,result:{status:'completed',summary:'Claim'}}),/termination/);assert.equal(f.inference(),0);});
