'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{DatabaseSync}=require('node:sqlite');
const {ControlPlaneStore}=require('../src/control-plane-store'),{EventLedger}=require('../src/event-ledger'),{transaction}=require('../src/control-transaction');
function fixture(t){const db=new DatabaseSync(':memory:');t.after(()=>db.close());const store=new ControlPlaneStore({db,ledger:new EventLedger(db),now:()=>10000});return{db,store,out:store.outbox};}
const intent={key:'fixture:1',destination:'fixture',ref:'local',eventType:'fixture.result',payload:{answer:42}};
test('outbox state and intent roll back together; dispatch only after commit and enqueue dedup rejects conflict',async t=>{const f=fixture(t);let calls=0;f.out.register('fixture',()=>{calls++;return{receipt:'ok'};},{idempotent:true});assert.throws(()=>transaction(f.db,()=>{f.out.enqueue(intent);f.out.dispatch();throw Error('rollback');}));assert.equal(calls,0);assert.equal(f.db.prepare('SELECT count(*) n FROM cp_effect_outbox').get().n,0);const a=f.out.enqueue(intent);assert.equal(f.out.enqueue(intent),a);assert.throws(()=>f.out.enqueue({...intent,payload:{answer:3}}),/conflict/);await Promise.all([f.out.dispatch(),f.out.dispatch()]);await f.out.dispatch();assert.equal(calls,1);assert.equal(f.out.health().counts.sent,1);});
test('bounded transient retry and permanent dead letter use safe error classes',async t=>{const f=fixture(t);f.out.maxAttempts=2;f.out.register('fixture',()=>{throw Error('private raw output');},{idempotent:true});f.out.enqueue(intent);await f.out.dispatch();assert.equal(f.out.health().counts.failed,1);f.db.prepare('UPDATE cp_effect_outbox SET next_at=0').run();await f.out.dispatch();assert.equal(f.out.health().counts.dead_letter,1);assert.ok(!JSON.stringify(f.db.prepare('SELECT * FROM cp_effect_outbox').all()).includes('private raw'));f.out.enqueue({...intent,key:'fixture:auth'});f.out.register('fixture',()=>{throw Object.assign(Error('secret'),{failureClass:'auth'});});await f.out.dispatch();assert.equal(f.out.health().counts.dead_letter,2);});
test('restart retries only idempotent claims, preserves ambiguous deliveries, never resends sent and redacts payload',async t=>{const f=fixture(t);f.out.register('fixture',()=>({ok:true}),{idempotent:true});f.out.enqueue({...intent,payload:{token:'private',summary:'Bearer abcdefghijklmnopqrstuvwxyz'}});f.db.prepare("UPDATE cp_effect_outbox SET status='dispatching'").run();f.out.recover();assert.equal(f.out.health().counts.pending,1);await f.out.dispatch();f.out.recover();await f.out.dispatch();assert.equal(f.out.health().counts.sent,1);f.out.enqueue({...intent,key:'unknown',destination:'slack_message'});f.db.prepare("UPDATE cp_effect_outbox SET status='dispatching' WHERE event_key='unknown'").run();f.out.recover();assert.equal(f.out.health().counts.delivery_unknown,1);assert.ok(!f.db.prepare('SELECT payload FROM cp_effect_outbox WHERE event_key=?').get(intent.key).payload.includes('private'));assert.equal(f.db.prepare('PRAGMA integrity_check').get().integrity_check,'ok');});
test('opaque UUID destination refs do not trigger payment-card text heuristics',t=>{const f=fixture(t);assert.ok(f.out.enqueue({...intent,key:'uuid-ref',ref:'12345678-1234-1234-1234-123456789012'}));assert.throws(()=>f.out.enqueue({...intent,key:'secret-ref',ref:'crsr_abcdefghijklmnopqrstuv'}),/Sensitive/);});
test('unregistered future destinations cannot starve supported local deliveries',async t=>{const f=fixture(t);for(let n=0;n<60;n++)f.out.enqueue({...intent,key:`future:${n}`,destination:'future'});let calls=0;f.out.register('fixture',()=>{calls++;return{ok:true};},{idempotent:true});f.out.enqueue(intent);await f.out.dispatch();assert.equal(calls,1);assert.equal(f.out.health().counts.pending,60);});
test('stale dispatcher selection cannot bypass a newly deferred retry',async t=>{
 const f=fixture(t);let calls=0;
 f.out.register('fixture',row=>{calls++;if(row.event_key==='fixture:1')f.db.prepare('UPDATE cp_effect_outbox SET next_at=50000 WHERE event_key=?').run('fixture:2');return{receipt:'local'};},{idempotent:true});
 f.out.enqueue(intent);f.out.enqueue({...intent,key:'fixture:2'});await f.out.dispatch();
 assert.equal(calls,1);assert.equal(f.db.prepare('SELECT attempts FROM cp_effect_outbox WHERE event_key=?').get('fixture:2').attempts,0);
});
test('non-idempotent receipt audit rollback is unresolved and never retried',async t=>{
 const f=fixture(t);let calls=0;f.out.register('fixture',()=>{calls++;return{remote_receipt:'observed'};});f.out.enqueue(intent);
 const audit=f.out.audit;f.out.audit=function(kind,...args){if(kind==='sent')throw Error('Injected post-send audit rollback');return audit.call(this,kind,...args);};
 await f.out.dispatch();await f.out.dispatch();assert.equal(calls,1);assert.equal(f.out.health().counts.delivery_unknown,1);assert.equal(f.db.prepare('SELECT sent_at FROM cp_effect_outbox').get().sent_at,null);
});
