'use strict';
process.env.NODE_ENV='test';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{randomUUID}=require('node:crypto');
const worker=require('../src/bounded-worker'),router=require('../src/model-worker-router'),handoff=require('../src/mission-handoff');
const {fixture}=require('./fixtures/mission-fixture.cjs'),synthetic=require('./fixtures/bounded-worker-fixture.cjs');
const root=t=>{const r=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'worker-test-')));t.after(()=>fs.rmSync(r,{recursive:true,force:true}));return r;};
const grant=repo=>({level:'development',permissions:{network:['internet']},filesystem:{read:[repo],write:[repo]},expiresAt:Date.now()+600000});
const policy=id=>({privacy:'cloud_allowed',providers:[worker.SPECS[id].provider],billing_classes:['subscription'],max_attempts:1});
async function setup(t,id='codex',mode='valid'){const opts=synthetic.options(root(t),id,mode),f=await fixture(t,{workers:{[id]:opts}});f.bridge.missionAuthority.initializeOperatorKey();const consent={confirmed:true,model:'fixture-model',request_id:randomUUID()};await f.bridge.workers.qualify(id,consent);return {...f,id,consent,opts,create:(extra={})=>f.create({preferred_agent:id,model:id+':fixture-model',dispatch_policy:policy(id),authority:grant(f.repo),...extra})};}
const result={status:'completed',summary:'Synthetic proposal',changes:[{path:'fixture.txt',content:'beta\n'}]};
const valid=()=>[{type:'thread.started',thread_id:'fixture-session'},{type:'item.completed',item:{type:'agent_message',text:JSON.stringify(result)}},{type:'turn.completed',usage:{input_tokens:7,output_tokens:5}}];
const stream=a=>a.map(e=>JSON.stringify(e)).join('\n');
for(const type of ['item.started','item.updated','item.completed'])test('reject every Codex tool event '+type,()=>assert.throws(()=>worker.parse('codex',stream([{type,item:{type:'command_execution'}},...valid()]),['fixture.txt']),/worker_tool_use_denied/));
test('unknown events, hooks, result authority and sensitive output are denied',()=>{for(const events of [[{type:'unknown'},...valid()],[{type:'system',subtype:'hook_started'}],[{type:'system',subtype:'init',tools:['Read']}],[{type:'assistant',message:{content:[{type:'tool_use'}]}}]])assert.throws(()=>worker.parse(events[0].type==='unknown'?'codex':'claude_code',stream(events),['fixture.txt']));const bad=valid();bad[1].item.text=JSON.stringify({...result,accepted:true});assert.throws(()=>worker.parse('codex',stream(bad),['fixture.txt']));assert.throws(()=>worker.safe('My password is synthetic-credential'));});
test('discovery does not execute installed candidates or infer a version',t=>{const r=root(t),file=path.join(r,'no-exec');fs.writeFileSync(file,'#!/bin/sh\ntouch '+path.join(r,'executed')+'\n',{mode:0o700});const o=worker.inspect('codex',{executable:file});assert.equal(o.installed,true);assert.equal(o.version,null);assert.equal(o.authenticated,false);assert.equal(fs.existsSync(path.join(r,'executed')),false);});
for(const id of ['codex','claude_code'])test('public synthetic '+id+' proposes without credentials, Memory or direct writes',async t=>{const f=await setup(t,id),b=f.bridge;const m=f.create();b.missions.dispatch(m.id,{request_id:randomUUID()});const done=await f.settle(m.id);assert.equal(fs.readFileSync(path.join(f.repo,'fixture.txt'),'utf8'),'beta\n');assert.equal(done.verifications[0].result,'passed');assert.equal(done.acceptance.length,0);const run=done.runs[0];assert.equal(run.agent_id,id);assert.equal(run.result.worker_provenance.tool_access,false);assert.equal(run.result.worker_provenance.context_items,0);assert.equal(run.result.worker_provenance.synthetic_only,true);assert.equal(b.controlContext.inspect(b.tasks.get(m.task_id).contextPackId).refs.length,0);b.workers.assertEvidence(run);});
test('same-version binary replacement cannot execute after binding',async t=>{const f=await setup(t),m=f.create();fs.appendFileSync(f.opts.executable,'\n// changed');assert.throws(()=>f.bridge.workers.assertMission(f.bridge.missions.require(m.id)),/qualification/);const a=f.bridge.workers.get('codex');await assert.rejects(a.execute({workspace:f.repo,files:['fixture.txt'],writable:['fixture.txt'],objective:'Synthetic change',model:'fixture-model',expectedPin:{sha256:'0'.repeat(64),version:'fixture-v2',policy:worker.POLICY}}),/worker_qualified_pin_changed/);assert.equal(fs.readFileSync(path.join(f.repo,'fixture.txt'),'utf8'),'alpha\n');});
test('consent, missing/offline/expired/overlong authority and model drift deny before apply',async t=>{const f=await setup(t);await assert.rejects(f.bridge.workers.qualify('claude_code',{confirmed:false,model:'fixture-model',request_id:randomUUID()}),/consent/);for(const authority of [undefined,{...grant(f.repo),permissions:{network:['localhost']}},{...grant(f.repo),expiresAt:Date.now()-1},{...grant(f.repo),expiresAt:Date.now()+3600000}])assert.throws(()=>f.create({authority}));assert.throws(()=>f.create({model:'unqualified-model'}));const o=synthetic.options(f.root,'claude_code','drift'),a=new worker.BoundedWorker('claude_code',f.bridge,o);await assert.rejects(a.execute({workspace:f.repo,files:['fixture.txt'],writable:['fixture.txt'],objective:'Synthetic',model:'fixture-model'}),/worker_model_drift/);});
test('expiry, revocation, seal tamper and provenance drift stop application',async t=>{const f=await setup(t),b=f.bridge,m=f.create();b.workers.assertMission(b.missions.require(m.id));assert.throws(()=>b.workers.assertOutput(b.missions.require(m.id),{provenance:{}}),/provenance/);b.workers.revoke('codex');assert.throws(()=>b.missions.dispatch(m.id,{request_id:randomUUID()}),/qualification/);assert.equal(b.workers.current('codex').qualified,false);await b.workers.qualify('codex',{...f.consent,request_id:randomUUID()});b.controlStore.db.prepare("UPDATE cp_worker_qualifications SET seal='{}' WHERE state='qualified'").run();assert.equal(b.workers.current('codex').qualified,false);});
test('timeout and cancellation verify owned process termination',async t=>{const r=root(t),workspace=path.join(r,'repo');fs.mkdirSync(workspace);fs.writeFileSync(path.join(workspace,'fixture.txt'),'alpha\n');const a=new worker.BoundedWorker('codex',{options:{allowFixtureWorker:true}},synthetic.options(r,'codex','hang'));const request={workspace,files:['fixture.txt'],writable:['fixture.txt'],objective:'Synthetic',model:'fixture-model'};await assert.rejects(a.execute({...request,timeoutMs:30}),/worker_timeout/);const c=new AbortController();setTimeout(()=>c.abort(),30);await assert.rejects(a.execute({...request,signal:c.signal}),/worker_cancelled/);assert.equal(fs.readFileSync(path.join(workspace,'fixture.txt'),'utf8'),'alpha\n');});
test('external routing never follows local-only, private data, unknown cost/context or busy route',()=>{const m={id:'codex:fixture-model',locality:'external',workers:['codex'],qualification:'qualified',available:true,expires_at:Date.now()+10000,data_classes:['public'],tasks:['WORK'],cost:null,context_limit:null},w={id:'codex',locality:'external',qualification:'qualified',available:true,capabilities:['coding']},catalog={models:[m],workers:[w]},base={mission_class:'WORK',privacy:'approved_external',data_class:'public',worker:'codex'};assert.equal(router.select(catalog,base).state,'READY');for(const extra of [{privacy:'local_only'},{data_class:'personal'},{mission_class:'CONVERSATION'},{max_cost:1},{context_need:1},{writer_conflict:true},{worker:'cursor'},{required_capabilities:['browser']}])assert.equal(router.select(catalog,{...base,...extra}).state,'WAIT');w.available=false;assert.equal(router.select(catalog,base).state,'WAIT');});
test('V2 handoff is host-template, principal and durable idempotency bound',async t=>{const f=await setup(t),b=f.bridge;const template={privacy:'approved_external',data_class:'public',workers:['codex'],project_id:f.create().project_id};const source=b.controlStore.listMissions({limit:5})[0];Object.assign(template,{project_id:source.project_id,goal_id:source.goal_id,workspace:f.repo,allowed_files:['fixture.txt'],criteria:source.envelope.criteria,verification:source.envelope.verification,capability_scopes:['repo','developer_environment'],authority:grant(f.repo)});b.workers.registerTemplate({project:'fixture',workspace_alias:'public',template,confirmed:true});const packet={version:2,request_id:randomUUID(),objective:'Change public fixture.txt to beta',mission_class:'WORK',data_class:'public',privacy:'approved_external',project:'fixture',workspace:'public',worker:'codex',model:'codex:fixture-model'};const one=await handoff.submit(b,packet,'mcp:fixture-one');assert.ok(one.mission_id);await f.settle(one.mission_id);b.workers.revoke('codex');const two=await handoff.submit(b,packet,'mcp:fixture-one');assert.equal(two.mission_id,one.mission_id);assert.equal(two.duplicate,true);await assert.rejects(handoff.submit(b,packet,'mcp:fixture-two'));assert.throws(()=>handoff.status(b,one.mission_id,'mcp:fixture-two'));assert.throws(()=>handoff.validate({...packet,references:['private-memory-handle']}));assert.equal(handoff.status(b,one.mission_id,'mcp:fixture-one').untrusted,true);});
test('sandbox denies forks, arbitrary exec, direct internet and original workspace',t=>{if(process.platform!=='darwin')return t.skip('macOS containment');const r=root(t),executable=fs.realpathSync(process.execPath),p=(fs.mkdirSync(path.join(r,'state')),worker.sandbox(r,executable,'claude_code',34567));assert.doesNotMatch(p,/allow process-fork|allowFork/);assert.match(p,/localhost:34567/);assert.doesNotMatch(p,/allow network-outbound\)/);});
module.exports={grant};

test('canonical external context excludes private Memory and host web remains public-only',async t=>{const f=await setup(t),b=f.bridge;const a=require('./fixtures/opencode-fixture.cjs').qualifyCanonical(b);a.operatorMemory({domain:'personal',subject:'fixture.private',content:'private-memory-canary-not-for-vendors'});const m=f.create();const pack=b.controlContext.build(b.missions.require(m.id));assert.deepEqual(pack.refs,[]);assert.deepEqual(pack.reference_data,[]);assert.doesNotMatch(JSON.stringify(pack),/private-memory-canary/);const g=b.missions.web.configure(m.id,{request_id:randomUUID(),mode:'on',entries:['https://public.example/'],confirmed:true,duration_ms:10000});assert.equal(g.authority,false);assert.equal(b.missions.web.status(m.id).public_only,true);});
test('secret/private templates and credential-shaped model labels never persist',async t=>{const f=await setup(t),b=f.bridge,source=f.create(),m=b.missions.require(source.id);const template={privacy:'approved_external',data_class:'public',workers:['codex'],project_id:m.project_id,goal_id:m.goal_id,workspace:f.repo,allowed_files:['fixture.txt'],criteria:m.envelope.criteria,verification:m.envelope.verification,capability_scopes:['repo','developer_environment'],authority:grant(f.repo)};for(const constraints of ['My password is synthetic-secret','My mailbox number is 4827'])assert.throws(()=>b.workers.registerTemplate({project:'fixture',workspace_alias:'public',template:{...template,constraints},confirmed:true}));assert.equal(b.workers.templates().length,0);await assert.rejects(b.workers.qualify('codex',{confirmed:true,model:['sk','proj','SyntheticCredentialCanary123'].join('-'),request_id:randomUUID()}));assert.equal(b.workers.current('codex').qualified,true);});

function hello(name,{ech=false}={}){const u16=n=>{const b=Buffer.alloc(2);b.writeUInt16BE(n);return b;},host=Buffer.from(name),sni=Buffer.concat([u16(host.length+3),Buffer.from([0]),u16(host.length),host]),extension=Buffer.concat([u16(0),u16(sni.length),sni,...(ech?[u16(0xfe0d),u16(0)]:[])]),body=Buffer.concat([Buffer.from([3,3]),Buffer.alloc(32),Buffer.from([0]),u16(2),Buffer.from([0x13,1]),Buffer.from([1,0]),u16(extension.length),extension]),handshake=Buffer.alloc(4);handshake[0]=1;handshake.writeUIntBE(body.length,1,3);const payload=Buffer.concat([handshake,body]);return Buffer.concat([Buffer.from([22,3,1]),u16(payload.length),payload]);}
test('TLS transport validates exact buffered SNI and rejects ECH and plaintext',()=>{const b=hello('api.anthropic.com');assert.equal(worker.clientHelloHost(b),'api.anthropic.com');for(let n=0;n<b.length;n++)assert.equal(worker.clientHelloHost(b.subarray(0,n)),null);assert.throws(()=>worker.clientHelloHost(hello('api.anthropic.com',{ech:true})));assert.throws(()=>worker.clientHelloHost(Buffer.from('GET / HTTP/1.1')));});
test('proxy redacts unknown destinations and rejects SNI mismatch before upstream',async()=>{const net=require('node:net'),dns=require('node:dns/promises'),connect=net.connect,lookup=dns.lookup,events=[],controller=new AbortController();let upstream=0;dns.lookup=async()=>[{address:'1.1.1.1',family:4}];net.connect=function(o,...rest){if(o?.host==='1.1.1.1'){upstream++;return new net.Socket();}return connect.call(this,o,...rest);};const p=await worker.proxy(['api.anthropic.com'],controller,e=>events.push(e));const clients=[];async function send(host,sni){const c=connect({host:'127.0.0.1',port:p.port});clients.push(c);c.on('error',()=>{});await new Promise(r=>c.once('connect',r));c.write('CONNECT '+host+':443 HTTP/1.1\r\nHost: '+host+':443\r\n\r\n');if(sni){await new Promise(r=>c.once('data',r));c.write(hello(sni));}await new Promise(r=>setTimeout(r,30));c.destroy();}try{await send('private-canary.invalid',null);assert.equal(events[0].host,'[denied]');assert.doesNotMatch(JSON.stringify(events),/private-canary/);await send('api.anthropic.com','other.invalid');assert.equal(upstream,0);await send('api.anthropic.com','api.anthropic.com');assert.equal(upstream,1);}finally{for(const c of clients)c.destroy();await p.close();net.connect=connect;dns.lookup=lookup;}});
test('actual macOS sandbox denies fork and unrelated file content',t=>{if(process.platform!=='darwin')return t.skip('macOS only');const r=root(t),isolated=path.join(r,'isolated');fs.mkdirSync(isolated);fs.mkdirSync(path.join(isolated,'state'));const canary=path.join(r,'private-canary');fs.writeFileSync(canary,'private-worker-test-canary');const p=worker.sandbox(isolated,'/bin/sh','claude_code',32109),cp=require('node:child_process');const fork=cp.spawnSync('/usr/bin/sandbox-exec',['-p',p,'/bin/sh','-c','( : ); exit 73'],{cwd:isolated,env:{HOME:isolated,PATH:'/usr/bin:/bin'},encoding:'utf8',timeout:5000});assert.notEqual(fork.status,73);assert.match(fork.stderr,/fork|Operation not permitted/i);const read=cp.spawnSync('/usr/bin/sandbox-exec',['-p',p,'/bin/sh','-c','IFS= read -r value < "$1"; printf "%s" "$value"','fixture',canary],{cwd:isolated,env:{HOME:isolated,PATH:'/usr/bin:/bin'},encoding:'utf8',timeout:5000});assert.doesNotMatch(read.stdout,/private-worker-test-canary/);});
test('canonical Router V2 dispatches the signed bounded vendor contract with empty context',async t=>{const f=await setup(t),b=f.bridge;require('./fixtures/opencode-fixture.cjs').qualifyCanonical(b);const m=f.create();b.missions.dispatch(m.id,{request_id:randomUUID()});const done=await f.settle(m.id);assert.equal(done.runs[0].agent_id,'codex');assert.equal(done.verifications[0].result,'passed');});
