'use strict';
process.env.NODE_ENV='test';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {fixture}=require('./fixtures/mission-fixture.cjs'),synthetic=require('./fixtures/bounded-worker-fixture.cjs'),ControlServer=require('../src/control-server');
test('worker UI qualifies only with public fixture consent, shows expiry and revokes; APIs are operator-only',async t=>{
 const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'worker-ui-')));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const f=await fixture(t,{workers:{codex:synthetic.options(root)}}),b=f.bridge;b.missionAuthority.initializeOperatorKey();const server=new ControlServer(b,{port:0});await server.start();t.after(()=>server.close());
 for(const token of [null,server.mcpToken]){const r=await fetch(server.origin+'/api/assistant/workers/qualify',{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify({worker:'codex',model:'fixture-model',confirmed:true,request_id:require('node:crypto').randomUUID()})});assert.notEqual(r.status,200);}
 const browser=await require('playwright-core').chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.name));await page.addInitScript(token=>sessionStorage.setItem('airodromToken',token),server.token);await page.goto(server.origin+'/');await page.getByText('Live · local',{exact:true}).waitFor();await page.getByRole('button',{name:'Workers',exact:true}).click();await page.getByRole('button',{name:'Qualify codex',exact:true}).waitFor();page.on('dialog',dialog=>dialog.accept(dialog.type()==='prompt'?'fixture-model':undefined));await page.getByRole('button',{name:'Qualify codex',exact:true}).click();await page.getByRole('button',{name:'Revoke codex',exact:true}).waitFor();assert.equal(b.workers.current('codex').qualified,true);const text=await page.locator('body').innerText();assert.match(text,/Qualification expiry/);assert.doesNotMatch(text,/\d+%|Bearer|synthetic-secret|executable_sha256/);await page.setViewportSize({width:320,height:780});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);if(process.env.AIRODROM_WORKER_UI_SCREENSHOT)await page.screenshot({path:process.env.AIRODROM_WORKER_UI_SCREENSHOT,fullPage:true});await page.getByRole('button',{name:'Revoke codex',exact:true}).click();for(let n=0;n<100&&b.workers.current('codex').qualified;n++)await new Promise(r=>setTimeout(r,10));assert.equal(b.workers.current('codex').qualified,false);assert.equal(errors.length,0);
 const r=await fetch(server.origin+'/api/assistant/registry',{headers:{Authorization:'Bearer '+server.token}});const catalog=await r.json();assert.doesNotMatch(JSON.stringify(catalog.workers),/executable|sha256|\/Users\//);
});
