'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {DatabaseSync}=require('node:sqlite'),{randomUUID}=require('node:crypto');
const {ControlPlaneStore}=require('../src/control-plane-store'),{EventLedger}=require('../src/event-ledger');
const identity=require('../src/memory-identity'),content=require('../src/memory-content-erasure');
function fixture(t){const db=new DatabaseSync(':memory:');t.after(()=>db.close());const store=new ControlPlaneStore({db,ledger:new EventLedger(db),now:()=>1000});identity.install(db);content.install(db);return{db,store,out:store.outbox};}
function queue(f,key){return f.out.enqueue({key,destination:'fixture',ref:'local',eventType:'fixture.result',payload:{personal:'fixture outbox canary'}});}
function retire(f,id){f.db.prepare("INSERT INTO memory_erasure_content_rows(table_name,row_key,generation) VALUES('cp_effect_outbox',?,1)").run(JSON.stringify([id]));}
for(const state of ['pending','failed','applying'])test('outbox refuses delivery while identity migration is '+state,async t=>{const f=fixture(t);queue(f,'fixture-one');let calls=0;f.out.register('fixture',()=>{calls++;return{ok:true};});f.db.prepare('UPDATE memory_identity_progress SET state=?').run(state);await assert.rejects(f.out.dispatch(),/identity|migration|retained/i);assert.equal(calls,0);assert.equal(f.db.prepare('SELECT attempts FROM cp_effect_outbox').get().attempts,0);});
test('outbox checks again between asynchronous deliveries and never caches the next payload',async t=>{const f=fixture(t);queue(f,'fixture-one');queue(f,'fixture-two');let calls=0;f.out.register('fixture',async()=>{calls++;await Promise.resolve();f.db.prepare("UPDATE memory_identity_progress SET state='failed'").run();return{personal:'fixture returned canary'};});await assert.rejects(f.out.dispatch(),/identity|migration/i);assert.equal(calls,1);assert.equal(f.db.prepare("SELECT attempts FROM cp_effect_outbox WHERE event_key='fixture-two'").get().attempts,0);assert.equal(f.db.prepare('SELECT count(*) n FROM cp_effect_outbox WHERE receipt IS NOT NULL').get().n,0);});
test('completed erasure disposition suppresses queued delivery even after global state is complete',async t=>{const f=fixture(t),id=queue(f,'fixture-one');retire(f,id);let calls=0;f.out.register('fixture',()=>{calls++;return{ok:true};});await f.out.dispatch();assert.equal(calls,0);assert.equal(f.db.prepare('SELECT attempts FROM cp_effect_outbox').get().attempts,0);});
test('receipt racing erasure cannot repopulate a retired outbox row',async t=>{const f=fixture(t),id=queue(f,'fixture-one');f.out.register('fixture',async()=>{await Promise.resolve();retire(f,id);return{personal:'fixture returned canary'};});await f.out.dispatch();const row=f.db.prepare('SELECT receipt,status FROM cp_effect_outbox').get();assert.equal(row.receipt,null);assert.notEqual(row.status,'sent');});
test('outbox freshly fetches current payload after an earlier asynchronous handler',async t=>{const f=fixture(t);queue(f,'fixture-one');const second=queue(f,'fixture-two');const seen=[];f.out.register('fixture',async row=>{seen.push(row.payload);if(row.event_key==='fixture-one'){await Promise.resolve();f.db.prepare('UPDATE cp_effect_outbox SET payload=? WHERE id=?').run(JSON.stringify({generation:'current'}),second);}return{ok:true};});await f.out.dispatch();assert.deepEqual(seen[1],{generation:'current'});assert.equal(f.out.health().counts.sent,2);});
test('operator collection reads and invocation replay deny incomplete migration',t=>{const f=fixture(t);f.db.prepare('INSERT INTO cp_invocations(request_id,task_id,fingerprint,state,result,created_at,updated_at,origin_event_id) VALUES(?,?,?,?,?,?,?,?)').run(randomUUID(),randomUUID(),'fixture-hash','settled',JSON.stringify({personal:'fixture outbox canary'}),1,1,randomUUID());f.db.prepare("UPDATE memory_identity_progress SET state='failed'").run();assert.throws(()=>f.store.invocation(f.db.prepare('SELECT request_id FROM cp_invocations').get().request_id),/migration/i);assert.throws(()=>require('../src/control-plane-api').controlPlaneRead({controlStore:f.store},new URL('http://localhost/api/control-v2/candidates')),/migration/i);});
