'use strict';
// Optional browser infrastructure; callers supply an installed Playwright module.
const test=require('node:test'),assert=require('node:assert/strict');
const engines=require(process.env.AIRODROM_PLAYWRIGHT_MODULE||'playwright'),engine=process.env.AIRODROM_BROWSER_ENGINE||'chromium';
const {fixture}=require('./fixtures/mission-fixture.cjs'),{runtime}=require('./fixtures/opencode-fixture.cjs'),ControlServer=require('../src/control-server');
const display=require('../src/product-observability');
test('cockpit browser: responsive, private, reduced motion, focus, pause, filtering and auth loss',async t=>{
 const r=runtime(t),f=await fixture(t,{opencode:r.options}),b=f.bridge,server=new ControlServer(b,{port:0});await server.start();t.after(()=>server.close());
 const browser=await engines[engine].launch({...(engine==='chromium'?{channel:process.env.AIRODROM_BROWSER_CHANNEL||'chrome'}:{}),headless:process.env.AIRODROM_BROWSER_HEADFUL!=='1',timeout:30000});t.after(()=>browser.close());
 const page=await browser.newPage({viewport:{width:1440,height:1000}});await page.addInitScript(token=>sessionStorage.setItem('airodromToken',token),server.token);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));let calls=0,deny=false,hold=null;
 b.projects.createProject({name:'Second synthetic project'});const initial=await display.overview(b);const seed=b.rememberPersonalMemory({domain:'personal',type:'fact',subject:'browser color',content:'Synthetic cobalt reference',source:'user_explicit',sensitivity:'normal'});initial.memory=display.memoryStatus(b);
 await page.route('**/api/product/overview*',async route=>{calls++;if(deny)return route.fulfill({status:401,contentType:'application/json',body:'{}'});if(hold){const gate=hold;hold=null;await gate;}initial.memory=display.memoryStatus(b);return route.fulfill({contentType:'application/json',body:JSON.stringify(initial)});});
 await page.goto(server.origin+'/');await page.getByText('Live · local',{exact:true}).waitFor();
 await t.test('no private canaries enter DOM, authentication stays out of the URL',async()=>{assert.equal(new URL(page.url()).hash,'');assert.doesNotMatch(await page.locator('body').innerText(),/Bearer|token=|PRIVATE_REASONING/);assert.equal(errors.length,0);});
 await t.test('responsive layout and reduced motion',async()=>{await page.setViewportSize({width:320,height:780});await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches),true);for(const name of ['Missions','Memory','Projects','Runtime & OpenCode','Approvals','Activity & Audit','System Health','Settings & About','Overview']){await page.getByRole('button',{name,exact:true}).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,name+' fits320px');}await page.setViewportSize({width:1440,height:1000});});
 await t.test('focused Mission search retains text and caret through refresh',async()=>{await page.getByRole('button',{name:'Missions',exact:true}).click();const input=page.getByRole('searchbox');await input.fill('opencode');await input.focus();await page.waitForTimeout(2800);assert.equal(await input.inputValue(),'opencode');assert.equal(await input.evaluate(e=>document.activeElement===e),true);});
 await t.test('dialog close restores keyboard focus',async()=>{const button=page.getByRole('button',{name:'New Mission',exact:true});await button.click();await page.getByRole('button',{name:'Close',exact:true}).first().click();await page.waitForFunction(()=>document.activeElement.id==='new');assert.equal(await button.evaluate(e=>document.activeElement===e),true);});
 await t.test('pause invalidates an in-flight update',async()=>{let release;hold=new Promise(r=>release=r);await page.waitForTimeout(2800);await page.getByRole('button',{name:'Pause updates',exact:true}).click();release();await page.waitForTimeout(300);assert.equal(await page.getByText('Updates paused · stale',{exact:true}).count(),1);const before=calls;await page.waitForTimeout(2800);assert.equal(calls,before);await page.getByRole('button',{name:'Resume updates',exact:true}).click();await page.getByText('Live · local',{exact:true}).waitFor();});
 await t.test('event category change reconciles the cursor and filters safely',async()=>{b.ledger.record({eventType:'mission.created',agent:'bridge',direction:'internal',metadata:{prompt:'PRIVATE_REASONING'}});b.ledger.record({eventType:'approval.expired',agent:'bridge',direction:'internal',metadata:{secret:'PRIVATE_SECRET'}});assert.ok(display.events(b,new URL('http://local/api/product/events?category=Approval')).events.some(e=>e.label==='Protected approval expired'),'canonical filter contains approval');await page.getByRole('button',{name:'Activity & Audit',exact:true}).click();await page.getByRole('combobox',{name:'Event category'}).selectOption('Approval');await page.locator('.feed li').filter({hasText:'Protected approval expired'}).waitFor();assert.equal(await page.getByText('Mission registered',{exact:true}).count(),0);assert.doesNotMatch(await page.locator('body').innerText(),/PRIVATE_/);});
 await t.test('explicit Memory retrieval clears after a canonical correction and forgetting',async()=>{await page.getByRole('button',{name:'Memory',exact:true}).click();assert.equal(await page.getByText('Synthetic cobalt reference',{exact:true}).count(),0);await page.getByRole('button',{name:'Retrieve current Memory',exact:true}).click();await page.getByText('Synthetic cobalt reference',{exact:true}).waitFor();const corrected=b.updatePersonalMemory(seed.memoryId,{content:'Synthetic amber reference'});await page.waitForTimeout(3000);assert.equal(await page.getByText('Synthetic cobalt reference',{exact:true}).count(),0);await page.getByRole('button',{name:'Retrieve current Memory',exact:true}).click();await page.getByText('Synthetic amber reference',{exact:true}).waitFor();await page.getByRole('button',{name:'Forget selected record',exact:true}).click();assert.equal(await page.getByText('Synthetic amber reference',{exact:true}).count(),0);await page.waitForTimeout(1000);assert.equal(b.personalMemory.get(corrected.memoryId),null);});
 await t.test('a delayed pre-forget Memory response cannot repopulate discarded content',async()=>{const memory=b.rememberPersonalMemory({domain:'personal',type:'fact',subject:'race color',content:'Synthetic delayed green',source:'user_explicit',sensitivity:'normal'});await page.waitForTimeout(3000);await page.getByRole('button',{name:'Retrieve current Memory',exact:true}).click();await page.getByText('Synthetic delayed green',{exact:true}).waitFor();let release,started;const gate=new Promise(r=>release=r),begin=new Promise(r=>started=r);await page.route('**/api/product/memory?*',async route=>{const reply=await route.fetch();const body=await reply.text();started();await gate;try{await route.fulfill({contentType:'application/json',body});}catch{}});await page.getByRole('button',{name:'Retrieve current Memory',exact:true}).click();await begin;await page.getByRole('button',{name:'Forget selected record',exact:true}).click();release();await page.waitForTimeout(1000);assert.equal(await page.getByText('Synthetic delayed green',{exact:true}).count(),0);assert.equal(b.personalMemory.get(memory.memoryId),null);await page.unroute('**/api/product/memory?*');});
 await t.test('per-record action focus stays bound to the same Memory and project',async()=>{const item=b.rememberPersonalMemory({domain:'personal',type:'fact',subject:'Z'.repeat(160),content:'W'.repeat(1000),source:'user_explicit',sensitivity:'normal'});b.rememberPersonalMemory({domain:'personal',type:'fact',subject:'Second focus record',content:'Synthetic focus reference',source:'user_explicit',sensitivity:'normal'});await page.waitForTimeout(3000);await page.getByRole('button',{name:'Retrieve current Memory',exact:true}).click();const forget=page.getByRole('button',{name:'Forget selected record',exact:true}).nth(1);await forget.waitFor();await forget.focus();const key=await forget.getAttribute('data-focus-key');await page.waitForTimeout(2800);assert.equal(await page.evaluate(()=>document.activeElement.dataset.focusKey),key);await page.setViewportSize({width:320,height:780});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'Projects',exact:true}).click();const archive=page.getByRole('button',{name:'Archive project',exact:true}).nth(1);await archive.focus();const projectKey=await archive.getAttribute('data-focus-key');await page.waitForTimeout(2800);assert.equal(await page.evaluate(()=>document.activeElement.dataset.focusKey),projectKey);b.forgetPersonalMemory(item.memoryId);});
 await t.test('authorization loss stops polling until private authorization is restored',async()=>{deny=true;await page.getByText('Authorization required',{exact:true}).waitFor({timeout:10000});const before=calls;await page.waitForTimeout(3000);assert.equal(calls,before);assert.equal(errors.length,0);});
});
