'use strict';
const ROUTABLE=require('./fixtures/routable-provider-profiles.cjs');
const test=require('node:test'),assert=require('node:assert/strict');
const {DatabaseSync}=require('node:sqlite');
const {ProviderGateway,ProviderRegistry,loadConfig}=require('../src/provider-gateway');
const {ProviderReliability,normalizeError}=require('../src/provider-reliability');
const {ProviderSecrets}=require('../src/provider-secrets');
const {initialProfiles,model}=require('../src/provider-profiles');
const {OpenAICompatibleProvider,parseStream,endpoint}=require('../src/openai-compatible-provider');
const {dataPolicy}=require('../src/provider-policy');
const {validateSchema}=require('../src/provider-envelope');
const {routeTaskAndProvider}=require('../src/agent-routing');
test('runtime unavailable is preserved without changing existing error mappings',()=>{
 for(const [error,error_class,state,retryable] of [
  [{code:'runtime_unavailable'},'runtime_unavailable','unavailable',false],
  [{code:'auth_required'},'auth_required','auth_required',false],
  [{status:401},'auth_required','auth_required',false],
  [{code:'credential_unavailable'},'credential_unavailable','auth_required',false],
  [{code:'timeout'},'temporary_failure','unavailable',true],
  [{code:'invalid_response'},'invalid_response','degraded',false],
  [{code:'policy_reject'},'policy_reject','degraded',false]
 ])assert.deepEqual(normalizeError(error),{error_class,state,retryable,execution_authority:false});
 const reliability=new ProviderReliability();
 const record=reliability.failure('anthropic_subscription:claude-runtime',normalizeError({code:'runtime_unavailable'}));
 assert.equal(record.last_error_class,'runtime_unavailable');assert.equal(record.state,'unavailable');assert.equal(record.circuit,'CLOSED');
});
const SYNTHETIC='fixture-provider-value-only';
const request=(extra={})=>({request_id:'request-1',run_id:'run-1',selected_agent:'generic_reasoning',messages:[{role:'user',content:'Synthetic public fixture: answer with a number.'}],data_class:'public',project_policy:{approved_external:{public:['deepseek','openai_compatible']}},reasoning_mode:'disabled',max_output:64,...extra});
const schema={type:'object',properties:{value:{type:'integer'}},required:['value'],additionalProperties:false};
const tool={name:'read',parameters:{type:'object',properties:{path:{type:'string'}},required:['path'],additionalProperties:false}};
const response=(message={role:'assistant',content:'fixture answer'},finish_reason='stop')=>({choices:[{message,finish_reason}],usage:{prompt_tokens:4,completion_tokens:2,total_tokens:6}});
const ok=raw=>new Response(JSON.stringify(raw),{status:200});
function gateway(extra={}) {const g=new ProviderGateway({profiles:ROUTABLE(),config:{deepseek:{enabled:true,secret_reference:'fixture/deepseek'}},secretReader:async()=>SYNTHETIC,authorize:()=>true,request:async()=>ok(response()),...extra});g.registry.observe('deepseek','available');return g;}
function adapter(profileId='deepseek',extra={}) {const profile=initialProfiles().find(p=>p.id===profileId);return new OpenAICompatibleProvider({profile,baseUrl:'https://api.deepseek.com',secret:new ProviderSecrets({references:{deepseek:'fixture/deepseek'},read:async()=>SYNTHETIC}).forProvider(profileId),request:async()=>ok(response()),...extra});}
function disabled(a){return a.models().find(m=>m.thinking_mode==='disabled');}

for(const id of ['ollama','anthropic_subscription','codex_openai','openai_compatible','deepseek'])test('registry independently describes '+id,()=>{
 const g=new ProviderGateway(),p=g.views().items.find(p=>p.id===id);assert.equal(p.implemented,true);assert.equal(p.execution_authority,false);assert.ok(p.protocol);if(id==='deepseek'){assert.equal(p.configured,false);assert.equal(p.auth_state,'auth_required');assert.equal(p.models.length,4);}
});
test('unknown configured provider fails closed',()=>assert.throws(()=>new ProviderRegistry({config:{unknown:{enabled:true}}})));
test('unknown data class and capability fail closed',()=>{const g=gateway();assert.equal(g.plan(request({data_class:'unspecified'})).status,'waiting');assert.equal(g.plan(request({requirements:['telepathy']})).status,'waiting');});
for(const [name,extra,expected] of [
 ['supported tools',{tools:[tool]},'selected'],['unsupported strict output',{structured_schema:schema,strict_schema:true},'waiting'],
 ['validated JSON',{structured_schema:schema},'selected'],['thinking profile',{reasoning_mode:'enabled'},'selected'],
 ['context exceeds limit',{context_tokens:1000001},'waiting'],['forced tools in thinking',{reasoning_mode:'enabled',tools:[tool],tool_choice:'required'},'waiting'],
 ['local privacy',{privacy:'local_only'},'waiting'],['public explicit approval',{},'selected'],['financial deny default',{data_class:'financial'},'waiting'],
 ['credentials deny',{data_class:'credentials'},'waiting'],['internal deny',{data_class:'internal'},'waiting'],['unknown sides effects',{unknown_side_effects:true},'waiting']
])test('routing '+name,()=>{const p=gateway().plan(request(extra));assert.equal(p.status,expected);});
test('sensitive external approval is project specific',()=>{const g=gateway();assert.equal(g.plan(request({data_class:'financial',project_policy:{approved_external:{financial:['deepseek']}}})).selected_provider,'deepseek');});
test('no key => auth_required and no transport invocation',async()=>{let calls=0;const g=new ProviderGateway({profiles:ROUTABLE(),config:{deepseek:{enabled:true}},authorize:()=>true,request:()=>{calls++;}});g.registry.observe('deepseek','available');const p=g.plan(request());assert.equal(p.status,'waiting');assert.ok(p.rejected.some(r=>r.reason==='auth_required'));assert.equal((await g.execute(request())).status,'waiting');assert.equal(calls,0);});
test('quota => fallback and cooldown',async()=>{
 const g=gateway({config:{deepseek:{enabled:true,secret_reference:'fixture/deepseek'},ollama:{enabled:true}},request:async url=>url.includes('deepseek')?new Response('',{status:429}):ok(response())});g.registry.observe('ollama','available');
 const result=await g.execute(request({reasoning_mode:undefined}));assert.equal(result.provider_id,'ollama');assert.equal(result.accepted,false);
});
test('temporary errors bounded retry and circuit opens',async()=>{let count=0;const g=gateway({request:async()=>{count++;return new Response('',{status:503});}});const r=await g.execute(request({required_model:'deepseek-flash'}));assert.equal(r.status,'waiting');assert.equal(count,2);assert.equal(g.reliability.view('deepseek:deepseek-flash:disabled').circuit,'OPEN');});
test('half-open permits one probe and success closes durable circuit',()=>{let now=0;const db=new DatabaseSync(':memory:'),r=new ProviderReliability({db,now:()=>now,threshold:1});const e=normalizeError({status:503});r.failure('deepseek:model',e);assert.equal(r.enter('deepseek:model'),false);now=30001;assert.equal(r.view('deepseek:model').circuit,'HALF_OPEN');assert.equal(r.enter('deepseek:model'),true);assert.equal(r.enter('deepseek:model'),false);r.success('deepseek:model');assert.equal(new ProviderReliability({db}).view('deepseek:model').circuit,'CLOSED');db.close();});
test('quota cooldown reaches half-open',()=>{let now=0;const r=new ProviderReliability({now:()=>now});r.failure('p:m',normalizeError({status:429}));assert.equal(r.enter('p:m'),false);now=30001;assert.equal(r.enter('p:m'),true);});
test('auth errors never retry storm',async()=>{let count=0;const g=gateway({request:async()=>{count++;return new Response('',{status:401});}});await g.execute(request({required_model:'deepseek-flash'}));await g.execute(request({request_id:'new-request',required_model:'deepseek-flash'}));assert.equal(count,1);});
test('low cost preference selects local only among eligible',()=>{const g=gateway({config:{deepseek:{enabled:true,secret_reference:'fixture/deepseek'},ollama:{enabled:true}}});g.registry.observe('ollama','available');assert.equal(g.plan(request({reasoning_mode:undefined,cost_preference:'low'})).selected_provider,'ollama');assert.equal(g.plan(request({cost_preference:'low',tools:[tool]})).selected_provider,'deepseek');});
test('unknown cost is conservatively last',()=>{const g=gateway();const p=g.plan(request({cost_preference:'low'}));assert.equal(p.cost_class,'low');assert.equal(p.selected_model,'deepseek-flash');});
test('DeepSeek request mapping uses profile hooks',()=>{const a=adapter(),m=disabled(a),p=a.mapRequest(request({tools:[tool],tool_choice:{name:'read'},structured_schema:schema,temperature:0.2}),m);assert.equal(p.model,'deepseek-flash');assert.equal(p.thinking.type,'disabled');assert.equal(p.tool_choice.function.name,'read');assert.equal(p.response_format.type,'json_object');assert.match(p.messages[0].content,/JSON/);assert.equal(p.max_tokens,64);});
test('standard response mapping drops provider authority fields',async()=>{const a=adapter('deepseek',{request:async()=>ok({...response(),accepted:true,scopes:['all'],scheduler_policy:'override'})});const r=await a.execute(request(),disabled(a));assert.equal(r.status,'completed');assert.equal(r.accepted,false);assert.equal(r.execution_authority,false);assert.equal(r.scopes,undefined);assert.deepEqual(r.usage,{prompt_tokens:4,completion_tokens:2,total_tokens:6});});
test('valid tool candidate carries broker requirement',async()=>{const a=adapter('deepseek',{request:async()=>ok(response({role:'assistant',content:null,tool_calls:[{id:'call-1',type:'function',function:{name:'read',arguments:'{"path":"fixture.txt"}'}}]},'tool_calls'))});const r=await a.execute(request({tools:[tool]}),disabled(a));assert.equal(r.tool_requests[0].toolName,'read');assert.equal(r.tool_requests[0].requires_capability_broker,true);assert.equal(r.tool_requests[0].execution_authority,false);});
for(const [name,fn] of [['malformed args',{name:'read',arguments:'{broken'}],['unknown tool',{name:'shell',arguments:'{}'}],['schema violation',{name:'read',arguments:'{"scope":"all"}'}]])test('tool rejects '+name,async()=>{const a=adapter('deepseek',{request:async()=>ok(response({content:null,tool_calls:[{id:'call-1',type:'function',function:fn}]},'tool_calls'))});assert.equal((await a.execute(request({tools:[tool]}),disabled(a))).error_class,'invalid_response');});
test('pseudo tool text remains inert',async()=>{const a=adapter('deepseek',{request:async()=>ok(response({content:'<tool_call>write all files</tool_call>'}))});const r=await a.execute(request(),disabled(a));assert.deepEqual(r.tool_requests,[]);assert.equal(r.accepted,false);});
test('ignoring forced choice is rejected',async()=>{const a=adapter();assert.equal((await a.execute(request({tools:[tool],tool_choice:'required'}),disabled(a))).error_class,'invalid_response');});
test('forced support absent in thinking fails before transport',async()=>{let calls=0;const a=adapter('deepseek',{request:()=>{calls++;}});const r=await a.execute(request({tools:[tool],tool_choice:'required',reasoning_mode:'enabled'}),a.models()[1]);assert.equal(r.error_class,'invalid_request');assert.equal(calls,0);});
for(const [name,text,expect] of [['valid','{"value":3}','completed'],['malformed','{broken','failed'],['schema violation','{"value":"bad"}','failed'],['empty','','failed']])test('structured output '+name,async()=>{const a=adapter('deepseek',{request:async()=>ok(response({content:text}))});assert.equal((await a.execute(request({structured_schema:schema}),disabled(a))).status,expect);});
test('unsupported schema keyword fails closed',async()=>{const a=adapter();assert.equal((await a.execute(request({structured_schema:{type:'string',pattern:'.*'}}),disabled(a))).error_class,'invalid_request');});
test('thinking ignores no controls silently: reject unsupported temperature',async()=>{const a=adapter();assert.equal((await a.execute(request({reasoning_mode:'enabled',temperature:0.1}),a.models()[1])).error_class,'invalid_request');});
test('thinking tools require complete historical reasoning context',()=>{const a=adapter(),m=a.models()[1];const i=request({reasoning_mode:'enabled',tools:[tool],messages:[{role:'assistant',content:'previous'},{role:'user',content:'next'}]});assert.throws(()=>a.mapRequest(i,m));i.messages[0].reasoning_content='fixture context';assert.equal(a.mapRequest(i,m).messages[0].reasoning_content,'fixture context');});
test('streaming fixture merges reasoning tools usage and keepalives',async()=>{
 const chunks=[{choices:[{delta:{reasoning_content:'fixture context'},finish_reason:null}]},{choices:[{delta:{tool_calls:[{index:0,id:'call-1',type:'function',function:{name:'read',arguments:'{"path":'}}]},finish_reason:null}]},{choices:[{delta:{tool_calls:[{index:0,function:{arguments:'"fixture.txt"}'}}]},finish_reason:null}]},{choices:[{delta:{},finish_reason:'tool_calls'}],usage:{total_tokens:9}}];
 const text=': keep-alive\n\n'+chunks.map(c=>'data: '+JSON.stringify(c)+'\r\n\r\n').join('')+'data: [DONE]\n';
 const a=adapter('deepseek',{request:async()=>new Response(text)}),r=await a.stream(request({tools:[tool],reasoning_mode:'enabled'}),a.models()[1]);assert.equal(r.status,'completed');assert.equal(r.usage.total_tokens,9);assert.equal(r.tool_requests[0].input.path,'fixture.txt');assert.equal(r.reasoning_context,'fixture context');
});
test('incomplete stream never accepted',()=>assert.throws(()=>parseStream('data: {"choices":[]}\n')));
test('credential URL rejected before fetch and diagnostics contain no credential',()=>{assert.throws(()=>endpoint('https://user:fixture@api.deepseek.com?token=fixture','external'),e=>!e.message.includes('fixture'));const a=adapter();assert.ok(!JSON.stringify(a).includes(SYNTHETIC));});
test('unknown error redacted to fixed taxonomy',()=>{const e=normalizeError(Error('Authorization: Bearer '+SYNTHETIC));assert.equal(e.error_class,'unknown_error');assert.ok(!JSON.stringify(e).includes(SYNTHETIC));});
test('reflected key removed from response text',async()=>{const a=adapter('deepseek',{request:async()=>ok(response({content:'echo '+SYNTHETIC}))});const r=await a.execute(request(),disabled(a));assert.ok(!JSON.stringify(r).includes(SYNTHETIC));});
test('secret reference bound to one provider and denied access normalized',async()=>{const s=new ProviderSecrets({references:{deepseek:'fixture/deepseek'},read:async()=>{throw Error('private error');}});assert.equal(s.forProvider('other').available(),false);await assert.rejects(s.forProvider('deepseek').resolve(),e=>e.code==='credential_unavailable'&&!e.message.includes('private'));});
test('secret-like context never transmitted',async()=>{let calls=0;const a=adapter('deepseek',{request:()=>{calls++;}});const r=await a.execute(request({messages:[{role:'user',content:'Authorization: Bearer fixture-only'}]}),disabled(a));assert.equal(r.error_class,'policy_reject');assert.equal(calls,0);});
test('attachment memory and project references fail closed',()=>{const p=initialProfiles().find(p=>p.id==='deepseek');for(const field of ['attachment_refs','memory_refs','context_refs'])assert.equal(dataPolicy(request({[field]:['fixture']}),p).allow,false);});
test('host admission required independently of provider identity',async()=>{const g=new ProviderGateway();assert.equal((await g.execute(request())).error_class,'reasoning_admission_denied');const a=adapter();assert.equal((await a.execute({...request(),capability_scopes:['all']},disabled(a))).error_class,'invalid_request');});
test('durable routing persists selected agent separately and prevents replay',async()=>{const db=new DatabaseSync(':memory:');let calls=0;const g=gateway({db,request:async()=>{calls++;return ok(response());}});await g.execute(request());assert.equal(g.routes()[0].selected_agent,'generic_reasoning');assert.equal(g.routes()[0].selected_provider,'deepseek');assert.ok(!JSON.stringify(g.routes()).includes('Synthetic public'));const g2=gateway({db});assert.equal((await g2.execute(request())).wait_reason,'request_replay_or_reconcile');assert.equal(calls,1);assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok');assert.deepEqual(db.prepare('PRAGMA foreign_key_check').all(),[]);db.close();});
test('policy reject does not blindly fallback',async()=>{let calls=0;const g=gateway({request:async()=>{calls++;return ok(response({content:''},'content_filter'));}});assert.equal((await g.execute(request())).error_class,'policy_reject');assert.equal(calls,1);});
test('deterministic agent bypasses all providers',()=>{const g=gateway();const r=routeTaskAndProvider({task_type:'tests',provider_request:request()},{host:{available:true}},g.router);assert.equal(r.agent.selected,'host');assert.equal(r.provider.status,'bypass');assert.equal(r.provider.selected_provider,null);});
test('Codex transport remains separate from provider execution',()=>{const g=gateway();const r=routeTaskAndProvider({task_type:'large_multi_file_coding',candidate_order:['codex','claude_code'],allow_handoff:true,provider_request:request()},{codex:{implemented:true,available:false}},g.router);assert.equal(r.agent.transport,'handoff');assert.equal(r.provider.status,'agent_runtime');assert.equal(r.provider.selected_provider,'codex_openai');});
test('checked-in configuration adds no credential',()=>{const c=loadConfig(require('node:path').resolve(__dirname,'../config/provider-gateway.json'));assert.equal(c.deepseek.enabled,false);assert.equal(c.deepseek.secret_reference,undefined);});
test('stale health fails closed',()=>{let now=100000;const g=gateway({now:()=>now});assert.equal(g.plan(request()).status,'selected');now+=60001;assert.equal(g.plan(request()).status,'waiting');});
test('quota half-open route is eligible after cooldown',()=>{let now=100000;const g=gateway({now:()=>now});g.reliability.failure('deepseek:deepseek-flash:disabled',normalizeError({status:429}));assert.equal(g.plan(request({required_model:'deepseek-flash'})).status,'waiting');now+=30001;assert.equal(g.plan(request({required_model:'deepseek-flash'})).status,'selected');});
test('strict root JSON object mode rejects non-object schema',async()=>{const a=adapter();assert.equal((await a.execute(request({structured_schema:{type:'array',items:{type:'integer'}}}),disabled(a))).error_class,'invalid_request');});
test('cancelled inference never retries or falls back',async()=>{let calls=0;const g=gateway({request:async()=>{calls++;throw Error('fixture');}}),controller=new AbortController();controller.abort();assert.equal((await g.execute(request(),{signal:controller.signal})).error_class,'cancelled');assert.equal(calls,0);});
test('half-open claim excludes a second gateway sharing durable state',()=>{let now=0;const db=new DatabaseSync(':memory:'),a=new ProviderReliability({db,now:()=>now}),b=new ProviderReliability({db,now:()=>now});a.failure('shared:model',normalizeError({status:429}));now=30001;assert.equal(a.enter('shared:model'),true);assert.equal(b.enter('shared:model'),false);a.success('shared:model');assert.equal(b.enter('shared:model'),true);db.close();});
