'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto'),zlib=require('node:zlib'),{spawnSync}=require('node:child_process');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'release-policy-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));function write(name,value){const p=path.join(root,name);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,typeof value==='string'?value:JSON.stringify(value));}
 write('package.json',{name:'release-policy-fixture',version:'1.0.0-rc.1',private:true,license:'MIT',files:['src/','config/','scripts/','README.md','SECURITY.md','THIRD_PARTY_NOTICES.md']});write('package-lock.json',{name:'release-policy-fixture',version:'1.0.0-rc.1',lockfileVersion:3,packages:{'':{version:'1.0.0-rc.1'}}});for(const n of ['README.md','LICENSE','SECURITY.md','THIRD_PARTY_NOTICES.md'])write(n,'Synthetic public fixture.\n');write('src/sdk/index.js','module.exports={};\n');write('scripts/airodrom.cjs','console.log("fixture help");\n');for(const n of ['verify-public.cjs','source-archive.cjs','package-check.cjs'])write('scripts/'+n,fs.readFileSync(path.join(__dirname,'../scripts',n),'utf8'));
 write('docs/canonical.md','Canonical reference.\n');write('config/architecture-memory-sources-v1.json',{sources:[{path:'docs/canonical.md',source_hash:crypto.createHash('sha256').update('Canonical reference.\n').digest('hex')}],facts:[{source_ref:'docs/canonical.md',content:'Canonical reference.'}]});const files=[];function list(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())list(p);else files.push(path.relative(root,p));}}list(root);files.push('release-files.json');write('release-files.json',files.sort());return{root,write,run:(name,args=[])=>spawnSync(process.execPath,[path.join(root,'scripts',name),...args],{cwd:root,encoding:'utf8',timeout:30000})};}
test('release verification rejects an unexpected file and a symlink while its valid control passes',t=>{const f=fixture(t);assert.equal(f.run('verify-public.cjs').status,0);f.write('unexpected.env','seeded release-private-canary');let r=f.run('verify-public.cjs');assert.equal(r.status,1);assert.match(r.stdout,/not_allowlisted/);fs.unlinkSync(path.join(f.root,'unexpected.env'));fs.symlinkSync(path.join(f.root,'README.md'),path.join(f.root,'linked.md'));r=f.run('verify-public.cjs');assert.equal(r.status,1);assert.match(r.stdout,/symlink/);});
test('release verification detects altered canonical source and missing dependency integrity',t=>{const f=fixture(t);f.write('docs/canonical.md','Changed unreviewed reference.\n');let r=f.run('verify-public.cjs');assert.equal(r.status,1);assert.match(r.stdout,/canonical_hash/);const lock=JSON.parse(fs.readFileSync(path.join(f.root,'package-lock.json')));lock.packages['node_modules/fixture']={version:'1.0.0',resolved:'https://registry.npmjs.org/fixture/-/fixture-1.0.0.tgz'};f.write('package-lock.json',lock);r=f.run('verify-public.cjs');assert.equal(r.status,1);assert.match(r.stdout,/lock_integrity/);});
test('source archive is reproducible and excludes planted private runtime bytes',t=>{const f=fixture(t);f.write('.runtime/credential.json','seeded release-private-canary');const a=path.join(os.tmpdir(),'archive-a-'+process.pid),b=path.join(os.tmpdir(),'archive-b-'+process.pid);t.after(()=>{for(const p of [a,b])fs.rmSync(p,{force:true});});assert.equal(f.run('source-archive.cjs',[a]).status,0);assert.equal(f.run('source-archive.cjs',[b]).status,0);assert.deepEqual(fs.readFileSync(a),fs.readFileSync(b));assert.equal(zlib.gunzipSync(fs.readFileSync(a)).includes(Buffer.from('seeded release-private-canary')),false);});
test('source archive rejects a symlink even when the path is allowlisted',t=>{const f=fixture(t);const p=path.join(f.root,'README.md');fs.unlinkSync(p);fs.symlinkSync(path.join(f.root,'SECURITY.md'),p);const out=path.join(os.tmpdir(),'archive-denied-'+process.pid);t.after(()=>fs.rmSync(out,{force:true}));assert.notEqual(f.run('source-archive.cjs',[out]).status,0);assert.equal(fs.existsSync(out),false);});
test('npm dry-run gate excludes an injected local operator manifest and requires notices',t=>{const f=fixture(t);f.write('config/safe-autonomy-manifest.json','{}');f.write('.npmignore','config/safe-autonomy-manifest.json\n');let r=f.run('package-check.cjs');assert.equal(r.status,1);assert.match(r.stdout,/safe-autonomy-manifest/);const pkg=JSON.parse(fs.readFileSync(path.join(f.root,'package.json')));pkg.files=pkg.files.map(p=>p==='config/'?'config/architecture-memory-sources-v1.json':p);f.write('package.json',pkg);r=f.run('package-check.cjs');assert.equal(r.status,0,r.stdout);fs.unlinkSync(path.join(f.root,'THIRD_PARTY_NOTICES.md'));r=f.run('package-check.cjs');assert.equal(r.status,1);assert.match(r.stdout,/missing:THIRD_PARTY_NOTICES/);});

test('release verification excludes the root Git worktree pointer while checking other unlisted files',t=>{const f=fixture(t);f.write('.git','gitdir: /private/tmp/fixture-common/git/worktrees/fixture\n');assert.equal(f.run('verify-public.cjs').status,0);f.write('src/.git','not metadata');const r=f.run('verify-public.cjs');assert.equal(r.status,1);assert.match(r.stdout,/not_allowlisted/);});
