'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {scan}=require('../scripts/check-runtime-removal.cjs');
const {REMOVED_RUNTIME,assertExecutable}=require('../src/removed-runtime');
const {AgentAdapter,AgentRouter}=require('../src/agent-adapter');
const Bridge=require('../src/bridge-controller');
const {fixture}=require('./fixtures/mission-fixture.cjs');
function copy(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'runtime-regression-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));for(const dir of ['src','scripts','config','public','macos','.github'])fs.cpSync(path.resolve(__dirname,'..',dir),path.join(root,dir),{recursive:true});for(const f of ['package.json','package-lock.json'])fs.copyFileSync(path.resolve(__dirname,'..',f),path.join(root,f));return root;}
test('active source/config/UI/package/workflows have no removed runtime route or dependency',()=>assert.deepEqual(scan().errors,[]));
test('architecture gate rejects a new removed adapter import',t=>{const root=copy(t);fs.writeFileSync(path.join(root,'src/rogue.js'),"require('./"+REMOVED_RUNTIME+"-adapter');\n");assert(scan(root).errors.some(x=>x.rule==='removed_runtime_dependency'));});
test('architecture gate rejects an executable route despite a legacy protocol identifier',t=>{const root=copy(t);fs.appendFileSync(path.join(root,'public/branding.js'),"\nconst runtime='"+REMOVED_RUNTIME+"';\n");assert(scan(root).errors.some(x=>x.rule==='undocumented_legacy_identifier'));});
test('architecture gate rejects a removed environment selector',t=>{const root=copy(t);fs.writeFileSync(path.join(root,'src/rogue.js'),'const profile=process.env.'+'PI_'+'CODING_AGENT_DIR;\n');assert(scan(root).errors.some(x=>x.rule==='removed_runtime_dependency'));});
test('removed adapter cannot register, resolve, or become the default',()=>{const adapter=new AgentAdapter({id:REMOVED_RUNTIME,label:'removed'});assert.throws(()=>new AgentRouter({adapters:[adapter]}),/Historical runtime removed/);assert.throws(()=>new AgentRouter().resolve(REMOVED_RUNTIME),/Historical runtime removed/);assert.throws(()=>new Bridge({defaultRuntime:REMOVED_RUNTIME}),/Invalid default/);});
test('removed identity denial occurs before inspecting authority or memory',()=>{const value={executionAgent:REMOVED_RUNTIME,get mission(){throw Error('must not read');},get envelope(){throw Error('must not read');}};assert.throws(()=>assertExecutable(value),/Historical runtime removed/);});
test('pre-identity records retain historical identity and cannot start, resume or receive context',async t=>{const f=await fixture(t),b=f.bridge,task=b.tasks.get(b.createTask('Historical fixture').id);delete task.executionAgent;task.status='paused';task.mission.status='paused';b.tasks.save(task);await f.reopen();const old=f.bridge.tasks.get(task.id);assert.equal(old.executionAgent,REMOVED_RUNTIME);assert.equal(old.runtimeRemoved,true);await assert.rejects(f.bridge.ensureRuntime(old.id),/Historical runtime removed/);await assert.rejects(f.bridge.resume(old.id),/Historical runtime removed/);assert.throws(()=>f.bridge.authorizeActiveChatMission(old.id,{}),/Historical runtime removed/);assert.throws(()=>f.bridge.continueActiveChatMission(old.id,'ignored',{}),/Historical runtime removed/);assert.throws(()=>f.bridge.activateMcpContinuation(old.id),/Historical runtime removed/);assert.throws(()=>f.bridge.controlContext.build({id:'historical',task_id:old.id,envelope:{preferred_agent:REMOVED_RUNTIME}}),/Historical runtime removed/);assert.equal(f.bridge.runtimes.size,0);});
test('new runs and results cannot acquire removed historical identity',async t=>{const f=await fixture(t),b=f.bridge,task=b.createTask('Historical fixture');assert.throws(()=>b.controlStore.startRun({id:'retired-run',taskId:task.id,agentId:REMOVED_RUNTIME}),/Historical runtime removed/);assert.throws(()=>b.resultInbox.publish({agent_id:REMOVED_RUNTIME}),/Historical runtime removed/);assert.equal(b.controlStore.run('retired-run'),null);});
test('advisory and authority routing reject removed observations',()=>{const {routeTask}=require('../src/agent-routing');assert.equal(routeTask({task_type:'focused_refactor',candidate_order:[REMOVED_RUNTIME]},{[REMOVED_RUNTIME]:{available:true}}).selected,null);const {evaluateRouting}=require('../src/authority-router');const result=evaluateRouting({memory_state:'ready',context_current:true},[{agent_id:REMOVED_RUNTIME,runtime_id:REMOVED_RUNTIME,enabled:true,availability:'available',observed_at:1}],1);assert.equal(result.state,'WAIT');assert.equal(result.rejectedCandidates[0].reason,'runtime_removed');});
test('typed coding descriptor and independent verifier are Airodrom host primitives',()=>{const d=require('../src/qualified-coding-adapter').DESCRIPTOR;assert.equal(d.id,'airodrom.typed-coding');assert.equal(d.provider,null);assert.equal(d.termination,'in_process_awaited_capabilities');const source=fs.readFileSync(path.resolve(__dirname,'../src/mission-verifier.js'),'utf8');assert.match(source,/airodrom:host-verifier/);assert.doesNotMatch(source,/agentRouter|sendCommand/);});
test('general host execution has no worker process factory',async()=>{const b=new Bridge();b.tasks={get:()=>({id:'synthetic',executionAgent:'host',mission:{}})};await assert.rejects(b._ensureHostRuntime('synthetic'),/signed deterministic/);assert.equal(b.runtimes.size,0);assert.equal(b.executable,undefined);});
test('legacy environment variables cannot change provider or runtime selection',()=>{const name='PI_'+'BRIDGE_SOURCE_PROFILE',old=process.env[name];process.env[name]='/no/removed-profile';try{const p=require('../src/config').prepareControlProfile('/unused');assert.equal(p.provider,'ollama');assert.equal(new Bridge().defaultRuntime,'opencode');}finally{if(old===undefined)delete process.env[name];else process.env[name]=old;}});

test('historical task principals cannot invoke tools or receive memory through a direct broker caller', async t => { const f=await fixture(t), b=f.bridge, task=b.tasks.get(b.createTask('Historical principal').id); task.executionAgent=REMOVED_RUNTIME; b.tasks.save(task); b.policy.registerTask(task); for (const toolName of ['ls','personal_memory_recent']) { const result=await b.capabilityBroker.execute(task.id,{toolName,input:toolName==='ls'?{path:'.'}:{domain:'personal'}}); assert.equal(result.allow,false); assert.equal(result.decision.kind,'runtime_removed'); } const decision=b.policy.check(task.id,{toolName:'read',input:{path:'file.txt'}}); assert.equal(decision.allow,false); assert.equal(decision.kind,'runtime_removed'); });

test('historical completed evidence stays readable and cannot gain new execution', async t => { const f=await fixture(t), b=f.bridge, m=f.create(); const task=b.tasks.get(m.task_id); task.executionAgent=REMOVED_RUNTIME; task.status='completed'; task.lastResult='Historical synthetic evidence'; b.tasks.save(task); const envelope={...m.envelope,preferred_agent:REMOVED_RUNTIME}; b.controlStore.db.prepare('UPDATE cp_missions SET envelope=? WHERE id=?').run(JSON.stringify(envelope),m.id); const view=b.missions.detail(m.id); assert.equal(view.runtimeRemoved,true); assert.equal(view.next_action,'inspect'); assert.throws(()=>b.missions.dispatch(m.id,{request_id:'historical-dispatch'}),/Historical runtime removed/); await f.reopen(); const old=f.bridge.tasks.get(task.id); assert.equal(old.status,'completed'); assert.equal(old.lastResult,'Historical synthetic evidence'); assert.equal(f.bridge.snapshotTask(old).runtimeLabel,'Historical runtime removed'); await assert.rejects(f.bridge._ensureHostRuntime(old.id),/Historical runtime removed/); });

test('queued historical dispatch is retired once and cannot stall supported Missions',async t=>{
 const f=await fixture(t),b=f.bridge,db=b.controlStore.db,old=f.create();
 b.missions.queue(old.id);
 db.prepare('UPDATE cp_missions SET envelope=? WHERE id=?').run(JSON.stringify({...old.envelope,preferred_agent:REMOVED_RUNTIME}),old.id);
 const fresh=f.create({objective:'Fresh supported deterministic Mission',task_type:'local_files',dispatch_policy:{privacy:'local_only',providers:['local'],billing_classes:['local'],task_category:'deterministic_files',native_actions:[{name:'file_write',path:'fixture.txt',content:'beta\n'}]}});
 b.missions.queue(fresh.id);
 await b.missions.tick();await b.missions.tick();await b.missions.tick();
 assert.equal(b.missions.detail(old.id).state,'blocked');assert.equal(db.prepare('SELECT state FROM cp_dispatches WHERE mission_id=?').get(old.id).state,'blocked');
 assert.equal(db.prepare('SELECT count(*) n FROM cp_runs WHERE mission_id=?').get(old.id).n,0);
 assert.equal((await f.settle(fresh.id)).state,'awaiting_acceptance');assert.equal(f.inference(),0);assert.equal(f.calls(),0);
 assert.equal(b.ledger.list({missionId:old.id,limit:100}).events.filter(e=>e.event_type==='mission.historical_runtime_removed').length,1);
});

test('queued historical continuation is cancelled without releasing uncertain writers or changing completed evidence',async t=>{
 const f=await fixture(t),b=f.bridge,db=b.controlStore.db,m=f.create();
 b.controlStore.startRun({id:'old-uncertain-run',taskId:m.task_id,missionId:m.id,agentId:'host'});
 const lease=b.controlStore.acquireLease({resource:f.repo,runId:'old-uncertain-run',missionId:m.id});
 db.prepare('UPDATE cp_runs SET agent_id=?,state=?,process_state=? WHERE id=?').run(REMOVED_RUNTIME,'termination_unverified','unknown','old-uncertain-run');
 db.prepare("UPDATE cp_leases SET state='quarantined' WHERE id=?").run(lease);
 db.prepare('UPDATE cp_missions SET state=?,envelope=? WHERE id=?').run('completed',JSON.stringify({...m.envelope,preferred_agent:REMOVED_RUNTIME}),m.id);
 db.prepare("INSERT INTO cp_continuations VALUES('old-continuation','old-decision',?,'queued',?)").run(m.id,Date.now());
 db.prepare("INSERT INTO cp_dispatches VALUES('old-uncertain',?,?,'unknown',NULL,NULL,NULL,?,?)").run(m.id,m.task_id,Date.now(),Date.now());
 await b.missions.tick();await b.missions.tick();
 assert.equal(db.prepare("SELECT state FROM cp_continuations WHERE id='old-continuation'").get().state,'cancelled');
 assert.equal(db.prepare("SELECT state FROM cp_dispatches WHERE id='old-uncertain'").get().state,'unknown');
 assert.equal(b.missions.detail(m.id).state,'completed');assert.equal(db.prepare('SELECT state FROM cp_leases WHERE id=?').get(lease).state,'quarantined');assert.equal(b.controlStore.run('old-uncertain-run').state,'termination_unverified');
});
