'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawnSync}=require('node:child_process');
const {repositorySnapshot:snapshot,manifest,compare,POLICY,resolveGitExecutable}=require('../src/repository-verification');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'repo-v2-')),gitPath=resolveGitExecutable();t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const git=(...a)=>{const r=spawnSync(gitPath,['-C',root,...a],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);return r.stdout};git('init','-q');git('config','user.name','Fixture');git('config','user.email','fixture@example.invalid');fs.writeFileSync(path.join(root,'owned.txt'),'baseline');fs.writeFileSync(path.join(root,'protected.txt'),'protected');git('add','owned.txt','protected.txt');git('commit','-qm','baseline');return{root,git,write:(n,s)=>fs.writeFileSync(path.join(root,n),s)};}
test('macOS Git resolution prefers a direct developer binary over the xcrun shim',()=>{
 if(process.platform!=='darwin')return;
 const direct=[
  '/Applications/Xcode.app/Contents/Developer/usr/bin/git',
  '/Library/Developer/CommandLineTools/usr/bin/git'
 ].find(candidate=>{try{return fs.statSync(fs.realpathSync(candidate)).isFile();}catch{return false;}});
 if(!direct)return;
 assert.equal(resolveGitExecutable(),fs.realpathSync(direct));
 assert.notEqual(resolveGitExecutable(),'/usr/bin/git');
});
test('small repository compatible path and repeated unchanged verification deterministic',t=>{const f=fixture(t),a=snapshot(f.root);assert.equal(a.mode,'legacy-compatible-v2');assert.equal(a.hash,snapshot(f.root).hash);assert.equal(compare(a,snapshot(f.root),['owned.txt']).status,'passed');});
test('allowed tracked change and new path pass with existence fingerprints',t=>{const f=fixture(t),a=snapshot(f.root);manifest(a,['owned.txt','new.txt']);f.write('owned.txt','after');f.write('new.txt','new');const r=compare(a,snapshot(f.root),['owned.txt','new.txt']);assert.equal(r.status,'passed');assert.deepEqual(r.newly_created,['new.txt']);});
for(const [name,mutate]of [['unowned tracked mutation',f=>f.write('protected.txt','mutated')],['unowned new untracked file',f=>f.write('unowned.txt','new')],['protected task definitions',f=>{fs.mkdirSync(path.join(f.root,'.vscode'));f.write('.vscode/tasks.json','{}')}],['index only mutation',f=>f.git('rm','--cached','protected.txt')]])test(name+' fails closed',t=>{const f=fixture(t),a=snapshot(f.root);mutate(f);assert.equal(compare(a,snapshot(f.root),['owned.txt']).status,'failed');});
test('pre-existing unrelated dirty and untracked preserved; their later mutations fail',t=>{const f=fixture(t);f.write('protected.txt','dirty');f.write('existing.txt','untracked');const a=snapshot(f.root);f.write('owned.txt','allowed');assert.equal(compare(a,snapshot(f.root),['owned.txt']).status,'passed');f.write('existing.txt','changed');assert.equal(compare(a,snapshot(f.root),['owned.txt']).status,'failed');assert.throws(()=>manifest(a,['protected.txt']),/dirty/);});
test('symlink escape and parent traversal fail closed',t=>{const f=fixture(t);fs.symlinkSync('/tmp',path.join(f.root,'escape'));assert.throws(()=>snapshot(f.root),/symlink/);fs.unlinkSync(path.join(f.root,'escape'));const a=snapshot(f.root);for(const n of ['../escape','/tmp/escape','a/../escape','a\\escape','a/./escape'])assert.throws(()=>manifest(a,[n]),/path/);fs.symlinkSync('/tmp',path.join(f.root,'parent'));assert.throws(()=>manifest(a,['parent/new.txt']),/symlink/);});
test('case and unicode ambiguity fail closed',t=>{const f=fixture(t),a=snapshot(f.root);assert.throws(()=>manifest(a,['OWNED.txt']),/case/);assert.throws(()=>manifest(a,['e\u0301.txt']),/path/);});
test('delete/recreate same content detected for protected paths',t=>{const f=fixture(t),a=snapshot(f.root);const old=path.join(f.root,'protected.txt');fs.renameSync(old,path.join(f.root,'old.tmp'));f.write('protected.txt','protected');fs.unlinkSync(path.join(f.root,'old.tmp'));assert.equal(compare(a,snapshot(f.root),['owned.txt']).status,'failed');});
test('scope and file-count budgets fail closed',t=>{const f=fixture(t),a=snapshot(f.root);assert.throws(()=>manifest(a,Array.from({length:41},(_,i)=>`new${i}`)),/manifest/);for(let i=0;i<POLICY.maxFiles;i++)f.write('f'+i,'');assert.throws(()=>snapshot(f.root),/budget/);});
test('unexpected HEAD and worktree identity mismatch fail closed',t=>{const f=fixture(t),a=snapshot(f.root);f.git('commit','--allow-empty','-qm','advance');assert.throws(()=>compare(a,snapshot(f.root),['owned.txt']),/identity/);const b=snapshot(f.root);assert.throws(()=>compare(b,{...b,repository:{...b.repository,git_dir:'/different'}},['owned.txt']),/identity/);});
test('restart recovery re-reads manifest; receipt never contains secret file contents',t=>{const f=fixture(t);f.write('private.txt','fixture-secret-never-export');const a=JSON.parse(JSON.stringify(snapshot(f.root))),m=JSON.parse(JSON.stringify(manifest(a,['owned.txt'])));f.write('owned.txt','done');const receipt=compare(a,snapshot(f.root),m.allowed_files);assert.equal(receipt.status,'passed');assert.ok(!JSON.stringify(receipt).includes('fixture-secret-never-export'));assert.ok(!JSON.stringify(a).includes('fixture-secret-never-export'));});
test('444 MiB binary uses streaming V2 without whole-file reads; legacy guard replaced by equivalent evidence',t=>{const f=fixture(t),file=path.join(f.root,'large.bin'),fd=fs.openSync(file,'w');fs.ftruncateSync(fd,444*1024*1024);fs.closeSync(fd);const old=fs.readFileSync;fs.readFileSync=function(p,...args){if(p===file)throw Error('whole-file read forbidden');return old.call(this,p,...args)};try{const a=snapshot(f.root);assert.equal(a.mode,'streaming-v2');assert.equal(a.inventory['large.bin'].digest.length,64);f.write('owned.txt','after');assert.equal(compare(a,snapshot(f.root),['owned.txt']).status,'passed');}finally{fs.readFileSync=old;}});
test('allowed new ignored path remains covered by explicit scope',t=>{const f=fixture(t);f.write('.gitignore','new.txt\n');f.git('add','.gitignore');f.git('commit','-qm','ignore policy');const a=snapshot(f.root);f.write('new.txt','created');assert.throws(()=>compare(a,snapshot(f.root),['new.txt']),/ignored|unobserved/);});
test('aggregate above 64 MiB selects V2 even when individual files fit legacy bound',t=>{const f=fixture(t);for(let i=0;i<5;i++){const fd=fs.openSync(path.join(f.root,'binary'+i),'w');fs.ftruncateSync(fd,15*1024*1024);fs.closeSync(fd);}assert.equal(snapshot(f.root).mode,'streaming-v2');});
test('required missing repository and unknown file types fail closed',t=>{const f=fixture(t);assert.throws(()=>snapshot(path.join(f.root,'missing')));assert.equal(spawnSync('mkfifo',[path.join(f.root,'pipe')]).status,0);assert.throws(()=>manifest(snapshot(f.root),['pipe']),/Unknown/);});
test('pre-existing dirty file with changed staged bytes fails despite same status',t=>{const f=fixture(t);f.write('protected.txt','staged1');f.git('add','protected.txt');f.write('protected.txt','working');const a=snapshot(f.root);f.write('protected.txt','staged2');f.git('add','protected.txt');f.write('protected.txt','working');assert.equal(compare(a,snapshot(f.root),['owned.txt']).status,'failed');});
test('task-owned symlink is refused, duplicate scopes and protected inputs rejected',t=>{const f=fixture(t);fs.symlinkSync('protected.txt',path.join(f.root,'link'));f.git('add','link');f.git('commit','-qm','internal link');const a=snapshot(f.root);assert.throws(()=>manifest(a,['link']),/symlink/);assert.throws(()=>manifest(a,['owned.txt','owned.txt']),/manifest/);assert.throws(()=>manifest(a,['tests/new.txt']),/Protected/);});
test('continuation may retain unchanged earlier task-owned dirty file but cannot overwrite it',t=>{const f=fixture(t);f.write('owned.txt','earlier run');const a=snapshot(f.root);f.write('next.txt','continuation');assert.equal(compare(a,snapshot(f.root),['owned.txt','next.txt']).status,'passed');f.write('owned.txt','overwrite');assert.equal(compare(a,snapshot(f.root),['owned.txt','next.txt']).status,'failed');});
test('original Mission baseline catches unowned changes introduced before run baseline',t=>{const f=fixture(t),creation=snapshot(f.root);f.write('outside.txt','unowned');const run=snapshot(f.root);f.write('owned.txt','allowed');const after=snapshot(f.root);assert.equal(compare(run,after,['owned.txt']).status,'passed');assert.equal(compare(creation,after,['owned.txt']).status,'failed');});
test('immutable creation proves an earlier owned file may be retouched without overwriting or replacing it',t=>{const f=fixture(t),creation=snapshot(f.root);f.write('owned.txt','earlier run');const before=snapshot(f.root);f.write('owned.txt','earlier run');const after=snapshot(f.root);assert.equal(compare(before,after,['owned.txt'],[],{creation}).status,'passed');f.write('owned.txt','new contents');assert.equal(compare(before,snapshot(f.root),['owned.txt'],[],{creation}).status,'failed');});
