'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {resolveSlackCredential,SERVICE,HELPER}=require('../src/slack-credentials');
const options={platform:'darwin',verifyHelper:()=>true};
test('exact allowlist rejects arbitrary and inherited references',async()=>{let calls=0;for(const ref of ['app_token','bot_token','OTHER','toString','__proto__',SERVICE,'SLACK_APP_TOKEN;echo'])assert.equal(await resolveSlackCredential(ref,{...options,execute:()=>calls++}),null);assert.equal(calls,0);});
test('fixed helper receives only account argv and validates classes',async()=>{for(const [ref,account,prefix] of [['SLACK_APP_TOKEN','app_token','xapp-'],['SLACK_BOT_TOKEN','bot_token','xoxb-']]){const buffer=Buffer.from(prefix+'fixture-only');const value=await resolveSlackCredential(ref,{...options,execute:(file,args,opts,cb)=>{assert.equal(file,HELPER);assert.deepEqual(args,['read',account]);assert.equal(opts.timeout,5000);assert.equal(opts.killSignal,'SIGKILL');assert.equal(opts.maxBuffer,8192);assert.equal(opts.encoding,'buffer');assert.deepEqual(opts.env,{PATH:'/usr/bin:/bin'});cb(null,buffer);}});assert.equal(value,prefix+'fixture-only');assert.ok(buffer.every(x=>x===0));}});
test('denial timeout exceptions and malformed output fail closed',async()=>{for(const error of [Error('denied'),Object.assign(Error('timeout'),{killed:true})])assert.equal(await resolveSlackCredential('SLACK_APP_TOKEN',{...options,execute:(_f,_a,_o,cb)=>cb(error,Buffer.from('xapp-fixture-only'))}),null);for(const output of ['xoxb-wrong-class','xapp-invalid\n','xapp-invalid space','', 'xapp-'])assert.equal(await resolveSlackCredential('SLACK_APP_TOKEN',{...options,execute:(_f,_a,_o,cb)=>cb(null,Buffer.from(output))}),null);assert.equal(await resolveSlackCredential('SLACK_APP_TOKEN',{...options,execute:()=>{throw Error('secret-bearing failure');}}),null);});
test('missing unsafe helper and unsupported platform do not execute',async()=>{for(const o of [{verifyHelper:()=>false},{platform:'linux'}])assert.equal(await resolveSlackCredential('SLACK_APP_TOKEN',{...options,...o,execute:()=>assert.fail('must not run')}),null);});
test('migration contains no generic utility fallback and native scope is fixed',()=>{const js=fs.readFileSync(require.resolve('../src/apps/slack-credentials'),'utf8'),c=fs.readFileSync('scripts/macos/slack-keychain-helper.c','utf8');assert.doesNotMatch(js,/\/usr\/bin\/security|find-generic-password/);assert.match(c,/SecKeychainSetUserInteractionAllowed\(approve\)/);assert.match(c,/local\.pi-chatgpt-bridge\.slack\.test/);assert.doesNotMatch(c,/SecKeychainItemSetAccess|SecKeychainAdd|system\(/);});
test('control-plane authorization fixes identity, account and environment and exposes only booleans',async()=>{
 const {authorizeSlackCredential}=require('../src/slack-credentials');let calls=0;
 assert.deepEqual(await authorizeSlackCredential('OTHER',{...options,execute:()=>calls++}),{readable:false,token_class_valid:false,execution_domain:'control_plane_internal'});assert.equal(calls,0);
 const result=await authorizeSlackCredential('SLACK_APP_TOKEN',{...options,execution_domain:'worker',execute:(file,args,opts,cb)=>{assert.equal(file,HELPER);assert.deepEqual(args,['authorize','app_token']);assert.deepEqual(opts.env,{PATH:'/usr/bin:/bin'});cb(null,JSON.stringify({readable:true,token_class_valid:true,status:0,untrusted_extra:'discard'}));}});
 assert.deepEqual(result,{readable:true,token_class_valid:true,execution_domain:'control_plane_internal'});
});
