'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {DatabaseSync}=require('node:sqlite'),{randomUUID,createHash}=require('node:crypto');
const {ControlPlaneStore}=require('../src/control-plane-store'),{EventLedger}=require('../src/event-ledger');
const {SlackGateway,prepareSlackOutboxSchema}=require('../src/slack-gateway');
const identity=require('../src/memory-identity'),content=require('../src/memory-content-erasure'),erasure=require('../src/memory-erasure');
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,DENIED=/identity|migration|unavailable|incomplete|origin|quarantine|scope/i;
function fixture(db){const store=new ControlPlaneStore({db,ledger:new EventLedger(db)}),gateway=new SlackGateway({store,config:{enabled:false}});return{store,gateway};}
function legacy(db,table,anchored=true){const f=fixture(db);if(table==='cp_slack_health_outbox')db.exec('CREATE TABLE cp_slack_health_outbox(id TEXT PRIMARY KEY,mission_id TEXT,kind TEXT NOT NULL,body TEXT NOT NULL,state TEXT NOT NULL,attempts INTEGER NOT NULL,next_at INTEGER NOT NULL,created_at INTEGER NOT NULL,remote_ts TEXT)');prepareSlackOutboxSchema(db,table);const id=createHash('sha256').update(JSON.stringify('fixture personal Slack legacy key')).digest('hex'),mission=randomUUID(),effect=randomUUID();db.prepare(`INSERT INTO ${table}(id,mission_id,kind,body,state,attempts,next_at,created_at,remote_ts) VALUES(?,?,?,?,'queued',0,1,1,NULL)`).run(id,mission,'info',JSON.stringify({channel:'C1',text:'fixture Slack legacy payload'}));if(anchored)db.prepare("INSERT INTO cp_effect_outbox VALUES(?,?,? ,?,?,?,?,'pending',0,1,1,1,NULL,NULL,NULL,NULL)").run(effect,'slack:'+id,'slack_message',id,'slack.notification',JSON.stringify({mission_id:mission}),JSON.stringify({channel:'C1',text:'fixture Slack legacy payload'}));return{...f,id,mission,effect};}
test('new Slack intents dedupe through erasable correlation while their record identities remain opaque',t=>{const db=new DatabaseSync(':memory:');t.after(()=>db.close());const f=fixture(db),mission=randomUUID(),key='fixture personal Slack active key';const id=f.gateway.enqueueIntent('cp_slack_outbox',mission,'info',{channel:'C1',text:'fixture Slack private payload'},key);assert.ok(UUID.test(id));assert.equal(f.gateway.enqueueIntent('cp_slack_outbox',mission,'info',{channel:'C1',text:'changed ignored replay'},key),id);assert.equal(db.prepare('SELECT count(*) n FROM cp_slack_outbox').get().n,1);const marker=erasure.mark(db,{store:'project_v2',identity:mission,scope_hash:erasure.scopeHash([]),action:'operator_erasure'});content.propagate(db,marker);const row=db.prepare('SELECT * FROM cp_slack_outbox').get();assert.equal(row.id,id);assert.equal(row.source_key,null);assert.equal(JSON.stringify(row).includes(key),false);assert.equal(JSON.stringify(row).includes('fixture Slack private payload'),false);});
for(const table of ['cp_slack_outbox','cp_slack_health_outbox']){
 test(`${table} legacy digest requires an independently opaque effect identity`,t=>{const db=new DatabaseSync(':memory:');t.after(()=>db.close());legacy(db,table,false);assert.throws(()=>identity.assertReadable(db),DENIED);assert.throws(()=>identity.migrate(db),DENIED);assert.equal(identity.qualification(db).state,'failed');});
 test(`${table} anchored legacy migration restores one alias-free intent and preserves delivery dedupe`,t=>{const dir=fs.mkdtempSync('/private/tmp/pi-slack-identity-'),source=new DatabaseSync(path.join(dir,'source.sqlite')),f=legacy(source,table);const file=path.join(dir,'recovery.sqlite');source.prepare('VACUUM INTO ?').run(file);const recovery=new DatabaseSync(file);t.after(()=>{recovery.close();source.close();fs.rmSync(dir,{recursive:true,force:true});});identity.migrate(source);identity.migrate(recovery,{sourceDb:source});identity.assertReadable(recovery);const current=source.prepare(`SELECT * FROM ${table}`).get(),restored=recovery.prepare(`SELECT * FROM ${table}`).get();assert.ok(UUID.test(current.id));assert.equal(restored.id,current.id);const effect=recovery.prepare('SELECT * FROM cp_effect_outbox WHERE id=?').get(f.effect);assert.equal(effect.destination_ref,restored.id);assert.equal(effect.event_key,'slack:'+restored.id);for(const {name}of recovery.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").all())for(const row of recovery.prepare('SELECT * FROM "'+name.replaceAll('"','""')+'"').all())for(const value of Object.values(row))if(typeof value==='string')assert.equal(value.includes(f.id),false,'Legacy digest retained in '+name);const store=new ControlPlaneStore({db:recovery,ledger:new EventLedger(recovery)});assert.equal(store.outbox.enqueue({key:'slack:'+restored.id,destination:'slack_message',ref:restored.id,eventType:'slack.notification',correlation:{mission_id:f.mission},payload:JSON.parse(restored.body)}),f.effect);assert.equal(recovery.prepare('SELECT count(*) n FROM cp_effect_outbox').get().n,1);identity.migrate(recovery,{sourceDb:source});assert.equal(recovery.prepare(`SELECT id FROM ${table}`).get().id,restored.id);});
}
test('anchored Slack restore honors newer source erasure after transport correlation is unavailable',t=>{
 const dir=fs.mkdtempSync('/private/tmp/pi-slack-erased-'),source=new DatabaseSync(path.join(dir,'source.sqlite')),f=legacy(source,'cp_slack_outbox');
 source.prepare("UPDATE cp_slack_outbox SET source_key='fixture erased Slack correlation canary'").run();const file=path.join(dir,'recovery.sqlite');source.prepare('VACUUM INTO ?').run(file);const recovery=new DatabaseSync(file);t.after(()=>{recovery.close();source.close();fs.rmSync(dir,{recursive:true,force:true});});
 identity.migrate(source);const marker=erasure.mark(source,{store:'project_v2',identity:f.mission,scope_hash:erasure.scopeHash([]),action:'operator_erasure'});content.propagate(source,marker);
 assert.equal(source.prepare('SELECT destination_type FROM cp_effect_outbox WHERE id=?').get(f.effect).destination_type,'[erased]');
 identity.migrate(recovery,{sourceDb:source});erasure.reconcile(recovery,source);assert.throws(()=>content.assertReadable(recovery),/propagation|incomplete/i);content.propagate(recovery,recovery.prepare("SELECT * FROM memory_erasure_markers WHERE store='project_v2' AND identity=?").get(f.mission));content.assertReadable(recovery);
 const intent=recovery.prepare('SELECT * FROM cp_slack_outbox').get(),effect=recovery.prepare('SELECT * FROM cp_effect_outbox WHERE id=?').get(f.effect);assert.ok(UUID.test(intent.id));assert.equal(intent.source_key,null);assert.equal(intent.body,'[erased]');assert.equal(effect.destination_type,'[erased]');assert.equal(effect.destination_ref,'[erased]');assert.equal(JSON.parse(effect.correlation).content_state,'erased');assert.equal(JSON.parse(effect.payload).content_state,'erased');
 for(const {name}of recovery.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").all())for(const row of recovery.prepare('SELECT * FROM "'+name.replaceAll('"','""')+'"').all())for(const value of Object.values(row))if(typeof value==='string')assert.equal([f.id,'fixture erased Slack correlation canary','fixture Slack legacy payload'].some(v=>value.includes(v)),false,'Erased Slack value retained in '+name);
});
