'use strict';
const { transaction } = require('./control-transaction');
const VERSION = 1;
const SCHEMA = `
CREATE TABLE authority_meta(id INTEGER PRIMARY KEY CHECK(id=1),version INTEGER NOT NULL,migrated_at INTEGER NOT NULL);
CREATE TABLE authority_projects(id TEXT PRIMARY KEY,slug TEXT UNIQUE,name TEXT NOT NULL,status TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE authority_goals(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES authority_projects(id),parent_goal_id TEXT REFERENCES authority_goals(id),title TEXT NOT NULL,description TEXT NOT NULL,status TEXT NOT NULL,revision INTEGER NOT NULL CHECK(revision>0),created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,UNIQUE(id,project_id));
CREATE TABLE authority_missions(id TEXT PRIMARY KEY,project_id TEXT REFERENCES authority_projects(id),goal_id TEXT,task_id TEXT UNIQUE,owner TEXT NOT NULL,current_revision INTEGER NOT NULL,current_state TEXT NOT NULL,acceptance_strength TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,FOREIGN KEY(goal_id,project_id) REFERENCES authority_goals(id,project_id),FOREIGN KEY(id,current_revision) REFERENCES authority_mission_revisions(mission_id,revision) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE authority_mission_revisions(mission_id TEXT NOT NULL REFERENCES authority_missions(id),revision INTEGER NOT NULL CHECK(revision>0),objective TEXT NOT NULL,task_type TEXT NOT NULL,envelope_json TEXT NOT NULL CHECK(json_valid(envelope_json)),workspace_descriptor_json TEXT NOT NULL,context_manifest_json TEXT NOT NULL,routing_policy_json TEXT NOT NULL,requested_capabilities_json TEXT NOT NULL,constraints_json TEXT NOT NULL,policy_version TEXT NOT NULL,checkpoint_id TEXT,created_by_actor_type TEXT NOT NULL,created_by_actor_id TEXT NOT NULL,created_at INTEGER NOT NULL,content_hash TEXT NOT NULL CHECK(length(content_hash)=64),binding_quality TEXT NOT NULL CHECK(binding_quality IN ('exact','legacy_snapshot')),PRIMARY KEY(mission_id,revision));
CREATE TABLE authority_acceptance_criteria(id TEXT PRIMARY KEY,mission_id TEXT NOT NULL,mission_revision INTEGER NOT NULL,criterion_key TEXT NOT NULL,criterion_type TEXT NOT NULL,description TEXT NOT NULL,verification_method TEXT NOT NULL,target_hash TEXT,required INTEGER NOT NULL CHECK(required IN (0,1)),created_at INTEGER NOT NULL,FOREIGN KEY(mission_id,mission_revision) REFERENCES authority_mission_revisions(mission_id,revision),UNIQUE(mission_id,mission_revision,criterion_key),UNIQUE(id,mission_id,mission_revision));
CREATE TABLE authority_runtime_registry(id TEXT PRIMARY KEY,agent_id TEXT NOT NULL,adapter_type TEXT NOT NULL,display_name TEXT NOT NULL,enabled INTEGER NOT NULL CHECK(enabled IN(0,1)),assurance_tier INTEGER NOT NULL,configuration_version TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE authority_model_registry(id TEXT PRIMARY KEY,provider_id TEXT NOT NULL,model_id TEXT NOT NULL,profile_json TEXT NOT NULL CHECK(json_valid(profile_json)),enabled INTEGER NOT NULL CHECK(enabled IN(0,1)),created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,UNIQUE(provider_id,model_id));
CREATE TABLE authority_runtime_instances(id TEXT PRIMARY KEY,runtime_registry_id TEXT NOT NULL REFERENCES authority_runtime_registry(id),external_runtime_id TEXT,status TEXT NOT NULL,sandbox_id TEXT,started_at INTEGER NOT NULL,last_heartbeat_at INTEGER,ended_at INTEGER,metadata_json TEXT NOT NULL CHECK(json_valid(metadata_json)));
CREATE TABLE authority_runtime_capability_observations(id TEXT PRIMARY KEY,runtime_registry_id TEXT NOT NULL REFERENCES authority_runtime_registry(id),model_registry_id TEXT REFERENCES authority_model_registry(id),capability_key TEXT NOT NULL,declared_level TEXT,observed_success_rate REAL,observed_failure_rate REAL,sample_count INTEGER NOT NULL CHECK(sample_count>=0),p50_latency_ms REAL,p95_latency_ms REAL,evaluated_at INTEGER NOT NULL,evidence_ref TEXT);
CREATE TABLE authority_runs(id TEXT PRIMARY KEY,mission_id TEXT NOT NULL,mission_revision INTEGER NOT NULL,task_id TEXT,agent_id TEXT NOT NULL,runtime_instance_id TEXT NOT NULL REFERENCES authority_runtime_instances(id),model_registry_id TEXT REFERENCES authority_model_registry(id),provider_id TEXT,status TEXT NOT NULL,started_at INTEGER NOT NULL,finished_at INTEGER,checkpoint_started_from TEXT,checkpoint_finished_at TEXT,failure_kind TEXT,failure_detail_json TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,FOREIGN KEY(mission_id,mission_revision) REFERENCES authority_mission_revisions(mission_id,revision),UNIQUE(id,mission_id,mission_revision));
CREATE TABLE authority_execution_grants(id TEXT PRIMARY KEY,mission_id TEXT NOT NULL,mission_revision INTEGER NOT NULL,run_id TEXT NOT NULL,issued_by TEXT NOT NULL,policy_version TEXT NOT NULL,issued_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,revoked_at INTEGER,signature_reference TEXT NOT NULL,content_hash TEXT NOT NULL,FOREIGN KEY(run_id,mission_id,mission_revision) REFERENCES authority_runs(id,mission_id,mission_revision),UNIQUE(id,run_id,mission_id,mission_revision),UNIQUE(id,run_id),CHECK(expires_at>issued_at));
CREATE TABLE authority_execution_grant_capabilities(grant_id TEXT NOT NULL REFERENCES authority_execution_grants(id),capability TEXT NOT NULL CHECK(capability<>'unrestricted'),scope_json TEXT NOT NULL CHECK(json_valid(scope_json)),PRIMARY KEY(grant_id,capability,scope_json));
CREATE TABLE authority_consumed_nonces(grant_id TEXT NOT NULL,nonce TEXT NOT NULL,run_id TEXT NOT NULL,request_hash TEXT NOT NULL,consumed_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,PRIMARY KEY(grant_id,nonce),FOREIGN KEY(grant_id,run_id) REFERENCES authority_execution_grants(id,run_id));
CREATE TABLE authority_ledger_entries(project_id TEXT NOT NULL REFERENCES authority_projects(id),sequence INTEGER NOT NULL CHECK(sequence>0),entry_id TEXT NOT NULL UNIQUE,mission_id TEXT,mission_revision INTEGER,run_id TEXT,kind TEXT NOT NULL,actor_type TEXT NOT NULL,actor_id TEXT NOT NULL,payload_json TEXT NOT NULL CHECK(json_valid(payload_json)),previous_hash TEXT NOT NULL CHECK(length(previous_hash)=64),entry_hash TEXT NOT NULL UNIQUE CHECK(length(entry_hash)=64),timestamp INTEGER NOT NULL,PRIMARY KEY(project_id,sequence),FOREIGN KEY(mission_id,mission_revision) REFERENCES authority_mission_revisions(mission_id,revision));
CREATE TABLE authority_ledger_heads(project_id TEXT PRIMARY KEY REFERENCES authority_projects(id),sequence INTEGER NOT NULL,entry_hash TEXT NOT NULL);
CREATE TABLE authority_grant_revocations(grant_id TEXT PRIMARY KEY REFERENCES authority_execution_grants(id),revoked_at INTEGER NOT NULL,reason TEXT NOT NULL);
CREATE TABLE authority_checkpoints(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES authority_projects(id),mission_id TEXT NOT NULL,mission_revision INTEGER NOT NULL,run_id TEXT,ledger_cursor INTEGER NOT NULL,authority_projection_hash TEXT NOT NULL,workspace_snapshot_hash TEXT NOT NULL,artifact_manifest_hash TEXT NOT NULL,context_pack_hash TEXT NOT NULL,created_at INTEGER NOT NULL,created_by_actor_type TEXT NOT NULL,created_by_actor_id TEXT NOT NULL,FOREIGN KEY(mission_id,mission_revision) REFERENCES authority_mission_revisions(mission_id,revision),FOREIGN KEY(run_id,mission_id,mission_revision) REFERENCES authority_runs(id,mission_id,mission_revision));
CREATE TABLE authority_results(id TEXT PRIMARY KEY,mission_id TEXT NOT NULL,mission_revision INTEGER NOT NULL,run_id TEXT NOT NULL REFERENCES authority_runs(id),runtime_registry_id TEXT NOT NULL REFERENCES authority_runtime_registry(id),model_registry_id TEXT REFERENCES authority_model_registry(id),status TEXT NOT NULL CHECK(status IN('completed','partial','blocked','failed')),summary TEXT NOT NULL,checkpoint_id TEXT REFERENCES authority_checkpoints(id),content_hash TEXT NOT NULL,runtime_signature TEXT,created_at INTEGER NOT NULL,result_json TEXT NOT NULL CHECK(json_valid(result_json)),FOREIGN KEY(run_id,mission_id,mission_revision) REFERENCES authority_runs(id,mission_id,mission_revision),UNIQUE(id,mission_id,mission_revision));
CREATE TABLE authority_evidence_records(id TEXT PRIMARY KEY,project_id TEXT REFERENCES authority_projects(id),mission_id TEXT NOT NULL,mission_revision INTEGER NOT NULL,run_id TEXT NOT NULL,grant_id TEXT,sandbox_id TEXT,kind TEXT NOT NULL,claim TEXT NOT NULL,source_type TEXT NOT NULL,request_hash TEXT,execution_hash TEXT,stdout_hash TEXT,stderr_hash TEXT,artifact_hash TEXT,command_hash TEXT,metadata_json TEXT NOT NULL CHECK(json_valid(metadata_json)),observed_at INTEGER NOT NULL,created_at INTEGER NOT NULL,FOREIGN KEY(run_id,mission_id,mission_revision) REFERENCES authority_runs(id,mission_id,mission_revision),FOREIGN KEY(grant_id,run_id,mission_id,mission_revision) REFERENCES authority_execution_grants(id,run_id,mission_id,mission_revision),UNIQUE(id,mission_id,mission_revision));
CREATE TABLE authority_test_evidence(evidence_id TEXT PRIMARY KEY REFERENCES authority_evidence_records(id),suite_name TEXT NOT NULL,command_hash TEXT,exit_code INTEGER,passed INTEGER NOT NULL CHECK(passed IN(0,1)),duration_ms INTEGER,raw_output_hash TEXT);
CREATE TABLE authority_artifact_evidence(evidence_id TEXT NOT NULL REFERENCES authority_evidence_records(id),path TEXT NOT NULL,change_type TEXT NOT NULL,pre_hash TEXT,post_hash TEXT,PRIMARY KEY(evidence_id,path));
CREATE TABLE authority_verification_records(id TEXT PRIMARY KEY,mission_id TEXT NOT NULL,mission_revision INTEGER NOT NULL,result_id TEXT NOT NULL,verification_policy_version TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN('pending','running','passed','failed','operator_review','unavailable')),verifier_type TEXT NOT NULL,verifier_id TEXT NOT NULL,started_at INTEGER NOT NULL,completed_at INTEGER,summary TEXT,evidence_manifest_hash TEXT,created_at INTEGER NOT NULL,FOREIGN KEY(result_id,mission_id,mission_revision) REFERENCES authority_results(id,mission_id,mission_revision),UNIQUE(id,mission_id,mission_revision));
CREATE TABLE authority_verification_evidence(verification_id TEXT NOT NULL REFERENCES authority_verification_records(id),evidence_id TEXT NOT NULL REFERENCES authority_evidence_records(id),ordinal INTEGER NOT NULL,PRIMARY KEY(verification_id,evidence_id),UNIQUE(verification_id,ordinal));
CREATE TABLE authority_criterion_verifications(verification_id TEXT NOT NULL,criterion_id TEXT NOT NULL,mission_id TEXT NOT NULL,mission_revision INTEGER NOT NULL,status TEXT NOT NULL CHECK(status IN('passed','failed','operator_review','unavailable')),evidence_refs_json TEXT NOT NULL CHECK(json_valid(evidence_refs_json)),reason TEXT,PRIMARY KEY(verification_id,criterion_id),FOREIGN KEY(verification_id,mission_id,mission_revision) REFERENCES authority_verification_records(id,mission_id,mission_revision),FOREIGN KEY(criterion_id,mission_id,mission_revision) REFERENCES authority_acceptance_criteria(id,mission_id,mission_revision));
CREATE TABLE authority_acceptance_records(id TEXT PRIMARY KEY,mission_id TEXT NOT NULL,mission_revision INTEGER NOT NULL,verification_id TEXT,decision TEXT NOT NULL CHECK(decision IN('accepted','rework_requested','rejected','stopped')),actor_type TEXT NOT NULL CHECK(actor_type IN('operator','host_policy')),actor_id TEXT NOT NULL,reason TEXT NOT NULL,review_evidence_json TEXT NOT NULL CHECK(json_valid(review_evidence_json)),created_at INTEGER NOT NULL,FOREIGN KEY(mission_id,mission_revision) REFERENCES authority_mission_revisions(mission_id,revision),FOREIGN KEY(verification_id,mission_id,mission_revision) REFERENCES authority_verification_records(id,mission_id,mission_revision));
CREATE TABLE authority_observations(id TEXT PRIMARY KEY,operator_id TEXT NOT NULL,session_id TEXT NOT NULL,chunk_id TEXT NOT NULL,speaker TEXT NOT NULL CHECK(speaker IN('operator','agent','provider')),observed_at INTEGER NOT NULL,claim TEXT NOT NULL,source_hash TEXT NOT NULL,created_at INTEGER NOT NULL,UNIQUE(operator_id,session_id,chunk_id));
CREATE TABLE authority_memory_candidates(id TEXT PRIMARY KEY,project_id TEXT REFERENCES authority_projects(id),mission_id TEXT REFERENCES authority_missions(id),run_id TEXT,observation_id TEXT REFERENCES authority_observations(id),kind TEXT NOT NULL CHECK(kind IN('architecture','project_operational','personal_preference','mission_episodic')),operator_id TEXT NOT NULL,scope TEXT NOT NULL CHECK(scope IN('global','project_specific')),subject_key TEXT NOT NULL,value_json TEXT NOT NULL CHECK(json_valid(value_json)),source_hash TEXT NOT NULL,source_refs_json TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN('candidate','rejected','promoted')),promoted_memory_id TEXT REFERENCES authority_memories(id),proposed_by_actor_type TEXT NOT NULL,proposed_by_actor_id TEXT NOT NULL,reviewed_by_actor_type TEXT,reviewed_by_actor_id TEXT,created_at INTEGER NOT NULL,reviewed_at INTEGER,metadata_json TEXT NOT NULL CHECK(json_valid(metadata_json)),CHECK(scope<>'project_specific' OR project_id IS NOT NULL));
CREATE TABLE authority_memories(id TEXT PRIMARY KEY,kind TEXT NOT NULL CHECK(kind IN('architecture','project_operational','personal_preference','mission_episodic')),project_id TEXT REFERENCES authority_projects(id),operator_id TEXT NOT NULL,scope TEXT NOT NULL CHECK(scope IN('global','project_specific')),subject_key TEXT NOT NULL,value_json TEXT NOT NULL CHECK(json_valid(value_json)),source_type TEXT NOT NULL,source_hash TEXT NOT NULL,source_refs_json TEXT NOT NULL,candidate_id TEXT UNIQUE REFERENCES authority_memory_candidates(id),assurance INTEGER NOT NULL CHECK(assurance BETWEEN 0 AND 3),privacy TEXT NOT NULL CHECK(privacy IN('public','internal','restricted_security')),status TEXT NOT NULL CHECK(status IN('active','superseded','forgotten','expired')),revision INTEGER NOT NULL CHECK(revision>0),effective_from INTEGER NOT NULL,effective_until INTEGER,last_verified_at INTEGER,ttl_ms INTEGER,expires_at INTEGER,reverify_task_classes_json TEXT NOT NULL,domains_json TEXT NOT NULL,canonical_priority INTEGER NOT NULL,supersedes_id TEXT REFERENCES authority_memories(id),superseded_by_id TEXT REFERENCES authority_memories(id),created_by_actor_type TEXT NOT NULL,created_by_actor_id TEXT NOT NULL,approved_by_actor_type TEXT NOT NULL,approved_by_actor_id TEXT NOT NULL,created_at INTEGER NOT NULL,content_hash TEXT NOT NULL,metadata_json TEXT NOT NULL CHECK(json_valid(metadata_json)),CHECK(scope<>'project_specific' OR project_id IS NOT NULL));
CREATE INDEX authority_memory_scope ON authority_memories(operator_id,project_id,scope,status,subject_key);
CREATE UNIQUE INDEX authority_one_active_memory ON authority_memories(kind,operator_id,COALESCE(project_id,''),scope,subject_key) WHERE status='active';
CREATE TABLE authority_memory_conflicts(id TEXT PRIMARY KEY,project_id TEXT REFERENCES authority_projects(id),operator_id TEXT NOT NULL,subject_key TEXT NOT NULL,memory_ids_json TEXT NOT NULL,candidate_ids_json TEXT NOT NULL,affected_domains_json TEXT NOT NULL,resolution_required INTEGER NOT NULL CHECK(resolution_required IN(0,1)),created_at INTEGER NOT NULL,resolved_at INTEGER,resolution_json TEXT);
CREATE TABLE authority_context_pack_manifests(id TEXT PRIMARY KEY,project_id TEXT REFERENCES authority_projects(id),mission_id TEXT REFERENCES authority_missions(id),mission_revision INTEGER,task_id TEXT,run_id TEXT,operator_id TEXT NOT NULL,privacy TEXT NOT NULL,retrieval_policy_version TEXT NOT NULL,context_hash TEXT NOT NULL,manifest_json TEXT NOT NULL CHECK(json_valid(manifest_json)),created_at INTEGER NOT NULL,FOREIGN KEY(mission_id,mission_revision) REFERENCES authority_mission_revisions(mission_id,revision));
CREATE TABLE authority_context_pack_items(context_pack_id TEXT NOT NULL REFERENCES authority_context_pack_manifests(id),ordinal INTEGER NOT NULL,memory_id TEXT NOT NULL REFERENCES authority_memories(id),snapshot_json TEXT NOT NULL CHECK(json_valid(snapshot_json)),PRIMARY KEY(context_pack_id,ordinal),UNIQUE(context_pack_id,memory_id));
CREATE TABLE authority_context_pack_diffs(id TEXT PRIMARY KEY,from_pack_id TEXT NOT NULL REFERENCES authority_context_pack_manifests(id),to_pack_id TEXT NOT NULL REFERENCES authority_context_pack_manifests(id),diff_json TEXT NOT NULL CHECK(json_valid(diff_json)),content_hash TEXT NOT NULL,created_at INTEGER NOT NULL,UNIQUE(from_pack_id,to_pack_id));
CREATE TABLE authority_routing_policy_versions(id TEXT PRIMARY KEY,project_id TEXT REFERENCES authority_projects(id),version INTEGER NOT NULL,policy_json TEXT NOT NULL CHECK(json_valid(policy_json)),content_hash TEXT NOT NULL,active INTEGER NOT NULL CHECK(active IN(0,1)),created_at INTEGER NOT NULL);
CREATE TABLE authority_routing_decisions(id TEXT PRIMARY KEY,mission_id TEXT REFERENCES authority_missions(id),mission_revision INTEGER,context_pack_id TEXT REFERENCES authority_context_pack_manifests(id),policy_id TEXT NOT NULL REFERENCES authority_routing_policy_versions(id),state TEXT NOT NULL CHECK(state IN('selected','WAIT')),selected_agent TEXT,selected_provider TEXT,selected_model TEXT,input_json TEXT NOT NULL,decision_json TEXT NOT NULL,audit_hash TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE authority_routing_candidates(decision_id TEXT NOT NULL REFERENCES authority_routing_decisions(id),candidate_key TEXT NOT NULL,eligible INTEGER NOT NULL CHECK(eligible IN(0,1)),rank_json TEXT NOT NULL,PRIMARY KEY(decision_id,candidate_key));
CREATE TABLE authority_routing_rejections(decision_id TEXT NOT NULL,candidate_key TEXT NOT NULL,gate INTEGER NOT NULL,reason TEXT NOT NULL,PRIMARY KEY(decision_id,candidate_key,gate),FOREIGN KEY(decision_id,candidate_key) REFERENCES authority_routing_candidates(decision_id,candidate_key));
CREATE TABLE authority_outbox_events(id TEXT PRIMARY KEY,project_id TEXT REFERENCES authority_projects(id),mission_id TEXT REFERENCES authority_missions(id),event_type TEXT NOT NULL,payload_json TEXT NOT NULL,content_hash TEXT NOT NULL,created_at INTEGER NOT NULL,published_at INTEGER,attempt_count INTEGER NOT NULL DEFAULT 0,last_error TEXT);
CREATE TABLE authority_legacy_records(source_table TEXT NOT NULL,source_id TEXT NOT NULL,source_hash TEXT NOT NULL,record_json TEXT NOT NULL,canonical_id TEXT,binding_quality TEXT NOT NULL CHECK(binding_quality IN('exact','legacy_snapshot','unresolved','provenance_only')),PRIMARY KEY(source_table,source_id));
CREATE TABLE authority_activation(id INTEGER PRIMARY KEY CHECK(id=1),memory_state TEXT NOT NULL CHECK(memory_state IN('disabled','qualifying','enabled')),router_state TEXT NOT NULL CHECK(router_state IN('disabled','qualifying','enabled')),source_hash TEXT,memory_receipt_id TEXT,router_receipt_id TEXT,updated_at INTEGER NOT NULL);
INSERT INTO authority_activation VALUES(1,'disabled','disabled',NULL,NULL,NULL,0);
CREATE TABLE authority_qualification_receipts(id TEXT PRIMARY KEY,kind TEXT NOT NULL CHECK(kind IN('memory','router')),source_hash TEXT NOT NULL,schema_version INTEGER NOT NULL,policy_version TEXT NOT NULL,evidence_json TEXT NOT NULL,evidence_hash TEXT NOT NULL,created_at INTEGER NOT NULL);
`;
const IMMUTABLE = ['mission_revisions','acceptance_criteria','execution_grants','execution_grant_capabilities','grant_revocations','consumed_nonces','ledger_entries','checkpoints','results','verification_records','verification_evidence','evidence_records','test_evidence','artifact_evidence','criterion_verifications','acceptance_records','observations','context_pack_manifests','context_pack_items','context_pack_diffs','routing_decisions','routing_candidates','routing_rejections','legacy_records','qualification_receipts'];
function migrateAuthority(db, now = Date.now()) {
  db.exec('PRAGMA foreign_keys=ON');
  if (db.prepare('PRAGMA foreign_keys').get().foreign_keys !== 1) throw new Error('Authority foreign keys must be enabled before a transaction');
  const exists = db.prepare("SELECT 1 FROM sqlite_master WHERE name='authority_meta'").get();
  if (exists) {
    if (db.prepare('SELECT version FROM authority_meta WHERE id=1').get()?.version !== VERSION) throw new Error('Unsupported authority schema');
    return false;
  }
  return transaction(db, () => {
    db.exec(SCHEMA);
    for (const name of IMMUTABLE) for (const op of ['UPDATE','DELETE']) db.exec(`CREATE TRIGGER authority_${name}_${op.toLowerCase()} BEFORE ${op} ON authority_${name} BEGIN SELECT RAISE(ABORT,'Immutable authority record'); END;`);
    for (const kind of ['architecture','project_operational','personal_preference','mission_episodic']) db.exec(`CREATE VIEW authority_${kind}_memory AS SELECT * FROM authority_memories WHERE kind='${kind}';`);
    db.prepare('INSERT INTO authority_meta VALUES(1,?,?)').run(VERSION,now);
    return true;
  });
}
module.exports = { migrateAuthority, VERSION };
