'use strict';
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const { randomBytes, randomUUID, timingSafeEqual } = require('node:crypto');
const { readJSON } = require('./bridge-controller');
const { McpTools } = require('./mcp-tools');
const { atomicJSON } = require('./config');
const { controlPlaneRead, controlPlaneWrite } = require('./control-plane-api');

// Keep the operator's private launch link valid across local service restarts.
// MCP credentials remain separate and retain their existing lifecycle.
function operatorToken(dataDir) {
  const file = path.join(dataDir, 'control-credential.json');
  if (require('./private-json').privateFileExists(file)) {
    const { token } = require('./private-json').readPrivateJSON(file);
    if (!/^[a-f0-9]{64}$/.test(token)) throw new Error('Invalid Control Center credential');
    return token;
  }
  let token;
  // An existing unsafe discovery file is an error, never a source of credentials.
  const discovery = path.join(dataDir, 'ui.json');
  if (require('./private-json').privateFileExists(discovery)) {
    const { url } = require('./private-json').readPrivateJSON(discovery);
    token = /^http:\/\/127\.0\.0\.1:\d+\/#token=([a-f0-9]{64})$/.exec(url)?.[1];
    if (!token) throw new Error('Invalid Control Center discovery');
  }
  token ||= randomBytes(32).toString('hex');
  atomicJSON(file, { token });
  return token;
}


class ControlServer {
  constructor(bridge, { port = 43117, token, mcpToken = randomBytes(32).toString('hex'), connectionStatus = require('./chatgpt-connection').chatgptConnection } = {}) {
    if (!Number.isInteger(port) || port < 0 || port > 65535) throw new Error('Invalid local port');
    this.bridge = bridge; this.port = port; this.token = token ?? operatorToken(bridge.dataDir); this.webRequests = new Map();
    const gmailFile=bridge.dataDir?path.join(bridge.dataDir,'gmail-oauth-config.json'):null;
    if(gmailFile&&require('./private-json').privateFileExists(gmailFile)){
      const config=require('./private-json').readPrivateJSON(gmailFile);require('./control-plane-store').object(config,['clientId','reference']);
      this.gmailOAuth=new(require('./gmail-oauth').GmailOAuth)({clientId:config.clientId,reference:config.reference||null,vault:new(require('./secret-vault').SecretVault)(bridge.dataDir),onReference:reference=>{require('./local-bootstrap').writePrivate(gmailFile,{clientId:config.clientId,reference});bridge.assistantConnectors=new(require('./assistant-connectors').AssistantConnectors)({gmail:this.gmailOAuth.configuration(),secrets:{resolve:()=>this.gmailOAuth.resolve()}});}});
      if(config.reference)bridge.assistantConnectors=new(require('./assistant-connectors').AssistantConnectors)({gmail:this.gmailOAuth.configuration(),secrets:{resolve:()=>this.gmailOAuth.resolve()}});
    }
    this.mcpToken = mcpToken;
    this.connectionStatus = connectionStatus;
    // The epoch is generated by the authenticated loopback endpoint, never by
    // MCP client metadata. A task bound to a previous bridge instance cannot
    // later be granted or continued by a fresh connection.
    this.mcpConnectionEpoch = randomBytes(32).toString('hex'); this.mcpSessions=new Map(); this.bridge.controlStore?.db?.exec('CREATE TABLE IF NOT EXISTS cp_mcp_handoff_sessions(id TEXT PRIMARY KEY,created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL)');
    this.mcp = new McpTools(bridge, { origin: () => this.origin, authenticatedConnection: () => ({ epoch: this.mcpConnectionEpoch, authenticatedAt: Date.now() }) }); this.lastMcpCallAt = null;
    this.server = http.createServer({ maxHeaderSize: 16384 }, (req, res) => this.handle(req, res));
    this.server.requestTimeout = 15000; this.server.headersTimeout = 10000;
    this.server.on('clientError', (_error, socket) => socket.end('HTTP/1.1 400 Bad Request\r\nConnection: close\r\n\r\n'));
  }
  async start() {
    await new Promise((resolve, reject) => { this.server.once('error', reject); this.server.listen(this.port, '127.0.0.1', resolve); });
    this.port = this.server.address().port; this.origin = `http://127.0.0.1:${this.port}`;
    return { url: `${this.origin}/#token=${this.token}`, port: this.port };
  }
  json(res, status, data) { res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8' }); res.end(JSON.stringify(require('./secret-observation').safeValue(data))); }
  authorize(req, token = this.token) {
    const provided = Buffer.from(req.headers.authorization || '');
    const expected = Buffer.from(`Bearer ${token}`);
    return provided.length === expected.length && timingSafeEqual(provided, expected);
  }
  assertCanRun(id) {
    const task = this.bridge.tasks.get(id);
    if (this.bridge.leases?.size || this.bridge.inFlight.size) {
      throw new Error(this.bridge.leases?.busyAdmissionError?.() || 'A task is still running; wait or cancel it first');
    }
    return task;
  }
  interactiveMemory(query = '') {
    const b = this.bridge;
    if (b.authorityRuntime?.active) {
      const result = b.authorityRuntime.memoryItems({ domain: 'personal', query, limit: 20 });
      const terms = query.toLowerCase().match(/[\p{L}\p{N}_]+/gu) || [];
      return { ...result, items: result.items.filter(m => !terms.length || terms.every(term => (m.subject + ' ' + m.content).toLowerCase().includes(term))) };
    }
    return query ? b.personalMemory.search(query, { domain: 'personal', limit: 20, includeSensitive: false }) : b.personalMemory.recent({ domain: 'personal', limit: 20, includeSensitive: false });
  }
  interactiveTask(id) {
    const m = this.bridge.controlStore.requireMission(id), task = this.bridge.tasks.get(m.task_id);
    const v = this.bridge.controlStore.db.prepare('SELECT id FROM cp_verifications WHERE mission_id=? ORDER BY created_at DESC LIMIT 1').get(id);
    let summary = task.lastResult;
    if (task.contextPackId) { try { this.bridge.opencodeAdapter.authorizedContext({ id: task.contextPackId }); } catch { summary = 'Memory context changed; create a fresh task.'; } }
    return { mission_id: id, task_id: task.id, state: m.state, reason: m.reason, runtime: m.envelope.preferred_agent, summary: summary || 'No result yet.', verification_id: v?.id || null, accepted: m.state === 'completed' };
  }
  rememberInteractive(content) {
    require('./control-plane-store').text(content, 'memory content', 2000);
    if(require('./assistant-intent').secret(content))throw Error('Secret content requires the Secret Vault secure input path.');
    if(require('./assistant-intent').sensitive(content))throw Error('Explicit Sensitive Memory command required.');
    const subject = require('./conversation-mission').subjectFor(content);
    const same = this.interactiveMemory(subject).items.filter(m => m.subject === subject);
    if (same.length > 1) throw Error('Memory subject is ambiguous; correct an explicit memory ID.');
    return same.length ? this.bridge.updatePersonalMemory(same[0].memoryId, { content }) : this.bridge.rememberPersonalMemory({ domain: 'personal', type: 'fact', subject, content, source: 'user_explicit', sensitivity: 'normal' });
  }
  status() {
    const tasks = this.bridge.tasks.list().map(task => this.bridge.snapshotTask(task)), counts = {};
    const statuses = new Set(['idle', 'running', 'starting', 'thinking', 'running_tool', 'compacting', 'approval_required', 'blocked', 'paused', 'completed', 'cancelled', 'error', 'interrupted', 'awaiting_operator_grant', 'awaiting_mcp_continuation']);
    let lastActivityAt = null, lastHeartbeatAt = null, connected = 0;
    for (const task of tasks) {
      // Only fixed status labels and measurements enter the menu helper response.
      // Task descriptions, model output and errors stay private.
      const status = statuses.has(task.status) ? task.status : 'unknown';
      counts[status] = (counts[status] || 0) + 1;
      if (task.connected === true) connected++;
      if (Number.isFinite(task.lastActivityAt) && task.lastActivityAt > 0) lastActivityAt = Math.max(lastActivityAt || 0, task.lastActivityAt);
      if (Number.isFinite(task.lastHeartbeatAt) && task.lastHeartbeatAt > 0) lastHeartbeatAt = Math.max(lastHeartbeatAt || 0, task.lastHeartbeatAt);
    }
    const execution = this.bridge.leases?.executionSnapshot?.() || null;
    return {
      pid: process.pid, now: Date.now(), healthy: !this.bridge.closed,
      mcp: { ready: !this.bridge.closed, lastCallAt: this.lastMcpCallAt },
      tasks: { active: this.bridge.leases?.size ?? this.bridge.inFlight.size, connected, total: tasks.length, counts },
      execution,
      lastActivityAt, lastHeartbeatAt
    };
  }
  async handle(req, res) {
    const headers = { 'Cache-Control': 'no-store', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'Referrer-Policy': 'no-referrer', 'Content-Security-Policy': "default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self'; img-src 'self' data:; frame-ancestors 'none'; base-uri 'none'; object-src 'none'; form-action 'self'" };
    for (const [key, value] of Object.entries(headers)) res.setHeader(key, value);
    try {
      const callbackPath=new URL(req.url,this.origin).pathname==='/oauth/gmail/callback'&&req.method==='GET';
      if (req.headers.host !== `127.0.0.1:${this.port}` || !callbackPath&&((req.headers.origin && req.headers.origin !== this.origin) || req.headers['sec-fetch-site'] === 'cross-site')) return this.json(res, 403, { error: 'Local same-origin requests only' });
      const url = new URL(req.url, this.origin);
      if(url.pathname==='/oauth/gmail/callback'){
        if(req.method!=='GET'||!this.gmailOAuth)throw Error('OAuth callback unavailable');
        await this.gmailOAuth.complete({state:url.searchParams.get('state'),code:url.searchParams.get('code')});
        res.setHeader('Content-Type','text/plain; charset=utf-8');res.end('Gmail read-only authorization completed. Close this tab and return to Airodrom.');return;
      }
      if (!url.pathname.startsWith('/api/')) {
        const assets = { '/branding.js': ['branding.js','text/javascript; charset=utf-8'], '/hub': ['control-hub.html','text/html; charset=utf-8'], '/control-hub.js': ['control-hub.js','text/javascript; charset=utf-8'], '/control-hub.css': ['control-hub.css','text/css; charset=utf-8'], '/workspace': ['index.html','text/html; charset=utf-8'], '/app.js': ['app.js','text/javascript; charset=utf-8'], '/style.css': ['style.css','text/css; charset=utf-8'] };
        assets['/'] = ['control-hub.html','text/html; charset=utf-8'];
        for (const file of ['airodrom-mark.svg','airodrom-logo-horizontal-dark.svg','airodrom-3d-model-blue.svg']) assets['/brand/'+file]=['brand/'+file,'image/svg+xml'];
        const asset = assets[url.pathname];
        if (req.method !== 'GET' || !asset) return this.json(res, 404, { error: 'Not found' });
        res.setHeader('Content-Type', asset[1]); res.end(fs.readFileSync(path.join(__dirname, '../public', asset[0]))); return;
      }
      // MCP has its own restricted credential. It cannot call the operator approval,
      // memory, web, or broad state APIs even if a client bypasses the stdio shim.
      if (url.pathname === '/api/mcp/health') {
        if (!this.authorize(req, this.mcpToken)) return this.json(res, 401, { error: 'MCP authorization required' });
        if (req.method !== 'GET') return this.json(res, 405, { error: 'GET required' });
        return this.json(res, 200, { ready: !this.bridge.closed, pid: process.pid, now: Date.now() });
      }
      if(url.pathname==='/api/mcp/session'){
        if(!this.authorize(req,this.mcpToken)||req.method!=='POST')return this.json(res,401,{error:'Authenticated session required'});
        const body=await readJSON(req);require('./control-plane-store').object(body,['session_id']);if(body.session_id&&!require('./product-observability').id(body.session_id))throw Error('Invalid resume identity');
        for(const [id,s]of this.mcpSessions)if(s.expires_at<Date.now())this.mcpSessions.delete(id);
        if(this.mcpSessions.size>=64)throw Error('Session bound reached');
        const db=this.bridge.controlStore.db;
        if(body.session_id&&!db.prepare('SELECT id FROM cp_mcp_handoff_sessions WHERE id=?').get(body.session_id))throw Error('Unknown session identity');
        const session_id=body.session_id||randomUUID(),expires_at=Date.now()+2*60*60*1000;
        db.prepare('INSERT INTO cp_mcp_handoff_sessions VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET expires_at=excluded.expires_at').run(session_id,Date.now(),expires_at);
        const mcp=new McpTools(this.bridge,{origin:()=>this.origin,authenticatedConnection:()=>({epoch:this.mcpConnectionEpoch,authenticatedAt:Date.now()})});
        mcp.handoffPrincipal=session_id;this.mcpSessions.set(session_id,{mcp,expires_at});return this.json(res,200,{session_id,expires_at});
      }
      if (url.pathname === '/api/mcp/call') {
        if (!this.authorize(req, this.mcpToken)) return this.json(res, 401, { error: 'MCP authorization required; restart the adapter after bridge restart' });
        if (req.method !== 'POST') return this.json(res, 405, { error: 'POST required' });
        if (req.headers['content-type']?.split(';')[0].trim() !== 'application/json') return this.json(res, 415, { error: 'JSON content type required' });
        const body = await readJSON(req);
        if (Object.keys(body).some(k => !['name', 'args', 'clientInfo'].includes(k)) || typeof body.name !== 'string') throw new Error('Invalid MCP operation');
        if (body.clientInfo !== undefined && (!body.clientInfo || typeof body.clientInfo !== 'object' || Array.isArray(body.clientInfo) || Object.keys(body.clientInfo).some(k => !['name', 'version'].includes(k)) || Object.values(body.clientInfo).some(v => typeof v !== 'string' || v.length > 100))) throw new Error('Invalid MCP client metadata');
        const session=this.mcpSessions.get(req.headers['x-airodrom-session']);
        if(['submit_mission','get_mission_handoff','cancel_mission_handoff'].includes(body.name)&&(!session||session.expires_at<Date.now()))throw Error('Fresh authenticated handoff session required');
        const result = await (session?.mcp||this.mcp).call(body.name, body.args, body.clientInfo);
        this.lastMcpCallAt = Date.now();
        return this.json(res, 200, result);
      }
      if (!this.authorize(req)) return this.json(res, 401, { error: 'Open the private Control Center link printed by the bridge to connect' });
      if (req.method === 'GET' && url.pathname === '/api/product/native-status') return this.json(res, 200, await require('./product-observability').nativeStatus(this.bridge));
      if (req.method === 'GET' && url.pathname === '/api/product/memory') {
        const query=url.searchParams.get('query')||'';if(query.length>240)throw Error('Memory query too long');
        const result=this.interactiveMemory(query);
        return this.json(res,200,{generation:require('./product-observability').memoryStatus(this.bridge).generation,items:result.items.map(m=>({id:require('./product-observability').id(m.memoryId),subject:require('./secret-observation').safeValue(m.subject),content:require('./secret-observation').safeValue(m.content),status:'active',source:'Explicit operator reference; not authority'}))});
      }
      if (req.method === 'GET' && url.pathname === '/api/product/overview') return this.json(res, 200, await require('./product-observability').overview(this.bridge,{currentOffset:Number(url.searchParams.get('current_offset')||0)}));
      if (req.method === 'GET' && url.pathname === '/api/product/events') return this.json(res, 200, require('./product-observability').events(this.bridge, url));
      if (req.method === 'GET' && url.pathname === '/api/product/mission') return this.json(res, 200, require('./product-observability').missionView(this.bridge, this.bridge.missions.require(url.searchParams.get('id'))));
      if(req.method==='GET'&&url.pathname==='/api/assistant/history'){
        const selected=url.searchParams.get('mission_id');
        if(selected&&!require('./product-observability').id(selected))throw Error('Invalid Mission ID');
        const rows=selected?this.bridge.controlStore.db.prepare("SELECT id FROM cp_missions WHERE id=? AND json_extract(envelope,'$.kind')='conversation'").all(selected):this.bridge.controlStore.db.prepare("SELECT id FROM cp_missions WHERE json_extract(envelope,'$.kind')='conversation' ORDER BY created_at DESC LIMIT 20").all();
        const items=rows.map(r=>{const m=this.bridge.missions.require(r.id),t=this.bridge.tasks.get(m.task_id);const prompt=require('./conversation-mission').projectRead(this.bridge,t.id,m.envelope.objective,m.id),response=require('./conversation-mission').projectRead(this.bridge,t.id,t.lastResult||null,m.id);return {mission_id:m.id,state:m.state,prompt:typeof prompt==='string'?prompt:null,response:typeof response==='string'?response:null};});return this.json(res,200,{items,generation:require('./product-observability').memoryStatus(this.bridge).generation,streaming:'Unavailable: adapter returns one bounded visible response'});
      }
      if(req.method==='GET'&&url.pathname==='/api/assistant/registry')return this.json(res,200,await require('./model-worker-router').inspect(this.bridge));
      if(req.method==='GET'&&url.pathname==='/api/assistant/connectors')return this.json(res,200,require('./assistant-service').connectors(this.bridge).status());
      if(req.method==='GET'&&url.pathname==='/api/assistant/sensitive')return this.json(res,200,require('./assistant-service').sensitiveList(this.bridge));
      if(req.method==='GET'&&url.pathname==='/api/assistant/handoff')return this.json(res,200,require('./mission-handoff').status(this.bridge,url.searchParams.get('id'),'operator'));
      if (req.method === 'GET' && url.pathname === '/api/interactive/status') return this.json(res, 200, { protocol: 'airodrom-local-v1', pid: process.pid, healthy: !this.bridge.closed, managed: typeof this.localShutdown === 'function', source_sha256: this.bridge.runtimeFingerprint.source_sha256, default_runtime: this.bridge.defaultRuntime, opencode: await this.bridge.opencodeAdapter.readiness(), memory_schema: 2, reasoning_scope: 'bounded registered local Mission; no tools', active_runs: this.bridge.controlStore.db.prepare("SELECT count(*) n FROM cp_runs WHERE state IN ('starting','running','verifying','termination_unverified')").get().n, quarantined_leases: this.bridge.controlStore.db.prepare("SELECT count(*) n FROM cp_leases WHERE state='quarantined'").get().n });
      if (req.method === 'GET' && url.pathname === '/api/interactive/memory') return this.json(res, 200, this.interactiveMemory(url.searchParams.get('query') || ''));
      if (req.method === 'GET' && url.pathname === '/api/interactive/task') return this.json(res, 200, this.interactiveTask(url.searchParams.get('mission_id')));
      if (req.method === 'GET' && url.pathname.startsWith('/api/control-v2/')) return this.json(res, 200, controlPlaneRead(this.bridge, url));
      if (req.method === 'POST' && url.pathname.startsWith('/api/control-v2/')) {
        if (req.headers['content-type']?.split(';')[0].trim() !== 'application/json') return this.json(res, 415, { error: 'JSON content type required' });
        return this.json(res, 200, await controlPlaneWrite(this.bridge, url.pathname.slice('/api/control-v2/'.length), await readJSON(req)));
      }
      if (req.method === 'GET' && url.pathname === '/api/status') return this.json(res, 200, this.status());
      if (req.method === 'GET' && url.pathname === '/api/state') {
        const snapshot = this.bridge.snapshot();
        snapshot.bridge.chatgptConnection = await this.connectionStatus();
        snapshot.bridge.directChatGPT = snapshot.bridge.chatgptConnection.connected;
        return this.json(res, 200, snapshot);
      }
      if (req.method === 'GET' && url.pathname === '/api/memory') {
        const taskId = url.searchParams.get('taskId'); const task = this.bridge.tasks.get(taskId);
        const query = url.searchParams.get('query') || '';
        const canonical = task.executionAgent === 'opencode' && task.includeSharedMemory === true;
        const result = canonical ? { items: this.interactiveMemory(query).items.map(m => ({ ...m, id: m.memoryId, kind: m.type, shared: true, provenance: { source: 'operator', authority: false } })) } : query ? this.bridge.memory.search(query, { taskId, includeShared: task.includeSharedMemory === true }) : { items: this.bridge.memory.list({ taskId, includeShared: task.includeSharedMemory === true }) };
        return this.json(res, 200, result);
      }
      if (req.method === 'GET' && url.pathname === '/api/personal-memory') {
        const id = url.searchParams.get('id'); const query = url.searchParams.get('query');
        const scope = {
          ...(url.searchParams.has('domain') ? { domain: url.searchParams.get('domain') } : {}),
          ...(url.searchParams.has('projectId') ? { projectId: url.searchParams.get('projectId') } : {}),
          ...(url.searchParams.has('taskId') ? { taskId: url.searchParams.get('taskId') } : {}),
          ...(url.searchParams.has('sessionId') ? { sessionId: url.searchParams.get('sessionId') } : {})
        };
        if (id) return this.json(res, 200, { item: this.bridge.personalMemory.get(id, { includeInactive: url.searchParams.get('includeInactive') === 'true' }) });
        if (query !== null) return this.json(res, 200, this.bridge.personalMemory.search(query, { ...scope, includeSensitive: true }));
        return this.json(res, 200, this.bridge.personalMemory.recent(scope));
      }
      if (req.method === 'GET' && url.pathname === '/api/projects') return this.json(res, 200, { items: this.bridge.projects.listProjects({ status: url.searchParams.get('status') || null }) });
      if (req.method === 'GET' && url.pathname === '/api/next-actions') return this.json(res, 200, this.bridge.nextActions.choose());
      if (req.method === 'GET' && url.pathname === '/api/capabilities') return this.json(res, 200, await this.bridge.capabilityInventory({ detect: url.searchParams.get('detect') === 'true' }));
      if (req.method === 'GET' && url.pathname === '/api/capabilities/activity') return this.json(res, 200, this.bridge.capabilityActivity());
      if (req.method === 'GET' && url.pathname === '/api/agents') return this.json(res, 200, await this.bridge.agentStatus());
      let projectReadMatch = /^\/api\/projects\/([0-9a-f-]{36})(?:\/(summary|memory))?$/.exec(url.pathname);
      if (req.method === 'GET' && projectReadMatch) {
        const [, projectId, action] = projectReadMatch;
        if (action === 'summary') return this.json(res, 200, this.bridge.projects.summary(projectId));
        if (action === 'memory') {
          const query = url.searchParams.get('query'); if (!query) throw new Error('Project memory query is required');
          return this.json(res, 200, this.bridge.projects.projectMemory(projectId, query));
        }
        return this.json(res, 200, this.bridge.projects.getProject(projectId));
      }
      if (req.method !== 'POST') return this.json(res, 404, { error: 'Operation not exposed' });
      if (req.headers['content-type']?.split(';')[0].trim() !== 'application/json') return this.json(res, 415, { error: 'JSON content type required' });
      const body = await readJSON(req);
      if (url.pathname.startsWith('/api/product/')) {
        try {
          const action = url.pathname.slice('/api/product/'.length);
          if(['remember-memory','correct-memory','forget-memory'].includes(action)){
            require('./control-plane-store').object(body,action==='remember-memory'?['content']:action==='correct-memory'?['id','content']:['id']);
            if(action!=='remember-memory'){
              if(!require('./product-observability').id(body.id))throw Error('Current personal memory identity required');
              const a=this.bridge.authorityRuntime,m=a?.active?a.memory.get(body.id):this.bridge.personalMemory.get(body.id);
              if(!m || (a?.active ? m.operator_id!==a.store.operatorId||m.scope!=='global'||m.kind!=='personal_preference'||!['public','internal'].includes(m.privacy)||a.memory.eligibility(m,{operator_id:a.store.operatorId,include_personal:true,privacy:'internal'},a.store.now())!==null : m.domain!=='personal'||m.sensitivity!=='normal'||m.status!=='active'))throw Error('Current authorized personal memory required');
            }
            const m=action==='remember-memory'?this.rememberInteractive(body.content):action==='correct-memory'?this.bridge.updatePersonalMemory(body.id,{content:require('./control-plane-store').text(body.content,'memory content',2000)}):this.bridge.forgetPersonalMemory(body.id);
            if(this.bridge.authorityRuntime?.active)this.bridge.ledger.record({eventType:action==='forget-memory'?'product.memory.forgotten':action==='correct-memory'?'product.memory.corrected':'product.memory.recorded',agent:'bridge',direction:'internal',metadata:{}});
            return this.json(res,200,{memory_id:require('./product-observability').id(m?.memoryId||m?.id||body.id),receipt:action==='forget-memory'?'Forgotten':'Current canonical memory recorded'});
          }
          if(action==='archive-project'){
            require('./control-plane-store').object(body,['id','request_id']);if(body.request_id)require('./control-plane-store').text(body.request_id,'request id',240);const project=this.bridge.projects.archiveProject(body.id);
            return this.json(res,200,{project_id:require('./product-observability').id(project.projectId),status:'archived'});
          }
          if (!['dispatch-mission','cancel-mission','accept-mission'].includes(action)) return this.json(res, 404, { error: 'Product action unavailable' });
          require('./control-plane-store').object(body, action === 'accept-mission' ? ['id','request_id','verification_id','decision','rationale','evidence'] : ['id','request_id']);
          this.bridge.missions.require(body.id);
          await require('./control-plane-api').controlPlaneWrite(this.bridge, action, body);
          const mission = this.bridge.missions.require(body.id);
          return this.json(res, 200, { mission_id: require('./product-observability').id(mission.id), state: require('./product-observability').state(mission.state), receipt: 'Canonical operation recorded' });
        } catch { return this.json(res, 400, { error: 'Canonical operation refused. Refresh current authority and verification before retrying.' }); }
      }
      if(url.pathname==='/api/assistant/connect'){
        require('./control-plane-store').object(body,['connector']);if(body.connector!=='gmail'||!this.gmailOAuth)return this.json(res,200,{state:'WAIT',message:'Configure an owner Google desktop OAuth client with airodrom gmail setup <client-id>, prepare the Keychain helper, then restart the service. WhatsApp requires an official host webhook transport.'});
        return this.json(res,200,this.gmailOAuth.start(this.origin+'/oauth/gmail/callback'));
      }
      if(url.pathname==='/api/assistant/input')return this.json(res,202,await require('./assistant-service').submit(this,body));
      if(url.pathname==='/api/assistant/handoff')return this.json(res,202,await require('./mission-handoff').submit(this.bridge,body,'operator'));
      if(url.pathname==='/api/assistant/sensitive'){
        require('./control-plane-store').object(body,['content','id']);const m=require('./assistant-service').sensitiveRecord(this.bridge,body.content,body.id);return this.json(res,201,{memoryId:m.memoryId,stored:true,operator_only:true});
      }
      if(url.pathname==='/api/assistant/reveal-sensitive'){
        require('./control-plane-store').object(body,['id']);return this.json(res,200,require('./assistant-service').reveal(this.bridge,body.id));
      }
      if(url.pathname==='/api/assistant/connector'){
        require('./control-plane-store').object(body,['connector','action','input']);return this.json(res,200,await require('./assistant-service').connectorInput(this,{connector:body.connector,action:body.action,input:body.input||{}}));
      }
      if (url.pathname === '/api/interactive/tasks') {
        const parsed=require('./assistant-intent').parse(body.message);
        if(parsed.kind!=='conversation')return this.json(res,200,await require('./assistant-service').submit(this,{message:body.message,request_id:body.request_id,include_memory:body.include_memory}));
        const created = this.bridge.missions.createConversation(body);
        this.bridge.missions.dispatch(created.mission_id, { request_id: 'interactive:' + body.request_id });
        return this.json(res, 202, created);
      }
      if (url.pathname === '/api/interactive/cancel') {
        require('./control-plane-store').object(body, ['mission_id', 'request_id']);
        return this.json(res, 200, this.bridge.missions.cancel(body.mission_id, body));
      }
      if (url.pathname === '/api/interactive/stop') {
        if (Object.keys(body).length || typeof this.localShutdown !== 'function') throw Error('Only the managed local service can be stopped by this endpoint.');
        this.json(res, 202, { stopping: true }); setImmediate(() => this.localShutdown().catch(() => {})); return;
      }
      if (url.pathname === '/api/interactive/remember') {
        require('./control-plane-store').object(body, ['content']);
        return this.json(res, 201, this.rememberInteractive(body.content));
      }
      if (url.pathname === '/api/interactive/forget') {
        require('./control-plane-store').object(body, ['selection']);
        const result=require('./assistant-service').forget(this,body.selection);
        if(result.kind!=='forgotten')throw Error('Forget requires one current memory ID. '+result.message);
        return this.json(res,200,{memoryId:result.memoryId,forgotten:true});
      }
      if (url.pathname === '/api/active-chat/authority/initialize') {
        if (Object.keys(body).length) throw new Error('Active Chat authority initialization accepts no arguments');
        return this.json(res, 201, this.bridge.initializeActiveChatAuthority());
      }
      let activeGrant = /^\/api\/tasks\/([0-9a-f-]{36})\/active-chat\/authorize$/.exec(url.pathname);
      if (activeGrant) {
        if (Object.keys(body).length) throw new Error('Active Chat authorization accepts no caller-supplied scope or grant fields');
        const task = this.assertCanRun(activeGrant[1]);
        const binding = task.source?.mcpConnection;
        if (!task.source?.connectionAuthenticated || !binding || binding.epoch !== this.mcpConnectionEpoch || !Number.isSafeInteger(binding.authenticatedAt) || Date.now() - binding.authenticatedAt > 10 * 60_000) throw new Error('Active Chat grant requires a fresh task from the current authenticated MCP connection');
        const result = this.bridge.authorizeActiveChatMission(task.id, { trusted: true, id: randomUUID(), mcpConnectionEpoch: this.mcpConnectionEpoch });
        return this.json(res, 202, result);
      }
      if (url.pathname === '/api/tasks') {
        if (body.workspace != null && (typeof body.workspace !== 'string' || !path.isAbsolute(body.workspace))) throw new Error('Workspace must be an absolute path');
        const created = this.bridge.createTask(body.description, { executionAgent: body.executionAgent, acceptanceCriteria: body.acceptanceCriteria, workspace: body.workspace || undefined, includeSharedMemory: body.includeSharedMemory === true, projectId: body.projectId, ...(!body.workspace && (body.executionAgent || this.bridge.defaultRuntime) === 'opencode' ? { capabilityScopes: [] } : {}) });
        return this.json(res, 201, created);
      }
      if (url.pathname === '/api/checkpoints') {
        const task = this.bridge.tasks.get(body.taskId);
        const checkpoint = this.bridge.memory.saveCheckpoint(task.id, body.checkpoint, { sessionId: task.sessionId });
        task.lastCheckpointAt = Date.now(); task.checkpointId = checkpoint.id; this.bridge.tasks.save(task);
        this.bridge.supervisor.schedule();
        return this.json(res, 201, checkpoint);
      }
      if (url.pathname === '/api/memory') {
        const task = this.bridge.tasks.get(body.taskId);
        if (task.executionAgent === 'opencode' && body.shared === true) return this.json(res, 201, this.rememberInteractive(body.content));
        return this.json(res, 201, this.bridge.saveMemory(body));
      }
      if (url.pathname === '/api/personal-memory/remember') return this.json(res, 201, this.bridge.rememberPersonalMemory(body));
      let personalMemoryMatch = /^\/api\/personal-memory\/([A-Za-z0-9_.:-]{1,160})\/(update|forget)$/.exec(url.pathname);
      if (personalMemoryMatch) {
        const [, memoryId, action] = personalMemoryMatch;
        if (action === 'forget') {
          if (Object.keys(body).length) throw new Error('Forget accepts no replacement content');
          return this.json(res, 200, this.bridge.forgetPersonalMemory(memoryId));
        }
        return this.json(res, 200, this.bridge.updatePersonalMemory(memoryId, body));
      }
      if (url.pathname === '/api/projects') return this.json(res, 201, this.bridge.projects.createProject(body));
      let projectWriteMatch = /^\/api\/projects\/([0-9a-f-]{36})\/(archive|goals|dependencies|blockers)$/.exec(url.pathname);
      if (projectWriteMatch) {
        const [, projectId, action] = projectWriteMatch;
        if (action === 'archive') { if (Object.keys(body).length) throw new Error('Archive accepts no body'); return this.json(res, 200, this.bridge.projects.archiveProject(projectId)); }
        if (action === 'goals') return this.json(res, 201, this.bridge.projects.createGoal({ ...body, projectId }));
        const owner = body.ownerType === 'goal' ? this.bridge.projects.getGoal(body.ownerId) : body.ownerType === 'mission' ? this.bridge.projects.getMission(body.ownerId) : null;
        if (!owner || owner.projectId !== projectId) throw new Error('Project entity is outside requested project');
        if (action === 'dependencies') return this.json(res, 201, this.bridge.projects.addDependency(body));
        return this.json(res, 201, this.bridge.projects.addBlocker(body));
      }
      let goalMissionMatch = /^\/api\/goals\/([0-9a-f-]{36})\/missions$/.exec(url.pathname);
      if (goalMissionMatch) return this.json(res, 201, this.bridge.projects.createMission({ ...body, goalId: goalMissionMatch[1] }));
      let missionStatusMatch = /^\/api\/missions\/([0-9a-f-]{36})\/status$/.exec(url.pathname);
      if (missionStatusMatch) return this.json(res, 200, this.bridge.projects.setMissionStatus(missionStatusMatch[1], body.status, { nextAction: body.nextAction }));
      let projectLinkMatch = /^\/api\/projects\/([0-9a-f-]{36})\/(tasks|runs|events)\/([A-Za-z0-9_.:-]{1,160})$/.exec(url.pathname);
      if (projectLinkMatch) {
        const [, projectId, kind, linkedId] = projectLinkMatch;
        if (kind === 'tasks') { if (Object.keys(body).length) throw new Error('Task link accepts no body'); return this.json(res, 201, this.bridge.associateTaskWithProject(projectId, linkedId)); }
        if (kind === 'runs') return this.json(res, 201, this.bridge.projects.associateRun(projectId, linkedId, { taskId: body.taskId ?? null }));
        return this.json(res, 201, this.bridge.projects.associateEvent(projectId, linkedId, { taskId: body.taskId ?? null }));
      }
      let match = /^\/api\/tasks\/([0-9a-f-]{36})\/(prompt|cancel|pause|resume|resolve-stop|web)$/.exec(url.pathname);
      if (match) {
        const [, id, action] = match; const task = this.bridge.tasks.get(id);
        if (action === 'prompt') {
          if (task.mission?.level1MissionId) {
            await this.bridge.handleLevel1HumanTurn(id);
            return this.json(res, 403, { error: 'Level 1 read-only proof accepts no human turns after authorization' });
          }
          if (task.mission?.capabilityProfile === 'active-chat-local-ollama-smoke-v1') return this.json(res, 403, { error: 'Active Chat smoke accepts only its authenticated MCP continuation' });
          this.assertCanRun(id);
          if (typeof body.message !== 'string' || !body.message.trim() || body.message.length > 59000 || /^\s*[/!@]/.test(body.message)) throw new Error('Plain-text prompt required (maximum 59,000 characters)');
          if (task.executionAgent === 'opencode') {
            if (task.requiredExecutionKind === 'native') throw Error('Coding work requires a registered scoped Mission with allowed files and verification. Use Control Hub Mission creation.');
            const created = this.bridge.missions.createConversation({ request_id: randomUUID(), message: body.message, include_memory: task.includeSharedMemory === true, runtime: task.executionAgent, ...(!task.controlPlaneMissionId ? { task_id: task.id } : {}) });
            this.bridge.missions.dispatch(created.mission_id, { request_id: 'browser:' + randomUUID() });
            return this.json(res, 202, { accepted: true, taskId: created.task_id, missionId: created.mission_id, scope: 'reasoning_only' });
          }
          this.bridge.prompt(id, body.message).catch(() => {}); return this.json(res, 202, { accepted: true, taskId: id });
        }
        if (task.mission?.level1MissionId) {
          this.bridge.recordLevel1ManualNextAction(id, action);
          await this.bridge.cancel(id);
          return this.json(res, 403, { error: `Manual Level 1 action denied: ${action}; the mission is cancelled` });
        }
        if (action === 'cancel') {
          for (const controller of this.webRequests.get(id) || []) controller.abort();
          if (task.controlPlaneMissionId && this.bridge.controlStore.requireMission(task.controlPlaneMissionId).envelope.kind === 'conversation') {
            this.bridge.missions.cancel(task.controlPlaneMissionId, { request_id: randomUUID() });
            return this.json(res, 200, this.bridge.snapshotTask(task));
          }
          return this.json(res, 200, await this.bridge.cancel(id));
        }
        if (['pause', 'resume'].includes(action) && task.controlPlaneMissionId && this.bridge.controlStore.requireMission(task.controlPlaneMissionId).envelope.kind === 'conversation') throw Error('Bounded conversation Missions cannot use legacy pause/resume. Cancel and submit a fresh question.');
        if (action === 'pause') return this.json(res, 200, await this.bridge.pause(id));
        if (action === 'resume') { await this.bridge.resume(id); return this.json(res, 202, { accepted: true, taskId: id, status: 'resuming' }); }
        if (action === 'resolve-stop') {
          if (Object.keys(body).some(key => key !== 'rationale')) throw new Error('Only a resolution rationale is accepted');
          if (typeof body.rationale !== 'string' || !body.rationale.trim()) throw new Error('Operator resolution rationale is required');
          return this.json(res, 200, this.bridge.resolveSafetyStop(id, body.rationale));
        }
        if (action === 'web') {
          const controller = new AbortController();
          if (!this.webRequests.has(id)) this.webRequests.set(id, new Set());
          this.webRequests.get(id).add(controller);
          res.on('close', () => { if (!res.writableEnded) controller.abort(); });
          try { return this.json(res, 200, await this.bridge.web.fetch(body, { taskId: id, sessionId: task.sessionId, signal: controller.signal })); }
          finally { this.webRequests.get(id)?.delete(controller); }
        }
      }
      match = /^\/api\/approvals\/([0-9a-f-]{36})\/(approve|reject)$/.exec(url.pathname);
      if (match) {
        const [, id, action] = match;
        if (action === 'reject') return this.json(res, 200, this.bridge.reject(id));
        const pending = this.bridge.policy.list().find(a => a.id === id); if (!pending) throw new Error('Approval not found');
        // Direct host execution of the captured approved capability — no model
        // reconstruction of the tool call, and no Local Ollama grant on resume.
        const approval = this.bridge.approve(id);
        this.bridge.resumeApproved(approval).catch(() => {});
        return this.json(res, 202, { approved: true, taskId: approval.taskId, approvalId: id });
      }
      return this.json(res, 404, { error: 'Operation not exposed' });
    } catch (error) { if (!res.writableEnded) this.json(res, 400, { error: error.message }); }
  }
  async close() {
    for (const controllers of this.webRequests.values()) for (const controller of controllers) controller.abort();
    if (this.server.listening) await new Promise(resolve => { this.server.close(resolve); this.server.closeAllConnections(); });
  }
}
module.exports = ControlServer;
