'use strict';
// Host-owned research uses the existing Mission, invocation, run, review and
// Acceptance records. Public page text is evidence, never an executable plan.
const fs=require('node:fs'),path=require('node:path');
const {randomUUID,createHash}=require('node:crypto');
const {transaction,fingerprint,object,text}=require('./control-plane-store');
const {afterCommit}=require('./control-transaction');
const {repositoryRoot}=require('./control-execution');
const PROFILE='governed-browser-research-v1';
const UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i;
const PHASES=Object.freeze(['scope','baseline','browser','inventory','responsive','comparison','report','verification','review','acceptance','settlement']);
const LABELS=['Approve research scope','Read Arecibo baseline','Open public website','Inventory public pages','Capture desktop and mobile evidence','Compare verified features','Prepare research report','Verify evidence independently','Record independent Mission review','Owner Acceptance','Record local Settlement'];
const digest=value=>createHash('sha256').update(value).digest('hex');
function entry(value){
 text(value,'public website',2000);let u;try{u=new URL(value);}catch{throw Error('A public website URL is required');}
 if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash||u.port&&!['443'].includes(u.port)||!u.hostname.includes('.')||/^\[|^[\d.]+$/.test(u.hostname)||/(?:^|\.)(?:localhost|local|internal|invalid)$/.test(u.hostname))throw Error('An HTTPS public website without credentials, query parameters or fragments is required');
 return u.href;
}
function bound(value,fallback,max){const n=value??fallback;if(!Number.isSafeInteger(n)||n<1||n>max)throw Error('Invalid host research budget');return n;}
class ResearchMission{
 constructor(service,options){
  this.service=service;this.bridge=service.bridge;this.store=service.store;this.db=service.db;
  this.options=options||this.bridge.options.researchMission||require('./research-profile').researchProfile();
  if((this.options.browserFactory||this.options.baselineFactory||this.options.reportFactory||this.options.verifyEvidence||this.options.credentialsFactory)&&!(process.env.NODE_ENV==='test'&&this.options.synthetic===true))throw Error('Synthetic research adapters are unavailable');
  this.maxPages=bound(this.options.maxPages,12,12);this.maxActions=bound(this.options.maxActions,90,100);this.timeoutMs=bound(this.options.timeoutMs,180000,180000);
  this.active=new Map();
 }
 safeSnapshot(m){return this.baseline(m.envelope.workspace).workspaceSnapshot();}
 get credentials(){return this._credentials||(this._credentials=this.options.credentialsFactory?this.options.credentialsFactory():new (require('./research-credentials').ResearchCredentials)(this.bridge));}
 baseline(workspace){return this.options.baselineFactory?this.options.baselineFactory({workspace}):new (require('./research-baseline').ResearchBaseline)({workspace,approvedFiles:this.options.baselineFiles,features:this.options.features});}
 phase(id,phase,state='active',extra={}){if(!PHASES.includes(phase)||!['active','completed','attention'].includes(state))throw Error('Invalid research phase');this.store.event('research.phase',id,{phase,state,...extra});this.bridge.emit('change');}
 create(input,owner='operator'){
  if(owner!=='operator')throw Error('Authenticated operator research registration is required');
  object(input,['request_id','objective','entry_url','workspace','account_authorization']);if(!UUID.test(input.request_id||''))throw Error('Opaque UUID request identity required');text(input.objective,'research objective',4000);
  if(require('./personal-memory').containsSecret(input.objective))throw Error('Research objectives cannot contain credentials');
  const url=entry(input.entry_url),origin=new URL(url).origin;
  if(this.options.origins&&!this.options.origins.includes(origin))throw Error('Website is outside the host research origin allowlist');
  let account=null;if(input.account_authorization!==undefined){const a=input.account_authorization;object(a,['username_reference','password_reference','confirmed']);if(a.confirmed!==true||!UUID.test(a.username_reference||'')||!UUID.test(a.password_reference||'')||a.username_reference===a.password_reference)throw Error('Explicit purpose-bound stored credentials required');this.credentials.validateReferences(a.username_reference,a.password_reference);account={id:randomUUID(),origin,login_url:url,username_reference:a.username_reference,password_reference:a.password_reference,confirmed:true,purpose:'competitor_product_research'};}
  const workspace=repositoryRoot(this.options.workspace);if(input.workspace&&fs.realpathSync(input.workspace)!==workspace)throw Error('Research baseline is the host registered Arecibo repository');
  if(this.db.prepare("SELECT 1 FROM cp_leases WHERE resource=? AND mode='write' AND state IN ('held','quarantined')").get(workspace))throw Error('Arecibo has an active or uncertain writer; research must wait');
  const reader=this.baseline(workspace),baseline=reader.capture(),preimage=reader.workspaceSnapshot(baseline);
  if(!this.bridge.missionAuthority.fixtureOnly)this.bridge.missionAuthority.initializeOperatorKey();
  return this.store.request(owner,input.request_id,{op:'research_create',objective:input.objective,entry_url:url,workspace,account_references:input.account_authorization||null},()=>{
   const registration=this.store.request(owner,'research-registry:'+PROFILE,{op:'research_registry'},()=>{
    const p=this.bridge.projects.createProject({name:'Arecibo product research',repositories:[workspace]});const g=this.bridge.projects.createGoal({projectId:p.projectId,name:'Bounded public product research'});return{project_id:p.projectId,goal_id:g.goalId};
   });
   // Keep the unique host suffix alphabetic: a valid opaque UUID can contain a
   // card-like digit sequence, while mission prose must retain secret screening.
   const requestLabel=input.request_id.toLowerCase().replace(/[0-9a-f]/g,c=>'abcdefghijklmnop'[parseInt(c,16)]);
   const pm=this.bridge.projects.createMission({goalId:registration.goal_id,name:input.objective.slice(0,130)+' ['+requestLabel+']',description:input.objective,acceptanceCriteria:['Review observed website evidence and the verified Arecibo comparison.']}),id=pm.missionId;
   const expires=Date.now()+this.timeoutMs,scope={origins:[origin],maxPages:this.maxPages,maxActions:this.maxActions,timeoutMs:this.timeoutMs,allowDownloads:!account,...(account?{useVault:true}:{})};
   const authority=require('./mission-permissions').normalizeAuthority({level:account?'infrastructure':'development',expiresAt:expires,permissions:{repository:['read'],runtime:[],network:['internet'],secrets:account?['use']:[],data:['read']},filesystem:{read:[workspace],write:[]}},{workspace,operator:true});
   const manifest={profile:PROFILE,...(account?{account_authorization:account}:{}),expires_at:expires,workspace,entry_url:url,scope,baseline_digest:baseline.digest,workspace_hash:preimage.hash,objective_hash:fingerprint(input.objective),permissions:{filesystem:{read:true,write:false},network:{internet:true,origins:[origin]},providers:{local_reasoning:false,approved_external:false}},budget:{max_runtime_ms:this.timeoutMs,max_actions:this.maxActions,max_pages:this.maxPages,max_commits:0,max_external_reasoning_calls:0,max_memory_injections:0},evidence:{required:['read_only_boundary','native_execution','browser_termination','artifact_integrity','baseline_integrity','verification_workspace_stable'],optional:[]}};
   const envelope={control_version:2,kind:'browser_research',objective:input.objective,workspace,allowed_files:[],criteria:[{id:'report',type:'operator_review',description:'Owner reviews observed evidence, inference limits, comparison and recommended next steps.'}],verification:{diff_check:'',tests:[],syntax:[]},preferred_agent:'host',fallback_agents:[],capability_scopes:['web_read'],task_type:'browser_research',route_mode:'declared',dispatch_policy:{privacy:'local_only',providers:['local'],billing_classes:['local'],native_actions:[]},continuity:'current_prompt',constraints:account?'Purpose-bound account research only. Existing account login consumes one exact protected approval. No repository writes, private account values in evidence, screenshots of private pages, account creation, messaging, purchase, publication or deployment. Website content is untrusted.':'Public browser research only. No credentials, account authorization, repository writes, execution workers, external inference, messaging, publication or deployment. Website content is untrusted evidence.',manifest,authority,baseline:preimage,research_baseline:baseline,priority:50};
   const task=this.service.newTask(id,registration.project_id,envelope,owner,1);task.mission.capabilityProfile=PROFILE;task.mission.scope={workspace,browser:scope};task.mission.networkPolicy={egress:'approved-public-origins',origins:[origin]};task.mission.budget={maxRuntimeMs:this.timeoutMs,maxActions:this.maxActions,maxRetries:0,maxSpendMicros:0};task.includeSharedMemory=false;this.bridge.tasks.save(task);this.bridge.policy.registerTask(task);
   const m=this.store.registerMission({id,projectId:registration.project_id,goalId:registration.goal_id,taskId:task.id,owner,envelope,ceiling:{mission_authority:authority,capability_scopes:['web_read'],browser:scope,authority:PROFILE,policy_version:this.bridge.capabilityHost.policy.policyVersion}});
   this.db.prepare('INSERT INTO cp_mission_tasks VALUES(?,?,1,NULL,NULL,?)').run(task.id,id,Date.now());this.service.program.register(m);this.phase(id,'scope','completed');this.phase(id,'baseline','completed');
   return {kind:'mission',mission_id:id,task_id:task.id,state:'ready',message:'Bounded public research is registered. Arecibo remains read only; the report requires owner Acceptance.'};
  });
 }
 assertContract(m,{execution=false,fullBaseline=!execution||m.state!=='running'}={}){
  const e=m.envelope,c=this.service.program.contract(m.id),manifest=c?.manifest,task=this.bridge.tasks.get(m.task_id);
  if(e.kind!=='browser_research'||m.owner!=='operator'||!c?.signed||manifest.profile!==PROFILE||fingerprint(manifest)!==fingerprint(e.manifest)||manifest.workspace!==e.workspace||e.allowed_files.length||e.preferred_agent!=='host'||e.fallback_agents.length||JSON.stringify(e.capability_scopes)!=='["web_read"]'||e.task_type!=='browser_research'||e.dispatch_policy?.privacy!=='local_only'||e.automatic_acceptance||e.fixture_auto_acceptance)throw Error('Research contract unavailable or changed');
  if(execution&&Date.now()>=manifest.expires_at)throw Error('Research runtime budget expired');
  const expected={version:1,level:manifest.account_authorization?'infrastructure':'development',label:manifest.account_authorization?'Infrastructure':'Development',permissions:{repository:['read'],runtime:[],network:['internet'],secrets:manifest.account_authorization?['use']:[],data:['read']},filesystem:{read:[e.workspace],write:[]},expiresAt:manifest.expires_at};
  const ceiling=JSON.parse(this.db.prepare('SELECT ceiling FROM cp_grants WHERE id=? AND mission_id=?').get(m.grant_id,m.id)?.ceiling||'null');
  if(!ceiling||fingerprint(ceiling.mission_authority)!==fingerprint(expected)||fingerprint(e.authority)!==fingerprint(expected)||fingerprint(ceiling.browser)!==fingerprint(manifest.scope)||JSON.stringify(ceiling.capability_scopes)!=='["web_read"]'||manifest.scope.origins.length!==1||new URL(entry(manifest.entry_url)).origin!==manifest.scope.origins[0]||manifest.scope.allowDownloads!==!manifest.account_authorization||manifest.scope.useVault!==(manifest.account_authorization?true:undefined)||manifest.scope.maxPages!==this.maxPages||manifest.scope.maxActions!==this.maxActions||manifest.scope.timeoutMs!==this.timeoutMs||manifest.baseline_digest!==e.research_baseline.digest||manifest.workspace_hash!==e.baseline.hash||manifest.objective_hash!==fingerprint(e.objective))throw Error('Research permission ceiling changed');
  if(manifest.account_authorization){const a=manifest.account_authorization;if(a.origin!==manifest.scope.origins[0]||a.login_url!==manifest.entry_url||!UUID.test(a.id)||!UUID.test(a.username_reference)||!UUID.test(a.password_reference)||a.confirmed!==true||a.purpose!=='competitor_product_research')throw Error('Research account purpose changed');}
  if(task.content_state==='erased'||task.mission.objective!==e.objective||task.includeSharedMemory!==false||task.controlPlaneMissionId!==m.id||task.workspace!==e.workspace||task.executionAgent!=='host'||task.requiredExecutionKind!=='native'||task.mission.capabilityProfile!==PROFILE||JSON.stringify(task.capabilityScopes)!=='["web_read"]'||fingerprint(task.mission.manifest)!==fingerprint(manifest)||fingerprint(task.mission.authority)!==fingerprint(expected)||fingerprint(task.mission.scope)!==fingerprint({workspace:e.workspace,browser:manifest.scope})||fingerprint(task.mission.budget)!==fingerprint({maxRuntimeMs:this.timeoutMs,maxActions:this.maxActions,maxRetries:0,maxSpendMicros:0}))throw Error('Research Task binding changed');
  if(execution&&(task.cancelRequested||task.safetyStop?.latched||task.mission.authorityRevoked||['cancelled','completed'].includes(m.state)))throw Error('Research authority is stopped');
  if(fullBaseline&&this.safeSnapshot(m).hash!==e.baseline.hash||!this.baseline(e.workspace).verify(e.research_baseline))throw Error('Arecibo research baseline changed');
  return task;
 }
 assess(task,input){
  object(input,['mission_id','action']);if(!UUID.test(input.mission_id||''))throw Error('Research Mission identity required');const m=this.store.requireMission(input.mission_id),bound=this.assertContract(m,{execution:true}),active=this.active.get(m.id),run=active?this.store.run(active.runId):null;
  const dispatch=this.db.prepare("SELECT run_id FROM cp_dispatches WHERE mission_id=? AND task_id=? AND state='running'").get(m.id,task.id);
  if(bound.id!==task.id||!active||!run||run.state!=='running'||run.agent_id!=='host'||run.task_id!==task.id||dispatch?.run_id!==run.id||m.state!=='running')throw Error('Active canonical research run required');
  if(!input.action||typeof input.action.type!=='string')throw Error('Typed browser action required');
  if(input.action.type==='download'&&m.envelope.manifest.account_authorization)throw Error('Downloads are outside account research scope');
  if(input.action.type==='authenticate'){const a=this.credentials.authorized(m,input.action);if(input.action.approval_id!==a.id)throw Error('Exact sealed login authorization required');}else if(input.action.type==='login')throw Error('Typed purpose-bound account workflow required');
  return {scope:{mission_id:m.id},...(['form','download','authenticate'].includes(input.action.type)?{dynamic:{decision:'approval_required',riskClass:'SECURITY',reason:'Research public interaction requires exact operator approval'}}:{})};
 }
 recordInvocation(task,toolName,request){
  if(toolName!=='capability'||request?.input?.name!=='browser_research')throw Error('Research invocation evidence requires the scoped browser port');
  const input=request.input.input,m=this.store.requireMission(input?.mission_id);this.assess(task,input);
  const active=this.active.get(m.id),e=task.nativeExecutionEvidence;if(!e||e.run_id!==active.runId||e.required_execution_kind!=='native')throw Error('Research native evidence run binding changed');
  e.completed_invocations++;
 }
 async perform(task,input,signal){
  this.assess(task,input);const active=this.active.get(input.mission_id);if(active.operation)throw Error('Research browser operation is already active');active.operation=true;
  const abort=()=>active.controller.abort();signal?.addEventListener('abort',abort,{once:true});
  try{if(signal?.aborted)abort();return await active.browser.execute(input.action);}finally{active.operation=false;signal?.removeEventListener('abort',abort);}
 }
 async call(m,task,active,action,requestId){
  if((active.queued||0)>=3)throw Error('Bounded research action queue is full');active.queued=(active.queued||0)+1;const prior=active.callTail||Promise.resolve();let release;active.callTail=new Promise(resolve=>{release=resolve;});
  await prior;try{return await this.callAction(m,task,active,action,requestId);}finally{active.queued--;release();}
 }
 async callAction(m,task,active,action,requestId=randomUUID()){
  this.assertContract(this.store.requireMission(m.id),{execution:true});task.activeRunId=active.runId;
  let response=await this.bridge.invokeCapability(task.id,{name:'browser_research',input:{mission_id:m.id,action},requestId});
  if(response.status==='pending'&&this.bridge.orchestrator.inflight.has(requestId))response=await this.bridge.orchestrator.inflight.get(requestId);
  task.activeRunId=active.runId;
  if(response.status==='approval_required'&&response.approval&&action.type==='authenticate'){const a=this.credentials.authorized(this.store.requireMission(m.id),action),approval=this.bridge.policy.approvals.get(response.approval.approval_id);if(active.accountForwarded||a.confirmed!==true||action.approval_id!==a.id||!approval||approval.taskId!==task.id||approval.status!=='pending'||fingerprint(approval.input)!==fingerprint({name:'browser_research',input:{mission_id:m.id,action}}))throw Error('Exact account purpose approval unavailable');active.accountForwarded=true;this.store.event('research.account_authorization.forwarded',m.id,{authorization_id:a.id,approval_id:approval.id,purpose:'competitor_product_research'},{protected:true});this.bridge.approve(approval.id);return this.callAction(m,task,active,action);}
  if(response.status==='approval_required'&&response.approval){
   const id=response.approval.approval_id;active.pendingApproval=id;
   this.store.updateRun(active.runId,{state:'waiting_for_permission',processState:'alive',resolution:id});this.store.state(m.id,'waiting_for_operator','Exact protected browser approval required');this.phase(m.id,'browser','attention');
   try{await this.waitApproval(active,id);this.store.state(m.id,'ready','Exact captured browser approval granted');this.store.state(m.id,'dispatching');this.store.state(m.id,'running');this.store.updateRun(active.runId,{state:'running',processState:'alive'});this.phase(m.id,'browser');return await this.callAction(m,task,active,action);}finally{delete active.pendingApproval;}
  }
  if(response.status==='approval_required'){const error=Error('Protected operator approval is required');error.code='approval_required';error.approvalId=response.approval?.approval_id;throw error;}
  if(response.status!=='completed')throw Object.assign(Error('Research browser action did not complete'),{code:response.status==='unknown'?'invocation_unverified':'browser_stopped'});
  active.receipts.push(requestId);return response.result;
 }
 download(id,input,owner='operator'){
  if(owner!=='operator')throw Error('Authenticated operator download request required');object(input,['url','request_id']);if(!UUID.test(input.request_id||''))throw Error('Opaque download request identity required');
  const url=entry(input.url),m=this.store.requireMission(id),task=this.assertContract(m,{execution:true}),active=this.active.get(id);if(!active||active.finishing||m.state!=='running'||m.envelope.manifest.account_authorization||!m.envelope.manifest.scope.origins.includes(new URL(url).origin))throw Error('Active public research Mission and approved download origin required');
  active.downloadRequests||=new Map();active.downloadTasks||=new Set();if(!active.downloadRequests.has(input.request_id)&&active.downloadRequests.size>=3)throw Error('Bounded public download request limit reached');
  return this.store.request(owner,input.request_id,{op:'research_download',mission_id:id,url},()=>{
   const receipt={kind:'download_request',mission_id:id,request_id:input.request_id,state:'queued',approval_required:true,authority:false};active.downloadRequests.set(input.request_id,receipt);this.store.event('research.download.queued',id,{request_id:input.request_id,authority:false});
   // The operator receives the admission receipt immediately. The same serial
   // action queue persists a protected approval before any download occurs.
   afterCommit(this.db,()=>{const pending=this.call(m,task,active,{type:'download',url,approval_id:randomUUID()},input.request_id).then(row=>{if(row.classification!=='observed'||!row.download_ref||!row.evidence_ref)throw Error('Verified download receipt required');active.evidence.push(row);this.store.event('research.download.completed',id,{request_id:input.request_id,evidence_id:row.id,authority:false});}).catch(error=>{active.manualError=error;this.store.event('research.download.stopped',id,{request_id:input.request_id,reason:'protected_download_stopped',authority:false});}).finally(()=>active.downloadTasks.delete(pending));active.downloadTasks.add(pending);});
   return receipt;
  });
 }
 waitApproval(active,id){return new Promise((resolve,reject)=>{const finish=(error)=>{this.bridge.policy.removeListener('approval',listener);active.controller.signal.removeEventListener('abort',abort);error?reject(error):resolve();},listener=record=>{if(record.id!==id)return;if(record.status==='approved')finish();else if(['rejected','expired','revoked'].includes(record.status))finish(Error('Protected research approval was not granted'));},abort=()=>finish(Error('Research cancelled while awaiting approval'));this.bridge.policy.on('approval',listener);active.controller.signal.addEventListener('abort',abort,{once:true});if(active.controller.signal.aborted)abort();else{const current=this.bridge.policy.approvals.get(id);if(current)listener(current);}});}
 resumeApproved(approval){const m=this.store.missionForTask(approval.taskId),active=m&&this.active.get(m.id);if(!active||active.pendingApproval!==approval.id)return{resumed:false,reason:'A fresh bounded research Mission is required; stopped browser actions never replay.'};return{resumed:true,mission_id:m.id,approval_id:approval.id};}
 browserApproval(m,action){if(action.type==='authenticate')return !!this.credentials.consumedApproval(m,action);return [...this.bridge.policy.approvals.values()].some(p=>p.taskId===m.task_id&&p.status==='consumed'&&p.toolName==='capability'&&fingerprint(p.input)===fingerprint({name:'browser_research',input:{mission_id:m.id,action}}));}
 async launch(dispatch,m){
  const task=this.assertContract(m,{execution:true});this.service.assertAuthority(m,{network:['internet'],repository:['read'],data:['read']});
  const C=require('./research-browser').ResearchBrowser;
  const runId=randomUUID(),controller=new AbortController(),evidenceDir=path.join(task.sessionDir,'research-evidence'),active={runId,taskId:task.id,controller,receipts:[],evidence:[],operation:false,browser:null};let started=false,closeResult=null;const startedAt=Date.now();
  const timer=setTimeout(()=>controller.abort(),this.timeoutMs);timer.unref?.();
  try{
   active.browser=this.options.browserFactory?this.options.browserFactory({scope:m.envelope.manifest.scope,evidenceDir,signal:controller.signal,onEvent:e=>this.browserEvent(m,runId,e),accountAuthorization:m.envelope.manifest.account_authorization,resolveCredential:(ref,grant)=>this.credentials.resolve(ref,{...grant,mission_id:m.id}),approve:({action})=>this.browserApproval(this.store.requireMission(m.id),action)}):new C({scope:m.envelope.manifest.scope,evidenceDir,signal:controller.signal,onEvent:e=>this.browserEvent(m,runId,e),accountAuthorization:m.envelope.manifest.account_authorization,resolveCredential:(ref,grant)=>this.credentials.resolve(ref,{...grant,mission_id:m.id}),approve:({action})=>this.browserApproval(this.store.requireMission(m.id),action)});
   transaction(this.db,()=>{this.assertContract(this.store.requireMission(m.id),{execution:true});if(this.db.prepare("SELECT 1 FROM cp_leases WHERE resource=? AND mode='write' AND state IN ('held','quarantined')").get(task.workspace))throw Error('Arecibo writer lease prevents research');this.store.startRun({id:runId,taskId:task.id,missionId:m.id,agentId:'host'});this.store.acquireLease({resource:task.workspace,runId,missionId:m.id,mode:'read',baseline:m.envelope.baseline,ttlMs:this.timeoutMs});
    this.store.updateRun(runId,{state:'starting',processState:'starting'});started=true;});
   this.active.set(m.id,active);
   const available=await active.browser.qualify();if(available.available!==true)throw Error('Governed browser runtime is unavailable');
   const observation={host:{implemented:true,capabilities:['browser_research'],runtime_profile:{availability:'available',auth_state:'not_required',quota_state:'available',circuit_state:'closed',cost_class:'local',transport:'in_process'}}};
   const route=this.bridge.authorityRuntime?.routing?await this.bridge.authorityRuntime.route(m,observation):{selected:'host',reason:PROFILE,transport:'in_process'};if(route.selected!=='host')throw Error('Governed host research route is unavailable');this.bridge.authorityRuntime?.assertDispatch(m,route);
   transaction(this.db,()=>{this.assertContract(this.store.requireMission(m.id),{execution:true});this.store.updateRun(runId,{state:'running',processState:'alive',pid:active.browser.ownedProcessId?.()});this.db.prepare("UPDATE cp_dispatches SET state='running',run_id=?,route=?,updated_at=? WHERE id=? AND state='queued'").run(runId,JSON.stringify(route),Date.now(),dispatch.id);this.store.state(m.id,'running');task.activeRunId=runId;task.status='running';task.assignedAgent='host';task.mission.started=true;task.mission.status='active';require('./execution-evidence').begin(task,runId);this.bridge.tasks.save(task);started=true;});
   this.phase(m.id,'browser');const visit=async url=>{let nav=await this.call(m,task,active,{type:'navigate',url});if(nav?.state==='human_takeover_required')throw Object.assign(Error('Account needs human takeover'),{code:'human_takeover_required'});if(nav?.login_forms?.length&&m.envelope.manifest.account_authorization&&!active.authenticated){const a=m.envelope.manifest.account_authorization,form=nav.login_forms[0];active.evidence.push(nav);const auth=await this.call(m,task,active,{type:'authenticate',form_id:form.id,username_reference:a.username_reference,password_reference:a.password_reference,approval_id:a.id});if(auth.state!=='authenticated')throw Object.assign(Error('Account needs human takeover'),{code:'human_takeover_required'});active.authenticated=true;nav={state:'navigated'};}if(nav?.state==='blocked'){active.evidence.push(nav);return null;}const row=await this.call(m,task,active,{type:'snapshot'});if(row?.classification==='observed')active.evidence.push(row);else{active.evidence.push(row);return null;}
    this.phase(m.id,'responsive');if(!active.authenticated)for(const size of [{width:1280,height:800},{width:390,height:844}]){await this.call(m,task,active,{type:'viewport',...size});const shot=await this.call(m,task,active,{type:'screenshot'});if(shot?.classification==='observed')active.evidence.push(shot);}return row;};
   const first=await visit(m.envelope.manifest.entry_url);this.phase(m.id,'browser','completed');this.phase(m.id,'inventory');
   if(first&&active.authenticated){
    let current=first;const seen=new Set();for(let page=1;page<this.maxPages;page++){const link=(current.links||[]).find(l=>UUID.test(l.id||'')&&typeof l.category==='string'&&!seen.has(l.category));if(!link)break;seen.add(link.category);const next=await this.call(m,task,active,{type:'click',link_id:link.id});if(next?.state==='human_takeover_required')throw Object.assign(Error('Account needs human takeover'),{code:'human_takeover_required'});if(next?.classification==='inaccessible'){active.evidence.push(next);break;}current=await this.call(m,task,active,{type:'snapshot'});active.evidence.push(current);if(current.classification!=='observed')break;}
   }else if(first){const seen=new Set([first.url]),links=first.links.filter(l=>typeof l.url==='string'&&new URL(l.url).origin===m.envelope.manifest.scope.origins[0]).sort((a,b)=>score(b)-score(a));for(const link of links){if(seen.size>=this.maxPages)break;if(seen.has(link.url)||/\b(?:login|signin|sign-in|signup|register|logout|checkout|cart|account|auth|unsubscribe)\b/i.test(link.url))continue;seen.add(link.url);await visit(link.url);}}
   active.finishing=true;await Promise.all([...(active.downloadTasks||[])]);if(active.manualError)throw active.manualError;
   this.phase(m.id,'inventory','completed');this.phase(m.id,'responsive',active.authenticated?'attention':'completed',active.authenticated?{reason:'account_screenshots_disabled'}:{});this.phase(m.id,'comparison');
   this.assertContract(this.store.requireMission(m.id),{execution:true});const baseline=this.baseline(task.workspace),evidenceStore={verify:row=>active.browser.verify(row)};
   const reporter=this.options.reportFactory?this.options.reportFactory({baseline,evidenceStore}):new (require('./research-report').ResearchReport)({baseline,evidenceStore});
   const report=await reporter.build({competitor:m.envelope.manifest.scope.origins[0],evidence:active.evidence,baselineSnapshot:m.envelope.research_baseline});this.phase(m.id,'comparison','completed');this.phase(m.id,'report','completed');
   if(typeof report.markdown!=='string'||report.markdown.length>24000)throw Error('Bounded verified research report required');
   closeResult=await active.browser.close();if(!closeResult?.termination_verified)throw Object.assign(Error('Browser termination unverified'),{code:'termination_unverified'});
   this.assertContract(this.store.requireMission(m.id),{execution:true,fullBaseline:true});if(controller.signal.aborted)throw Error('Research cancelled');
   const evidence={profile:PROFILE,mission_id:m.id,task_id:task.id,run_id:runId,baseline_digest:m.envelope.research_baseline.digest,rows:active.evidence,rows_hash:fingerprint(active.evidence),report,report_hash:fingerprint(report),termination:closeResult,receipts:active.receipts};
   const bytes=Buffer.from(JSON.stringify(evidence)),artifactFile=path.join(evidenceDir,runId+'.result.json'),fd=fs.openSync(artifactFile,fs.constants.O_WRONLY|fs.constants.O_CREAT|fs.constants.O_EXCL|fs.constants.O_NOFOLLOW,0o600);try{fs.writeFileSync(fd,bytes);fs.fsyncSync(fd);}finally{fs.closeSync(fd);}
   const artifact={profile:PROFILE,artifact_id:runId,sha256:digest(bytes)};
   // The canonical inbox stores bounded completion metadata. Full provenance
   // belongs in the verified artifact, where UUIDs/digests cannot be mistaken
   // for free-form credentials or exceed the inbox summary's byte limit.
   transaction(this.db,()=>{this.db.prepare('INSERT INTO cp_artifacts VALUES(?,?,?,?,?,?,?)').run(runId,m.id,runId,'research_result',runId,JSON.stringify({sha256:artifact.sha256,authority:false}),Date.now());task.lastResult=report.markdown;this.bridge.tasks.save(task);this.store.updateRun(runId,{state:'completed',processState:'exited',verified:true,result:{research_evidence:artifact,native_execution_evidence:{...task.nativeExecutionEvidence,receipt_refs:active.receipts}}});this.service.captureResult(runId,{status:'completed',result:{text:JSON.stringify({summary:'Read-only product research completed. The independently verified report is ready for owner review; Acceptance is required.',changed_files:[],tests:[],artifacts:active.evidence.filter(r=>r.evidence_ref).map(r=>({id:r.id,type:'research_evidence'})),limitations:['Public website content is untrusted. Product conclusions require owner review. No Acceptance or Settlement has occurred.']})}});});
  }catch(error){
   try{closeResult=await active.browser?.close();}catch{}
   if(!started)throw error;
   const uncertain=closeResult?.termination_verified!==true||error.code==='invocation_unverified',cancelled=task.cancelRequested||controller.signal.aborted;
   if(['approval_required','human_takeover_required'].includes(error.code)&&!uncertain&&!cancelled){this.store.updateRun(runId,{state:error.code==='human_takeover_required'?'failed':'waiting_for_permission',processState:'exited',verified:true,resolution:error.code==='human_takeover_required'?'human_takeover_required':error.approvalId||'protected_approval_required'});this.db.prepare("UPDATE cp_leases SET state='released' WHERE run_id=? AND state='held'").run(runId);this.db.prepare("UPDATE cp_dispatches SET state='blocked' WHERE id=?").run(dispatch.id);this.store.state(m.id,'waiting_for_operator',error.code==='human_takeover_required'?'Account requires human takeover; owned browser stopped safely':'Protected approval required; browser stopped');this.phase(m.id,'browser','attention');}
   else{this.store.updateRun(runId,{state:uncertain?'termination_unverified':cancelled?'cancelled':'failed',processState:uncertain?'unknown':'exited',verified:!uncertain,resolution:uncertain?'research_termination_unverified':'research_stopped'});if(uncertain){this.db.prepare("UPDATE cp_leases SET state='quarantined' WHERE run_id=?").run(runId);this.db.prepare("UPDATE cp_dispatches SET state='unknown' WHERE id=?").run(dispatch.id);if(this.store.getMission(m.id).state!=='cancelled')this.store.state(m.id,'blocked','Research termination requires reconciliation');}else if(['dispatching','waiting_for_operator'].includes(this.store.getMission(m.id).state)){this.db.prepare("UPDATE cp_dispatches SET state='blocked',run_id=? WHERE id=?").run(runId,dispatch.id);this.store.state(m.id,'blocked','Governed browser qualification or route unavailable');}else if(this.store.getMission(m.id).state!=='cancelled')this.service.captureResult(runId,{status:'failed',result:{text:JSON.stringify({summary:'Public research stopped safely; inspect the scoped Mission before retrying.',changed_files:[],tests:[],artifacts:[],limitations:['Research did not complete; no verified comparison or Acceptance.']})}});}
  }finally{clearTimeout(timer);this.active.delete(m.id);delete task.activeRunId;task.mission.used.runtimeMs+=Date.now()-startedAt;this.bridge.tasks.save(task);this.bridge.emit('change');}
 }
 browserEvent(m,runId,event){const type=/^research\.[a-z_]+$/.test(event?.type||'')?event.type:'research.browser_event';const metadata={authority:false};if(UUID.test(event?.id||''))metadata.evidence_id=event.id;if(typeof event?.termination_verified==='boolean')metadata.termination_verified=event.termination_verified;if(['observed','inaccessible'].includes(event?.classification))metadata.classification=event.classification;this.store.event(type,m.id,metadata,{runId});}
 artifact(m,run){
  const ref=run.result?.research_evidence,task=this.bridge.tasks.get(run.task_id);if(!ref||ref.profile!==PROFILE||ref.artifact_id!==run.id||task.content_state==='erased')throw Error('Research artifact unavailable');
  const a=this.db.prepare('SELECT * FROM cp_artifacts WHERE id=? AND mission_id=? AND run_id=?').get(ref.artifact_id,m.id,run.id);
  if(!a||a.kind!=='research_result'||a.reference!==run.id||JSON.parse(a.metadata).sha256!==ref.sha256)throw Error('Canonical research artifact binding unavailable');
  const file=path.join(this.evidenceDirectory(task),run.id+'.result.json'),fd=fs.openSync(file,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);
  try{const stat=fs.fstatSync(fd);if(!stat.isFile()||stat.nlink!==1||stat.uid!==process.getuid?.()||stat.mode&0o077||stat.size>2097152)throw Error('Research artifact integrity denied');const bytes=fs.readFileSync(fd);if(digest(bytes)!==ref.sha256)throw Error('Research artifact preimage changed');const e=JSON.parse(bytes);if(e.mission_id!==m.id||e.task_id!==task.id||e.run_id!==run.id||e.profile!==PROFILE)throw Error('Research artifact identity changed');return e;}finally{fs.closeSync(fd);}
 }
 evidenceDirectory(task){const session=path.resolve(this.bridge.dataDir,'tasks',task.id,'sessions'),dir=path.join(session,'research-evidence');if(task.sessionDir!==session)throw Error('Canonical research session required');for(const directory of [session,dir]){const stat=fs.lstatSync(directory);if(!stat.isDirectory()||stat.isSymbolicLink()||stat.uid!==process.getuid?.()||stat.mode&0o077||fs.realpathSync(directory)!==directory)throw Error('Research evidence directory scope denied');}return dir;}
 assertAcceptance(m,verificationId){
  const v=this.db.prepare('SELECT run_id FROM cp_verifications WHERE id=? AND mission_id=?').get(verificationId,m.id);if(!v)throw Error('Research independent verification unavailable');
  const run=this.store.run(v.run_id),e=this.artifact(m,run),verifier=this.options.verifyEvidence||require('./research-browser').verifyEvidence;
  if(!run.termination_verified||e.baseline_digest!==m.envelope.research_baseline.digest||e.termination?.closed!==true||e.termination?.termination_verified!==true||e.termination?.owned_process_termination!=='verified'||e.report_hash!==fingerprint(e.report)||e.rows_hash!==fingerprint(e.rows)||e.rows.some(row=>verifier(row,{evidenceDir:path.join(this.bridge.tasks.get(run.task_id).sessionDir,'research-evidence'),scope:m.envelope.manifest.scope})!==true))throw Error('Research Acceptance artifact integrity unavailable');
 }
 async verify(m,run){
  const checks=[],add=(id,status,evidence)=>checks.push({id,status,evidence});let hash='unavailable';
  try{this.assertContract(m);const before=this.safeSnapshot(m);hash=before.hash;const e=this.artifact(m,run);
   if(run.agent_id!=='host'||run.task_id!==m.task_id||run.state!=='completed'||!run.termination_verified||!e||e.profile!==PROFILE)throw Error('Canonical research evidence unavailable');
   add('browser_termination',e.termination?.closed&&e.termination.termination_verified&&e.termination.owned_process_termination==='verified'?'passed':'failed',{termination_verified:e.termination?.termination_verified===true});
   const invocations=e.receipts.map(id=>this.store.invocation(id));add('native_execution',require('./execution-evidence').runSatisfied(run)&&e.receipts.length===run.result.native_execution_evidence.completed_invocations&&invocations.every(i=>i?.task_id===run.task_id&&i.state==='settled'&&i.result?.status==='completed'&&i.result?.capability==='browser_research')?'passed':'failed',{completed_invocations:invocations.filter(i=>i?.result?.status==='completed').length});
   const verifier=this.options.verifyEvidence||require('./research-browser').verifyEvidence;let valid=e.rows_hash===fingerprint(e.rows)&&e.report_hash===fingerprint(e.report)&&e.baseline_digest===m.envelope.research_baseline.digest;
   for(const row of e.rows){valid=await verifier(row,{evidenceDir:path.join(this.bridge.tasks.get(run.task_id).sessionDir,'research-evidence'),scope:m.envelope.manifest.scope})&&valid;}
   add('artifact_integrity',valid?'passed':'failed',{evidence_count:e.rows.length,immutable_artifacts_rehashed:true});
   add('baseline_integrity',this.baseline(m.envelope.workspace).verify(m.envelope.research_baseline)?'passed':'failed',{baseline_digest:m.envelope.research_baseline.digest});
   add('read_only_boundary',before.hash===m.envelope.baseline.hash&&!m.envelope.allowed_files.length?'passed':'failed',{approved_sources_unchanged:before.hash===m.envelope.baseline.hash,filesystem_write_permission:false,scope:'approved_research_sources'});const after=this.safeSnapshot(m);hash=after.hash;add('verification_workspace_stable',after.hash===before.hash?'passed':'failed',{before:before.hash,after:after.hash,scope:'approved_research_sources'});
   add('report','operator_review',{factual_accuracy:'owner_review_required',accepted:false});
  }catch{add('research_evidence_available','failed',{reason:'research_evidence_unavailable'});}
  return{status:checks.some(c=>c.status==='failed')?'failed':'operator_review',checks,workspace_hash:hash};
 }
 async report(id,owner='operator'){if(owner!=='operator')throw Error('Authenticated operator research report access required');const m=this.store.requireMission(id);if(m.envelope.kind!=='browser_research')throw Error('Research Mission required');const rows=this.db.prepare("SELECT id FROM cp_runs WHERE mission_id=? AND agent_id='host' AND state='completed' AND termination_verified=1 ORDER BY ended_at DESC").all(id);const run=rows.map(r=>this.store.run(r.id)).find(r=>r.result?.research_evidence);if(!run)throw Error('Research report is unavailable');const verification=await this.verify(m,run);if(verification.status!=='operator_review')throw Error('Research report integrity unavailable');const e=this.artifact(m,run);return{mission_id:id,markdown:e.report.markdown,report:publicReport(e.report),screenshots:e.rows.filter(r=>r.screenshot_ref).map(r=>({id:r.id,viewport:r.viewport,sha256:r.screenshot_ref.sha256})),accepted:m.state==='completed',authority:false};}
 async evidence(id,evidenceId,owner='operator'){
  if(owner!=='operator'||!UUID.test(evidenceId||''))throw Error('Authenticated operator evidence access required');await this.report(id);
  const run=this.db.prepare("SELECT id FROM cp_runs WHERE mission_id=? AND state='completed' ORDER BY ended_at DESC").all(id).map(r=>this.store.run(r.id)).find(r=>r.result?.research_evidence);
  const m=this.store.requireMission(id),e=this.artifact(m,run),evidenceDir=this.evidenceDirectory(this.bridge.tasks.get(run.task_id)),row=e.rows.find(r=>r.id===evidenceId&&r.screenshot_ref?.id===evidenceId);if(!row)throw Error('Research screenshot is unavailable');
  const ref=row.screenshot_ref;if(ref.path!==path.join(evidenceDir,evidenceId+'.png'))throw Error('Research screenshot scope denied');const fd=fs.openSync(ref.path,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);
  try{const stat=fs.fstatSync(fd);if(!stat.isFile()||stat.nlink!==1||stat.mode&0o077||stat.uid!==process.getuid?.()||stat.size>4194304)throw Error('Research screenshot integrity denied');const buffer=fs.readFileSync(fd);if(digest(buffer)!==ref.sha256)throw Error('Research screenshot integrity denied');return{buffer,mime:'image/png'};}finally{fs.closeSync(fd);}
 }
 progress(m){const events=this.bridge.ledger.list({missionId:m.id,eventType:'research.phase',limit:500,order:'asc'}).events.filter(e=>e.event_type==='research.phase'),states=new Map(events.map(e=>[e.metadata.phase,e.metadata.state]));if(['awaiting_acceptance','completed'].includes(m.state)){states.set('verification','completed');states.set('acceptance',m.state==='completed'?'completed':'attention');}else if(m.state==='verifying')states.set('verification','active');const review=this.db.prepare('SELECT result FROM cp_mission_reviews WHERE mission_id=? ORDER BY created_at DESC LIMIT 1').get(m.id);if(review)states.set('review',review.result==='failed'?'attention':'completed');const settlement=this.db.prepare('SELECT state FROM cp_mission_settlements WHERE mission_id=?').get(m.id);if(settlement?.state==='settled')states.set('settlement','completed');return{title:'ARECIBO PRODUCT RESEARCH',steps:PHASES.map((id,i)=>({id,label:LABELS[i],state:states.get(id)||'pending'})),report_available:['awaiting_acceptance','completed'].includes(m.state)};}
 cancel(id){this.active.get(id)?.controller.abort();}
 isActiveTask(id){return [...this.active.values()].some(active=>active.taskId===id);}
 recover(m){for(const row of this.db.prepare("SELECT id,state FROM cp_runs WHERE mission_id=? AND termination_verified=0 AND state IN ('running','starting','waiting_for_permission','interrupted','termination_unverified')").all(m.id)){if(row.state!=='interrupted')this.store.updateRun(row.id,{state:'termination_unverified',processState:'unknown',resolution:'research_owned_process_reconciliation_required'});this.db.prepare("UPDATE cp_leases SET state='quarantined' WHERE run_id=? AND state='held'").run(row.id);if(['ready','dispatching','running','verifying','waiting_for_operator'].includes(this.store.getMission(m.id).state))this.store.state(m.id,'blocked','Research owned process requires reconciliation');}}
 async close(){for(const active of this.active.values())active.controller.abort();await Promise.allSettled([...this.active.values()].map(a=>a.browser?.close()));}
}
function score(link){return /pricing|features|products|platform|solutions|integration|security|about|docs|developer|api/i.test(link.text+' '+new URL(link.url).pathname)?1:0;}
function publicReport(value){if(Array.isArray(value))return value.map(publicReport);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).filter(([key,v])=>key!=='evidence_dir'&&!(key==='path'&&typeof v==='string'&&path.isAbsolute(v))).map(([k,v])=>[k,publicReport(v)]));return value;}
module.exports={ResearchMission,PROFILE,PHASES};
