'use strict';
// Cell geometry sampled from the canonical even-odd SVG. No terminal graphics dependency.
const fs=require('node:fs'),path=require('node:path');
const geometry=fs.readFileSync(path.join(__dirname,'../public/brand/airodrom-mark.svg'),'utf8').match(/<path d="([^"]+)"/)[1].split(' M').map(s=>[...s.matchAll(/(?:M|L)?\s*(-?\d+\.\d+),(-?\d+\.\d+)/g)].map(m=>[+m[1],+m[2]]));
function inside(x,y){let filled=false;for(const poly of geometry){let hit=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>y)!==(b[1]>y)&&x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0])hit=!hit;}if(hit)filled=!filled;}return filled;}
function colorMode({tty=false,env=process.env}={}){if(!tty||env.NO_COLOR!==undefined||env.TERM==='dumb')return'none';if(/truecolor|24bit/i.test(env.COLORTERM||''))return'truecolor';return /256color/.test(env.TERM||'')?'256':'16';}
function sample(x,y,w,h){const px=x/w*256,py=y/h*256;if(inside(px,py))return y<5?'highlight':'front';if(inside(px-20,py-16))return'depth';if(inside(px-28,py-25))return'shadow';return null;}
function rgb(type,y,h){if(type==='depth')return[72,58,155];if(type==='shadow')return[32,42,65];if(type==='highlight')return[151,255,224];const t=y/h;return t<.25?[133,225,255]:[80,145,255];}
function sgr(type,y,h,mode,bg=false){if(!type)return`\x1b[${bg?49:39}m`;const c=rgb(type,y,h),channel=bg?48:38;if(mode==='truecolor')return`\x1b[${channel};2;${c.join(';')}m`;if(mode==='256')return`\x1b[${channel};5;${16+36*Math.round(c[0]/51)+6*Math.round(c[1]/51)+Math.round(c[2]/51)}m`;const ansi={front:94,highlight:96,depth:34,shadow:90}[type];return`\x1b[${bg?ansi+10:ansi}m`;}
function mark({mode='none',compact=false,unicode=true}={}){const w=compact?20:32,h=compact?14:26,lines=[];for(let y=0;y<h;y+=2){let row='';for(let x=0;x<w;x++){const top=sample(x,y,w,h),bottom=sample(x,y+1,w,h);if(mode==='none')row+=top||bottom?(unicode?({front:'█',highlight:'▀',depth:'▓',shadow:'░'}[top||bottom]):({front:'#',highlight:'#',depth:'+',shadow:'.'}[top||bottom])):' ';else if(top)row+=sgr(top,y,h,mode)+sgr(bottom,y+1,h,mode,true)+'▀';else if(bottom)row+=sgr(bottom,y+1,h,mode)+sgr(null,y,h,mode,true)+'▄';else row+=sgr(null,y,h,mode)+sgr(null,y,h,mode,true)+' ';}lines.push(row+(mode==='none'?'':'\x1b[0m'));}return lines;}
function wrap(text,width){const lines=[];let line='';for(const word of text.split(' ')){if(line&&line.length+word.length+1>width){lines.push(line);line='';}line+=(line?' ':'')+word;}if(line)lines.push(line);return lines.join('\n');}
function intro({color=false,mode,unicode=true,columns=80}={}){mode=mode|| (color?'truecolor':'none');const compact=columns<72,title=(mode==='none'?'AIRODROM':'\x1b[96mAIRODROM\x1b[0m')+'\n'+wrap('MANY AGENTS. ONE CONTROL PLANE.',columns)+'\n',version=require('../package.json').version+' · PRE-RELEASE';if(columns<28)return title+'PRE-RELEASE\n';const art=mark({mode,compact,unicode});const info=[version,'Bounded local work. Durable authority.','Independent verification. Memory V2.'];if(compact)return art.join('\n')+'\n'+title+version+'\n';return title+art.map((line,i)=>line+'  '+(info[i]||'')).join('\n')+'\n';}
module.exports={colorMode,mark,intro,inside};
